<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_profocupation' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="span6"><?php echo $this->form->getElement( 'fk_id_profgroup' ); ?></div>
	    <div class="span6"><?php echo $this->form->getElement( 'fk_id_profsubgroup' ); ?></div>
	</div>
	<div class="row-fluid">
	    <div class="span6"><?php echo $this->form->getElement( 'fk_id_profminigroup' ); ?></div>
	    <div class="span6"><?php echo $this->form->getElement( 'ocupation_name' ); ?></div>
	</div>
	<div class="row-fluid">
	    <div class="span6"><?php echo $this->form->getElement( 'acronym' ); ?></div>
	    <div class="span6"><?php echo $this->form->getElement( 'description' ); ?></div>
	</div>
	
	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>