<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->group_acronym; ?></td>
	<td class="hidden-480"><?php echo $row->sub_group_acronym; ?></td>
	<td class="hidden-480"><?php echo $row->mini_group_acronym; ?></td>
	<td><?php echo $row->acronym; ?></td>
	<td><?php echo $row->ocupation_name; ?></td>
	<td>
	    <?php if ( $this->access( Register_Form_InternationalOccupation::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
		<a class="btn green" href="<?php echo $this->baseUrl( 'register/international-occupation/edit/id/' . $row->id_profocupation ); ?>">
		    <i class="icon-edit"></i>  
		    Troka                                            
		</a>
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>  
		    La bele acessu                                            
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>