<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_profocupationtimor' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_isicdivision' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_isicgroup' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <div class="row-fluid">
			<?php echo $this->form->getElement( 'fk_id_isicclass' ); ?>
		    </div>
		    <div class="row-fluid">
			<?php echo $this->form->getElement( 'name_classtimor' ); ?>
		    </div>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'description' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<?php echo $this->form->getElement( 'acronym' ); ?>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>