<?php
    $this->headLink()->appendStylesheet( $this->baseUrl( 'public/template/plugins/bootstrap-tree/bootstrap-tree/css/bootstrap-tree.css' ) );
    $this->headScript()->appendFile( $this->baseUrl( 'public/template/plugins/bootstrap-tree/bootstrap-tree/js/bootstrap-tree.js' ) );
?>

<div class="box-content">
    <div class="row-fluid">
	<div class="span12">
	    <?php echo $this->form; ?>
	</div>
    </div>
    
    <div class="row-fluid">
	<div class="span12">
	    <div class="portlet box grey">
		<div class="portlet-title">
		    <div class="caption">
			<i class="icon-reorder"></i>
			Permissaum sira
		    </div>
		    <div class="actions">
			<a href="javascript:;" id="access_collapse" class="btn green"> 
			    Collapse All
			</a>
			<a href="javascript:;" id="access_expand" class="btn yellow"> 
			    Expand All
			</a>
		    </div>
		</div>
		<div class="portlet-body fuelux">
		    <ul id="user_access" class="tree">
			<?php foreach ( $this->data as $module ) : ?>
			    <li>
				<a href="#" data-role="branch" class="tree-toggle closed" data-toggle="branch">
				    <?php echo $module['module']; ?>
				</a>
				<ul class="branch">
					<?php foreach ( $module['forms'] as $idForm => $form ) : ?>
					    <li>
						<a href="#" class="tree-toggle closed" data-toggle="branch">
						    <?php echo $form['form']; ?>
						</a>
						<ul class="branch">
						    <?php foreach ( $form['operations'] as $operation ) : ?>
						    <li>
							<div class="controls">
							    <label class="checkbox">
								<input type="checkbox"
								<?php if ( !$this->access( Admin_Form_UserForm::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) echo 'disabled' ?>
								id="oper_<?php echo $idForm; ?>_<?php echo $operation->id_sysoperation; ?>" 
								value='<?php echo json_encode( $operation->toArray() ); ?>' />
								<?php echo $operation->operation; ?>
							    </label>
							</div>
						    </li>
						    <?php endforeach; ?>
						</ul>
					    </li>
					<?php endforeach; ?>
				</ul>
			    </li>
			<?php endforeach; ?>
		    </ul>

		</div>
	    </div>
	</div><!--/span-->
    </div>
    
</div>