<?php
    $colors = array( 'grey', 'red', 'blue', 'yellow', 'purple', 'green' );
    $cont = 0;
    foreach ( $this->files as $folder => $files ) :
?>
<div class="row-fluid">
    <div class="span12">
	<div class="portlet box <?php echo $this->cycle( $colors )->next(); ?>">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-file"></i><?php echo $folder; ?></div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="table_<?php echo $cont++; ?>">
		    <thead>
			<tr>
			     <th>Arkivu</th>
			     <th>Hira</th>
			     <th>Tipu</th>
			     <th>Data</th>
			     <th>Asaun</th>
			</tr>
		    </thead>
		    <tbody>
			<?php foreach ( $files as $file ) : ?>
			    <tr>
				<td><?php echo $file['name']; ?></td>
				<td><?php echo $file['size']; ?></td>
				<td><?php echo $file['type']; ?></td>
				<td><?php echo $file['date']; ?></td>
				<td>
				    <button class="btn green" type="button" title="Download" onClick="Default.Form.download('<?php echo $this->baseUrl( $file['path'] ); ?>');">
					<i class="icon-download icon-white"></i>
				    </button>
				</td>
			    </tr>
			<?php endforeach; ?>
		    </tbody>
		</table>
	    </div>
	</div>
    </div>
</div>
<?php endforeach; ?>