<?php $this->headScript()->appendFile( $this->baseUrl( 'public/scripts/controller/default/dashboard.js' ) ); ?>
<div class="margin-bottom-25"></div>
<div class="row-fluid margin-bottom-20">
    <div class="span12">
	<div class="logo-print">
	    <img src="<?php echo $this->baseUrl( 'public/images/brasao_print.png' ); ?>" />
	</div>
	<h4 class="text-center">SECRETARIA DE ESTADO PARA POLÍTICA DA FORMAÇÃO PROFISSIONAL E EMPREGO</h4>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box red ">
	    <div class="portlet-title"  style="cursor: pointer">
		<div class="caption"><i class="icon-briefcase"></i>Klik iha ne'e ba haree vaga serbisu</div>
		<div class="tools"><a href="javascript:;" class="expand"></a></div>
	    </div>
	    <div class="portlet-body form hide">
		<table class="table table-striped table-bordered table-hover table-full-width" id="job-list">
		    <thead>
			<tr>
			    <th>Titulu</th>
			    <th>Empreza</th>
			    <th>Posizaun Hira</th>
			    <th>Data taka</th>
			    <th></th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box grey ">
	    <div class="portlet-title"  style="cursor: pointer">
		<div class="caption"><i class="icon-book"></i>Klik iha ne'e ba haree Formasaun Profisional</div>
		<div class="tools"><a href="javascript:;" class="expand"></a></div>
	    </div>
	    <div class="portlet-body form hide">
		<table class="table table-striped table-bordered table-hover table-full-width" id="training-list">
		    <thead>
			<tr>
			    <th>#</th>
			    <th>Titulu</th>
			    <th>Sentru Formasaun</th>
			    <th>Data Hahu</th>
			    <th>Data Taka</th>
			    <th></th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box green ">
	    <div class="portlet-title" style="cursor: pointer">
		<div class="caption"><i class="icon-home"></i>Klik iha ne'e ba haree Kontatu CEOP</div>
		<div class="tools"><a href="javascript:;" class="expand"></a></div>
	    </div>
	    <div class="portlet-body form hide">
		<table class="table table-striped table-bordered table-hover table-full-width" id="ceop-list">
		    <thead>
			<tr>
			    <th>CEOP</th>
			    <th>E-mail</th>
			    <th>Kontatu</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>

<script type="text/javascript">
    $( document ).ready(
	function() 
	{    
	    App.init();
	}
    );
</script>