<table class="table table-striped table-bordered table-hover table-full-width" id="expense-list">
    <thead>
	<tr>
	    <th>Komponente</th>
	    <th>Rúbrica</th>
	    <th>Asaun</th>
	</tr>
    </thead>
    <tbody>
	<?php foreach ( $this->rows as $row ) : ?>
	    <tr>
		<td><?php echo $row->type_expense; ?></td>
		<td><?php echo $row->description; ?></td>
		<td>
		    <a class="btn red action-ajax" href="javascript:;" data-id="<?php echo $row->id_budget_category; ?>">
			<i class="icon-ok"></i>                                     
		    </a>
		</td>
	    </tr>
	<?php endforeach; ?>
    </tbody>
</table>
