<?php 
    $this->headLink()->appendStylesheet( $this->baseUrl( 'public/template/plugins/jquery-file-upload/css/jquery.fileupload-ui.css' ) );
    $this->headLink()->appendStylesheet( $this->baseUrl( 'public/template/plugins/bootstrap-tree/bootstrap-tree/css/bootstrap-tree.css' ) );

    $this->headScript()->appendFile( $this->baseUrl( 'public/template/plugins/jquery-file-upload/js/vendor/jquery.ui.widget.js' ) ); 
    $this->headScript()->appendFile( $this->baseUrl( 'public/template/plugins/jquery-file-upload/js/vendor/tmpl.min.js' ) ); 
    $this->headScript()->appendFile( $this->baseUrl( 'public/template/plugins/jquery-file-upload/js/jquery.fileupload.js' ) ); 
    $this->headScript()->appendFile( $this->baseUrl( 'public/template/plugins/jquery-file-upload/js/jquery.fileupload-fp.js' ) ); 
    $this->headScript()->appendFile( $this->baseUrl( 'public/template/plugins/jquery-file-upload/js/jquery.fileupload-ui.js' ) ); 
    $this->headScript()->appendFile( $this->baseUrl( 'public/template/plugins/bootstrap-tree/bootstrap-tree/js/bootstrap-tree.js' ) );
    $this->headScript()->appendFile( $this->baseUrl( 'public/scripts/controller/fefop/contract.js' ) ); 
?>
<div class="row-fluid <?php if ( empty( $this->id ) ) echo 'hide'; ?>">
    <div class="span12" id="container-num-training-plan">
	<?php if ( !empty( $this->id ) ) : ?>
	    <span class="well pull-right number-system" id="drn-training-plan-number">
		<strong>
		    <?php echo Fefop_Model_Mapper_DRHTrainingPlan::buildNum( $this->id ); ?>
		</strong>
	    </span>
	<?php endif; ?>
    </div>
</div>

<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_drh_trainingplan' );
    echo $this->form->getElement( 'fk_id_fefpeduinstitution' );
    echo $this->form->getElement( 'fk_id_addcountry' );
    echo $this->form->getElement( 'need_insurance' );
 ?>

    <?php echo $this->fefopContract()->getMessages(); ?>

    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span11">
		    <?php echo $this->form->getElement( 'entity' ); ?>
		</div>
		<div class="span1">
		    <div class="control-group">
			<label class="control-label">&#160;</label>
			<div class="controls">
			    <a class="btn green" title="Buka Instituisaun" href="javascript:;" 
				onclick="Fefop.DRHTrainingPlan.searchInstitute()">
				 <i class="icon-search"></i>  
			     </a>
			</div>
		    </div>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_scholarity_area' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_profocupationtimor' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span4">
		    <?php echo $this->form->getElement( 'modality' ); ?>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'country' ); ?>
		</div>
		<div class="span4 hide">
		    <?php echo $this->form->getElement( 'country_timor' ); ?>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'city' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span4">
		    <?php echo $this->form->getElement( 'date_start' ); ?>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'date_finish' ); ?>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'duration_days' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span8">
		    <div class="span3">
			<strong class="pull-right">Seguro moris</strong>
		    </div>
		    <div class="span9 well" id="health-insurance" style="padding: 5px 0 0 10px">
			<div class="row-fluid beneficiary">
			    <p class="text-error bold hide">
				<i class="icon-remove"></i>
				Benefisiariu presiza seguru
			    </p>
			    <p class="text-success bold hide">
				<i class="icon-ok"></i>
				Benefisiariu la presiza seguru
			    </p>
			</div>
			<div class="row-fluid trainer">
			    <p class="text-error bold hide">
				<i class="icon-remove"></i>
				Formador presiza seguru
			    </p>
			    <p class="text-success bold hide">
				<i class="icon-ok"></i>
				Formador la presiza seguru
			    </p>
			</div>
		    </div>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'amount' ); ?>
		</div>
	    </div>
	    
	    <div class="row-fluid">
		<div class="span12">
		    <div class="portlet box blue ">
			<div class="portlet-title">
			    <div class="caption"><i class="icon-user"></i>Benefisiariu sira</div>
			    <div class="tools"><a href="javascript:;" class="collapse"></a></div>
			    <div class="actions">
				<button type="button" id="btn-add-beneficiary" class="btn mini yellow" onclick="Fefop.DRHTrainingPlan.addBeneficiary( event );"> 
				     <i class="icon-plus-sign"></i>
				     Aumenta
				</button>
			    </div>
			</div>
			<div class="portlet-body form">
			    <table class="table table-striped table-bordered table-hover table-full-width" id="beneficiary-list">
				<thead>
				    <tr>
					<th>Naran</th>
					<th>Sentru Formasaun</th>			
					<th>Seksu</th>			
					<th>Defisiensia</th>	
					<th>Valór atu selu ba sentru formasaun</th>			
					<th>Kustu Unitariu Total</th>	
					<th style="width: 8%">Asaun</th>
				    </tr>
				</thead>
				<tbody>
				    <?php 
					if ( !empty( $this->beneficiaries ) ) :
					    foreach ( $this->beneficiaries as $beneficiary ) :
						echo $this->action( 'add-staff', 'drh-training-plan', 'fefop', array( 'row' => $beneficiary ) );
					    endforeach;
					endif;
				    ?>
				</tbody>
			    </table>
			</div>
		    </div>
		</div>
	    </div>
	    
	     <div class="row-fluid">
		<div class="span12">
		    <div class="portlet box red">
			<div class="portlet-title">
			    <div class="caption"><i class="icon-dollar"></i>Orsamentu</div>
			    <div class="tools"><a href="javascript:;" class="collapse"></a></div>
			    <div class="actions">
				<button type="button" id="btn-add-expense" class="btn mini yellow" onclick="Fefop.DRHTrainingPlan.searchExpense( event );"> 
				     <i class="icon-plus-sign"></i>
				     Aumenta
				</button>
			    </div>
			</div>
			<div class="portlet-body form">
			    <table class="table table-striped table-bordered table-hover table-full-width" id="expense-list">
				<thead>
				    <tr>
					<th>Depeza</th>
					<th>Valór ho USD</th>
					<th style="width: 15%">Asaun</th>
				    </tr>
				</thead>
				<tbody>
				    <?php 
					if ( !empty( $this->expenses ) ) :
					    foreach ( $this->expenses as $expense ) :
						echo $this->action( 'add-expense', 'drh-training-plan', 'fefop', array( 'row' => $expense ) );
					    endforeach;
					endif;
				    ?>
				</tbody>
				<tfoot>
				    <tr>
					<td>TOTÁL</td>
					<td>
					    <?php echo $this->form->getElement( 'amount_expenses' ); ?>
					</td>
					<td></td>
				    </tr>
				</tfoot>
			    </table>
			</div>
		    </div>
		</div>
	    </div>
	    
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>