<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo Fefop_Model_Mapper_DRHTrainingPlan::buildNum( $row->id_drh_trainingplan ); ?></td>
	<td><?php echo $row->entity; ?></td>
	<!--<td><?php echo $row->scholarity_area; ?></td>
	<td><?php echo $row->ocupation_name_timor; ?></td>-->
	<td><?php echo $row->country; ?></td>
	<td><?php echo $this->date( $row->date_start ); ?></td>
	<td><?php echo $this->date( $row->date_finish ); ?></td>
	<td><?php echo $this->currency( $row->amount ); ?></td>
	<td>
	    <?php if ( empty( $this->listAjax ) ) : ?>
		<?php if ( $this->access( Fefop_Form_DRHTrainingPlan::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
		    <a class="btn green" href="<?php echo $this->baseUrl( 'fefop/drh-training-plan/edit/id/' . $row->id_drh_trainingplan ); ?>">
			<i class="icon-edit"></i>            
		    </a>
		<?php else : ?>
		    <a class="btn red" href="javascript:;">
			<i class="icon-alert icon-lock"></i>                                 
		    </a>
		<?php endif; ?>
	    <?php else : ?>
		<a class="btn red action-ajax" href="javascript:;" data-id="<?php echo $row->id_drh_trainingplan; ?>">
		    <i class="icon-ok"></i>                                     
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>