<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_fefop_contract' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span12">
		    <?php echo $this->form->getElement( 'fk_id_fefop_status' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span12">
		    <?php echo $this->form->getElement( 'description' ); ?>
		    <div class="progress progress-striped active" id="progress-content">
			<div class="bar"></div>
		    </div>
		</div>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>