<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_sysuser' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="span6"><?php echo $this->form->getElement( 'name' ); ?></div>
	    <div class="span6"><?php echo $this->form->getElement( 'login' ); ?></div>
	</div>
	<div class="row-fluid">
	    <div class="span6"><?php echo $this->form->getElement( 'password' ); ?></div>
	    <div class="span6"><?php echo $this->form->getElement( 'confirm_password' ); ?></div>
	</div>
	<div class="row-fluid">
	    <div class="span6"><?php echo $this->form->getElement( 'fk_id_dec' ); ?></div>
	    <div class="span6"><?php echo $this->form->getElement( 'active' ); ?></div>
	</div>
	
	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>