<div class="row-fluid">
    <div class="span4">
	<div class="control-group">
	    <label class="control-label">Naran Klase:</label>
	    <div class="controls">
		<span class="text bold">
		    <?php echo $this->class->class_name; ?>
		</span>
	    </div>
	</div>
    </div>
    <div class="span4">
	<div class="control-group">
	    <label class="control-label">Instituisaun Ensinu:</label>
	    <div class="controls">
		<span class="text bold">
		    <?php echo $this->class->institution; ?>
		</span>
	    </div>
	</div>
    </div>
    <div class="span2">
	<div class="control-group">
	    <label class="control-label">Kursu:</label>
	    <div class="controls">
		<span class="text bold">
		    <?php echo ( empty( $this->class->external_code ) ? '' : $this->class->external_code  . ' - ' ) . $this->class->scholarity; ?>
		</span>
	    </div>
	</div>
    </div>
</div>
<div class="form-actions">
    <button class="btn red" <?php echo $this->caseActiveGroup()->hasAccessEdit() ? '' : 'disabled'; ?>
	    type="button" onclick="Client.CaseGroup.clientsToClass( this )" >Karuka lista kandidatu <i class="m-icon-swapright m-icon-white"></i></button>
</div>
<div class="row-fluid">
    <table class="table table-striped table-bordered table-hover table-full-width" id="client-class-list">
	<thead>
	    <tr>
		<th style="width: 5%" class="no-sort">
		    <input type="checkbox" onClick="General.checkAll( this );" />
		</th>
		<th style="width: 18%">Numeru</th>
		<th style="width: 40%">Kliente</th>
		<th class="hidden-phone hidden-tablet">Data Moris</th>
		<th class="hidden-phone hidden-tablet">Idade</th>
		<th>Seksu</th>
		<th>CEOP</th>
	    </tr>
	</thead>
	<tbody></tbody>
    </table>
</div>