<div class="box-content">

    <div class="row-fluid">
	<div class="span12">
	    <div class="portlet box grey">
		<div class="portlet-title">
		    <div class="caption"><i class="icon-search"></i> Buka Kliente</div>
		    <div class="tools"><a class="collapse" href="javascript:;"></a></div>
		</div>
		<div class="portlet-body form">
		    <?php
			$this->headScript()->appendFile( $this->baseUrl( 'public/scripts/controller/client/case.js' ) );
			$this->placeholder( 'form' )->captureStart();
		    ?>
		    <div class="row-fluid">
			<div class="span6">
			    <?php echo $this->searchClient->getElement( 'fk_id_dec' ); ?>
			</div>
			<div class="span6">
			    <div class="control-group">
				<label class="control-label" for="fk_id_dec">Numeru Rejistu</label>
				<div class="controls">
				    <?php
					echo $this->searchClient->getElement( 'num_district' );
					echo $this->searchClient->getElement( 'num_subdistrict' );
					echo $this->searchClient->getElement( 'num_servicecode' );
					echo $this->searchClient->getElement( 'num_year' );
					echo $this->searchClient->getElement( 'num_sequence' );
				    ?>
				</div>
			    </div>
			</div>
		    </div>
		    <div class="row-fluid">
			<div class="span6">
			    <?php echo $this->searchClient->getElement( 'first_name' ); ?>
			</div>
			<div class="span6">
			    <?php echo $this->searchClient->getElement( 'last_name' ); ?>
			</div>
		    </div>
		    <div class="row-fluid">
			<div class="span3">
			    <?php echo $this->searchClient->getElement( 'active' ); ?>
			</div>
			<div class="span3">
			    <?php echo $this->searchClient->getElement( 'hired' ); ?>
			</div>
			<div class="span6">
			    <?php echo $this->form->getElement( 'fk_id_profocupationtimor' ); ?>
			</div>
		    </div>

		    <div class="row-fluid">
			<div class="form-actions">
			    <button class="btn blue">Buka <i class="icon-search m-icon-white"></i></button>
			    <button class="btn green" type="reset" id="clear">Hamoos <i class="icon-trash m-icon-white"></i></button>
			    <button class="btn red" <?php echo !$this->caseActiveGroup()->hasAccessEdit() ? 'disabled' : ''; ?> type="button" onclick="Client.CaseGroup.addClients( this )" >Add kliente <i class="icon-plus-sign m-icon-white"></i></button>
			</div>
		    </div>
		    <?php
			$this->placeholder( 'form' )->captureEnd();
			echo $this->form( $this->searchClient->getId(), $this->searchClient->getAttribs(), $this->placeholder( 'form' ) );
		    ?>
		</div>
	    </div>
	</div>
    </div>

    <div class="row-fluid">
	<div class="span12">
	    <div class="portlet box grey">
		<div class="portlet-title">
		    <div class="caption"><i class="icon-list"></i> Resultado Buka</div>
		    <div class="tools"><a class="collapse" href="javascript:;"></a></div>
		</div>
		<div class="portlet-body form">
		    <table class="table table-striped table-bordered table-hover table-full-width" id="client-list">
			<thead>
			    <tr>
				<th style="width: 5%" class="no-sort">
				    <input type="checkbox" onClick="General.checkAll( this );" />
				</th>
				<th style="width: 18%">Numeru</th>
				<th style="width: 40%">Kliente</th>
				<th class="hidden-phone hidden-tablet">Data Moris</th>
				<th class="hidden-phone hidden-tablet">Idade</th>
				<th>Seksu</th>
				<th>CEOP</th>
			    </tr>
			</thead>
			<tbody></tbody>
		    </table>
		</div>
	    </div>
	</div>
    </div>
    
    <div class="row-fluid">
	<div class="span12">
	    <div class="portlet box light-grey">
		<div class="portlet-title">
		    <div class="caption"><i class="icon-list"></i> Kliente sira iha Grupu</div>
		    <div class="tools"><a class="collapse" href="javascript:;"></a></div>
		</div>
		<div class="portlet-body form">
		    <table class="table table-striped table-bordered table-hover table-full-width" id="client-group-list">
			<thead>
			    <tr>
				<th>Action</th>
				<th style="width: 18%">Numeru</th>
				<th style="width: 40%">Kliente</th>
				<th class="hidden-phone hidden-tablet">Data Moris</th>
				<th class="hidden-phone hidden-tablet">Idade</th>
				<th>Seksu</th>
				<th style="width: 10%">Status</th>
			    </tr>
			</thead>
			<tbody></tbody>
		    </table>
		</div>
	    </div>
	</div>
    </div>
</div>