<div class="box-content">
     <div class="row-fluid">
	<div class="span12 text-center margin-bottom-20">
	    <button type="button" id="button-finish"
		    onClick="Client.CaseGroup.finishCase();"
		    class="btn green <?php echo $this->caseActiveGroup()->hasAccessEdit() ? '' : 'disabled'; ?>">
		<i class="icon-lock m-icon-white"></i>
		    Taka Kazu
	    </button>
	</div>
    </div>
    <div class="row-fluid">
	<table class="table table-striped table-bordered table-hover table-full-width" id="finish-list">
	    <thead>
		<tr>
		    <th style="width: 10%">#</th>
		    <th>Kriterio Sira</th>
		    <th style="width: 10%">Status</th>
		</tr>
	    </thead>
	    <tbody>
		
	    </tbody>
	</table>
    </div>
</div>