<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_action_plan_group' );
    echo $this->form->getElement( 'step' );
    echo $this->form->getElement( 'fk_id_perdata' );
 ?>
    <div class="row-fluid">
	<div class="span6">
	    <?php echo $this->form->getElement( 'fk_id_counselor' ); ?>
	</div>
	<div class="span6">
	    <?php echo $this->form->getElement( 'name' ); ?>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span6">
	    <?php echo $this->form->getElement( 'fk_id_addcountry' ); ?>
	</div>
	<div class="span6">
	    <?php echo $this->form->getElement( 'fk_id_fefpeduinstitution' ); ?>
	</div>
    </div>

    <?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>

<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>