<div class="row-fluid">
    <div class="span6">
	<div class="control-group">
	    <label class="control-label">Titulu Vaga Empregu:</label>
	    <div class="controls">
		<span class="text bold">
		    <?php echo $this->vacancy->vacancy_titule; ?>
		</span>
	    </div>
	</div>
    </div>
    <div class="span4">
	<div class="control-group">
	    <label class="control-label">Empreza:</label>
	    <div class="controls">
		<span class="text bold">
		    <?php echo $this->vacancy->enterprise_name; ?>
		</span>
	    </div>
	</div>
    </div>
    <div class="span2">
	<div class="control-group">
	    <label class="control-label">Kodigu:</label>
	    <div class="controls">
		<span class="text bold">
		    <?php echo str_pad( $this->vacancy->id_jobvacancy, 5, 0, STR_PAD_LEFT ); ?>
		</span>
	    </div>
	</div>
    </div>
</div>
<div class="row-fluid">
    <div class="span3">
	<div class="control-group">
	    <label class="control-label">Okupasaun:</label>
	    <div class="controls">
		<span class="text bold">
		    <?php echo $this->vacancy->ocupation_name_timor; ?>
		</span>
	    </div>
	</div>
    </div>
    <div class="span3">
	<div class="control-group">
	    <label class="control-label">CEOP:</label>
	    <div class="controls">
		<span class="text bold">
		    <?php echo $this->vacancy->name_dec; ?>
		</span>
	    </div>
	</div>
    </div>
    <div class="span4">
	<div class="control-group">
	    <label class="control-label">Data Loke:</label>
	    <div class="controls">
		<span class="text bold">
		    <?php echo $this->vacancy->open_date_formated; ?>
		</span>
	    </div>
	</div>
    </div>
    <div class="span2">
	<div class="control-group">
	    <label class="control-label">Data Taka:</label>
	    <div class="controls">
		<span class="text bold">
		    <?php echo $this->vacancy->close_date_formated; ?>
		</span>
	    </div>
	</div>
    </div>
</div>
<div class="form-actions">
    <button class="btn red" <?php echo $this->caseActiveGroup()->hasAccessEdit() ? '' : 'disabled'; ?>
	    type="button" onclick="Client.CaseGroup.clientsToVacancy( this )" >Karuka lista kandidatu <i class="m-icon-swapright m-icon-white"></i></button>
</div>
<div class="row-fluid">
    <table class="table table-striped table-bordered table-hover table-full-width" id="client-vacancy-list">
	<thead>
	    <tr>
		<th style="width: 5%" class="no-sort">
		    <input type="checkbox" onClick="General.checkAll( this );" />
		</th>
		<th style="width: 18%">Numeru</th>
		<th style="width: 40%">Kliente</th>
		<th class="hidden-phone hidden-tablet">Data Moris</th>
		<th class="hidden-phone hidden-tablet">Idade</th>
		<th>Seksu</th>
		<th>CEOP</th>
	    </tr>
	</thead>
	<tbody></tbody>
    </table>
</div>