<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td>
	    <div class="btn-group" style="margin: 0px !important;">
		<a class="btn yellow" href="javascript:;" data-toggle="dropdown">
		    <i class="icon-bolt"></i> Asaun
		    <i class="icon-angle-down"></i>
		</a>
		<ul class="dropdown-menu">
		    <li>
			<a href="<?php echo $this->baseUrl( '/client/client/evidence/id/' . $row->id_perdata ); ?>" target="_blank">
			    <i class="icon-credit-card"></i> 
			    Kartaun Evidensia
			</a>
		    </li>
		    <li>
			<a href="javascript:;" onClick="Client.Case.caseNote( <?php echo $row->id_action_plan; ?>);">
			    <i class="icon-edit"></i> 
			    Nota Kazu
			</a>
		    </li>
		    <li>
			<a href="javascript:;" onClick="Client.Case.appointment( <?php echo $row->id_action_plan; ?>);">
			    <i class="icon-group"></i> 
			    Audiensia
			</a>
		    </li>
		    <li>
			<a href="javascript:;" onClick="Client.CaseGroup.documentsCase( <?php echo $row->id_action_plan; ?>, <?php echo $row->id_perdata ?>  );">
			    <i class="icon-folder-open"></i> 
			    Dokumentu
			</a>
		    </li>
		</ul>
	    </div>
	</td>
	<td><?php echo Client_Model_Mapper_Client::buildNumRow( $row ); ?></td>
	<td>
	    <?php if ( $this->access( Client_Form_ClientInformation::ID) ) : ?>
		<a href="<?php echo $this->baseUrl( '/client/client/print/id/' . $row->id_perdata ); ?>" target="_blank">
		    <?php echo Client_Model_Mapper_Client::buildName( $row ); ?>
		</a>
	    <?php else : ?>
		    <?php echo Client_Model_Mapper_Client::buildName( $row ); ?>
	    <?php endif; ?>
	</td>
	<td class="hidden-phone hidden-tablet"><?php echo $row->birth_date_format; ?></td>
	<td class="hidden-phone hidden-tablet"><?php echo $row->age; ?></td>
	<td><?php echo $row->gender; ?></td>
	<td style="width: 10%" class="hidden-phone hidden-tablet">
	    <?php 
		if ( $row->status_case == 1 ) {
		  
		    $label = 'success';
		    $status = 'Loke';  
		    
		} else {
		    
		    $label = ( $row->status_case == 2 ) ? 'warning' : 'important';
		    $status = ( $row->status_case == 2 ) ? 'Kansela' : 'Taka';	
		}
	    ?>
	    
	    <span class="label label-<?php echo $label; ?>">
		<?php echo $status; ?>
	    </span>
	</td>
    </tr>
<?php endforeach; ?>