<div class="form-actions no-print">
    <button type="button" class="btn blue" onClick="self.print();"><i class="icon-print"></i> Print</button>
    <button type="button" class="btn red" onClick="self.close();"><i class="icon-remove-sign"></i> Taka</button>
</div>

<?php echo $this->action( 'header-report', 'index', 'default', array( 'id' => $this->fk_id_dec ) ); ?>

<h3 class="text-center">
    JESTAUN KAZU GRUPU
</h3>

<div class="form-view">
	<h4 class="form-section bold">
	    DADUS KAZU GRUPU
	</h4>
    
	<div class="row-fluid">
	    <div class="span4">
		<div class="control-group">
		    <label class="control-label bold">Naran Grupu:</label>
		    <div class="controls">
			<span class="text">
			    <?php echo $this->case->name; ?>
			</span>
		    </div>
		</div>
	    </div>
	    <div class="span4">
		<div class="control-group">
		    <label class="control-label bold">Konselleru:</label>
		    <div class="controls">
			<span class="text">
			    <?php echo $this->case->name; ?>
			</span>
		    </div>
		</div>
	    </div>
	    <div class="span4">
		<div class="control-group">
		    <label class="control-label bold">
			<?php echo !empty( $this->case->institution ) ? 'Instituisaun Ensinu' : 'Nasaun'; ?>:
		    </label>
		    <div class="controls">
			<span class="text">
			    <?php echo empty( $this->case->institution ) ? $this->case->country : $this->case->institution; ?>
			</span>
		    </div>
		</div>
	    </div>
	</div>
    
	<div class="row-fluid margin-bottom-25"></div>	
    
	<h4 class="form-section bold margin-bottom-15">
	    PLANU ASAUN
	</h4>
    
	<div class="row-fluid">
	    <div class="span12">
		<table class="table table-striped table-bordered table-hover table-full-width">
		    <thead>
			<tr>
			    <th>Tipu Barreira</th>
			    <th>Barreira</th>
			    <th>Intervensaun</th>
			    <th>Se mak halo</th>
			</tr>
		    </thead>
		    <tbody>
			<?php foreach ( $this->barriers as $barrier ) : ?>
			    <tr>
				<td><?php echo $barrier->barrier_type_name; ?></td>
				<td><?php echo $barrier->barrier_name; ?></td>
				<td><?php echo $barrier->barrier_Intervention_name; ?></td>
				<td><?php echo $barrier->user; ?></td>
			    </tr>
			<?php endforeach; ?>
		    </tbody>
		</table>
	    </div>
	</div>
	
	<div class="row-fluid margin-bottom-25"></div>	
    
	<h4 class="form-section bold margin-bottom-15">
	    KLIENTE HOTU
	</h4>
	
	<div class="row-fluid">
	    <div class="span12">
		<table class="table table-striped table-bordered table-hover table-full-width">
		    <thead>
			<tr>
			    <th>Numeru</th>
			    <th>Naran</th>
			    <th>Data Moris</th>
			    <th>Idade</th>
			    <th>Seksu</th>
			    <th>Status</th>
			</tr>
		    </thead>
		    <tbody>
			<?php foreach ( $this->clients as $client ) : ?>
			    <tr>
				<td><?php echo Client_Model_Mapper_Client::buildNumRow( $client ); ?></td>
				<td><?php echo Client_Model_Mapper_Client::buildName( $client ); ?></td>
				<td><?php echo $client->birth_date_format; ?></td>
				<td><?php echo $client->age; ?></td>
				<td><?php echo $client->gender; ?></td>
				<td>
				    <?php 
					if ( $client->status_case == 1 ) {

					    $label = 'success';
					    $status = 'Loke';  

					} else {

					    $label = ( $client->status_case == 2 ) ? 'warning' : 'important';
					    $status = ( $client->status_case == 2 ) ? 'Kansela' : 'Taka';	
					}
				    ?>

				    <span class="label label-<?php echo $label; ?>">
					<?php echo $status; ?>
				    </span>
				</td>
			    </tr>
			<?php endforeach; ?>
		    </tbody>
		</table>
	    </div>
	</div>
</div>



<div class="row-fluid margin-bottom-25"></div>
<div class="row-fluid">
    <div class="span12 text-right">
	<small><em>SECRETARIA DE ESTADO PARA POLÍTICA DA FORMAÇÃO PROFISSIONAL E EMPREGO</em></small>
    </div>
</div>

 <div class="row-fluid">
    <div class="span4 offset8 text-center">
        <div class="row-fluid">
            <?php
                $auth = Zend_Auth::getInstance()->getIdentity();
                echo $auth->name_dec . ' - ' . Zend_Date::now()->toString( 'dd/MM/yyyy' );
            ?>
        </div>
        <div class="row-fluid">Tekniknu Profisional Empregu</div>
        <div class="row-fluid">
            <br />
        </div>
        <div class="row-fluid">
            <?php echo $auth->name; ?>
        </div>
    </div>
</div>