<?php $this->headScript()->appendFile( $this->baseUrl( 'public/scripts/controller/fefop/contract.js' ) );  ?>
<div class="row-fluid">
    <div class="span12">
	<div class="portlet box green ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-search"></i>Buka</div>
		<div class="tools"><a href="javascript:;" class="expand"></a></div>
	    </div>
	    <div class="portlet-body form hide">
		<?php 
		    $this->placeholder( 'form' )->captureStart();
		    echo $this->formSearch->getElement( 'minimum_amount' );
		    echo $this->formSearch->getElement( 'maximum_amount' );
		    echo $this->formSearch->getElement( 'fk_id_fefpenterprise' );
		    echo $this->formSearch->getElement( 'fk_id_fefop_contract' );
		?>

		    <div class="box-content">
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->formSearch->getElement( 'fk_id_fefop_type_transaction' ); ?>
			    </div>
			    <div class="span6">
				<?php echo $this->formSearch->getElement( 'id_fefop_transaction_status' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->formSearch->getElement( 'fk_id_budget_category_type' ); ?>
			    </div>
			    <div class="span6">
				<?php echo $this->formSearch->getElement( 'fk_id_budget_category' ); ?>
			    </div>
			</div>
                        <div class="row-fluid">
                            <div class="span6">
                                <?php echo $this->formSearch->getElement( 'date_start' ); ?>
                            </div>
                            <div class="span6">
                                <?php echo $this->formSearch->getElement( 'date_finish' ); ?>
                            </div>
                        </div>
			 <div class="row-fluid">
			    <div class="span5">
				<?php echo $this->formSearch->getElement( 'enterprise' ); ?>
			    </div>
			    <div class="span1">
				<div class="control-group">
				    <label class="control-label">&#160;</label>
				    <div class="controls">
					<button type="button" id="btn-search-enterprise"
						class="btn green" title="Buka Empreza" onclick="Fefop.Financial.searchEnterprise( this )">
					     <i class="icon-search"></i>  
					 </button>
				    </div>
				</div>
			    </div>
			    <div class="span6">
				<?php echo $this->formSearch->getElement( 'identifier' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span5">
				<?php echo $this->formSearch->getElement( 'name_contract' ); ?>
			    </div>
			    <div class="span1">
				<div class="control-group">
				    <label class="control-label">&#160;</label>
				    <div class="controls">
					<button type="button" id="btn-search-contract"
						class="btn green" title="Buka Kontratu" onclick="Fefop.Financial.searchListContract( this )">
					     <i class="icon-search"></i>  
					 </button>
				    </div>
				</div>
			    </div>
			    <div class="span6">
				<?php echo $this->formSearch->getElement( 'num_contract' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			     <div class="span12">
				<div class="control-group">
				    <label class="control-label optional margin-bottom-10-">Kustu total</label>
				    <div class="controls">
					<div id="slider-amount" class="slider bg-blue"></div>
					<div class="slider-value">
					    Kustu:
					    <span id="slider-age-amount">
						<?php echo $this->currency( 0 ) . ' - ' . $this->currency( 20000 ); ?>
					    </span>
					</div>
				    </div>
				</div>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="form-actions">
				<button class="btn blue">Buka <i class="icon-search m-icon-white"></i></button>
				<button class="btn green" type="reset" id="clear">Hamoos <i class="icon-trash m-icon-white"></i></button>
				<button onclick="Fefop.Contract.printGrid( '#transaction-list' );" class="btn purple" type="button">Print <i class="icon-print m-icon-white"></i></button>
			    </div>
			</div>
		    </div>
		
		<?php
		    $this->placeholder( 'form' )->captureEnd();
		    echo $this->form( $this->formSearch->getId(), $this->formSearch->getAttribs(), $this->placeholder( 'form' ) );
		?>
	    </div>
	</div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box green ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-dollar"></i>Lansamentu Hotu-Hotu</div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="transaction-list">
		    <thead>
			<tr>
			    <th style="width: 8%" class="date-column">Data</th>
			    <th style="width: 5%">T/P</th>
			    <th style="width: 15%">Kontratu</th>
			    <th style="width: 14%">Komponente</th>
			    <th>Rúbrica</th>
			    <th style="width: 7%" class="no-sort">Kont.</th>
			    <th style="width: 13%">Valor</th>
			    <th class="no-sort" style="width: 7%">Asaun</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		    <tfoot>
			<tr>
			    <th colspan="6">Total</th>
			    <th class="text-right">
				<span class="bold pull-right"></span>
			    </th>
			    <th></th>
			</tr>
		    </tfoot>
		</table>
	    </div>
	</div>
    </div>
</div>