<?php foreach ( $this->rows as $row ) : ?>
    <tr class="<?php echo $row->id_fefop_transaction_status != Fefop_Model_Mapper_Financial::ACTIVE ? 'muted' : ''; ?>">
	<td style="width: 8%"><?php echo $this->date( $row->date_reference ); ?></td>
	<td style="width: 5%"><?php echo $row->code_transaction; ?></td>
	<td><?php echo Fefop_Model_Mapper_Contract::buildNumById( $row->fk_id_fefop_contract ); ?></td>
	<td style="width: 14%"><?php echo empty( $row->component ) ? 'N/A' : ucwords( strtolower( $row->component ) ); ?></td>
	<td><?php echo ucwords( strtolower( $row->expense ) ); ?></td>
	<td style="width: 7%">
	    <?php 
		$label = '<p>%s: <strong>%s</strong></p>';
		
		$infoContract = sprintf( $label, 'Kontratu', Fefop_Model_Mapper_Contract::buildNumById( $row->fk_id_fefop_contract ) );
		$infoContract .= sprintf( $label, 'Status', $row->status_description );
		
		if ( !empty( $row->fk_id_fefop_receipt ) ) {
		    
		    $infoContract .= sprintf( $label, 'Empreza', $row->enterprise_name );
		    $infoContract .= sprintf( $label, 'Identifikador Resibu', $row->identifier );
		}
		
		$infoContract .= sprintf( $label, 'Benefisiariu', $row->beneficiary );
	    ?>
	    
	    <a class="btn blue disabled popovers" 
		data-trigger="hover"
		data-container="body" 
		data-toggle="popover" 
		data-placement="top" 
		data-content='<?php echo $infoContract; ?>'
	       href="javascript:;">
		<i class="icon-info-sign"></i>
	    </a>
	</td>
	<td class="text-right" style="width: 13%">
	    <input type="hidden" class="total-transaction" value="<?php echo $row->amount * ( $row->operation == 'C' ? 1 : -1 ); ?>" />
	    <p class="pull-right bold text-<?php echo $row->operation == 'C' ? 'success' : 'error'; ?>">
		 <?php echo $this->currency( $row->amount * ( $row->operation == 'C' ? 1 : -1 ) ); ?>
	    </p>
	</td>
	<td style="width: 7%">
	    <?php if ( empty( $this->listAjax ) ) : ?>
		<?php 
		    if ( 
			  $this->access( Fefop_Form_Transaction::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) &&
			  $row->id_fefop_transaction_status == Fefop_Model_Mapper_Financial::ACTIVE
			) : 
			
			$onclick = 'Fefop.Financial.editTransaction(' . $row->id_fefop_transaction . ')' ;
			if ( !empty( $row->fk_id_fefop_receipt ) )
			    $onclick = 'Fefop.Financial.editReceipt(' . $row->fk_id_fefop_receipt . ')';
			
		?>
		    <button type="button" class="btn green" 
			    onClick="<?php echo $onclick; ?>">
			<i class="icon-edit"></i>
		    </button>
		<?php else : ?>
		    <a class="btn red" href="javascript:;">
			<i class="icon-alert icon-lock"></i>                                 
		    </a>
		<?php endif; ?>
	    <?php else : ?>
		<a class="btn red action-ajax" href="javascript:;" data-id="<?php echo $row->id_fefop_transaction; ?>">
		    <i class="icon-ok"></i>                                     
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>