<div id="container-contract" style="padding: 0 10px">
    <?php echo $this->action( 'contract', 'index', 'fefop', array( 'id' => $this->contract ) ); ?>
</div>
<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_fefop_transaction' );
    echo $this->form->getElement( 'fk_id_fefop_contract' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_fefop_type_transaction' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'date_reference' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_budget_category_type' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_budget_category' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'total_contract' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'amount' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span12">
		    <?php echo $this->form->getElement( 'description' ); ?>
		</div>
	    </div>	    
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>