<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_fefop_receipt' );
    echo $this->form->getElement( 'fk_id_fefpenterprise' );
 ?>

    <?php echo $this->fefopContract()->getMessages(); ?>

    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span11">
		    <?php echo $this->form->getElement( 'enterprise' ); ?>
		</div>
		<div class="span1">
		    <div class="control-group">
			<label class="control-label">&#160;</label>
			<div class="controls">
			    <button type="button" id="btn-search-enterprise" <?php echo empty( $this->receipt ) ? '' : 'disabled="disabled"'; ?>
				    class="btn green" title="Buka Empreza" onclick="Fefop.Financial.searchEnterprise( this )">
				 <i class="icon-search"></i>  
			     </button>
			</div>
		    </div>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'identifier' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'date_purchased' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span8">
		    <?php echo $this->form->getElement( 'description' ); ?>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'amount' ); ?>
		</div>
	    </div>
	    
	    <div class="row-fluid">
		<div class="span12">
		    <div class="portlet box green ">
			<div class="portlet-title">
			    <div class="caption"><i class="icon-dollar"></i>Kontratu</div>
			    <div class="actions">
				<a href="javascript:;" class="btn blue" onclick="Fefop.Financial.searchContractTransaction();"> 
				    <i class="icon-plus-sign"></i>
				    Aumenta
				</a>
			    </div>
			</div>
			<div class="portlet-body form">
			    <table class="table table-striped table-bordered table-hover table-full-width" id="contract-list">
				<thead>
				    <tr>
					<th style="width: 5%"></th>
					<th>Kontratu</th>
					<th style="width: 20% !important">Total</th>			
					<th style="width: 15%"></th>
				    </tr>
				</thead>
				<tbody>
				    <?php 
					if ( !empty( $this->contracts ) ) :
					    foreach ( $this->contracts as $contract ) :
						echo $this->action( 'add-contract', 'financial', 'fefop', array( 'row' => $contract ) );
						foreach ( $contract['expenses'] as $expense ) :
						    echo $this->action( 'add-expense', 'financial', 'fefop', array( 'row' => $expense ) );
						endforeach;
					    endforeach;
					endif;
				    ?>
				</tbody>
			    </table>
			</div>
		    </div>
		</div>
	    </div>
	    
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>