<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-search"></i>Buka Kontratu FEFOP</div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<?php 
		    $this->placeholder( 'form' )->captureStart(); 
		    echo $this->form->getElement( 'minimum_amount' );
		    echo $this->form->getElement( 'maximum_amount' );
		?>

		    <div class="box-content">
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_fefop_status' ); ?>
			    </div>
			    <div class="span6">
				<div class="control-group">
				    <label class="control-label optional margin-bottom-10-">Kustu total</label>
				    <div class="controls">
					<div id="slider-amount" class="slider bg-blue"></div>
					<div class="slider-value">
					    Kustu:
					    <span id="slider-age-amount">
						<?php echo $this->currency( 0 ) . ' - ' . $this->currency( 20000 ); ?>
					    </span>
					</div>
				    </div>
				</div>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span3">
				<?php echo $this->form->getElement( 'fk_id_fefop_programs' ); ?>
			    </div>
			    <div class="span2">
				<?php echo $this->form->getElement( 'fk_id_fefop_modules' ); ?>
			    </div>
			    <div class="span2">
				<?php echo $this->form->getElement( 'num_district' ); ?>
			    </div>
			    <div class="span2">
				<?php echo $this->form->getElement( 'num_year' ); ?>
			    </div>
			    <div class="span3">
				<?php echo $this->form->getElement( 'num_sequence' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="form-actions">
				<button class="btn blue">Buka <i class="icon-search m-icon-white"></i></button>
				<button class="btn green" type="reset" id="clear">Hamoos <i class="icon-trash m-icon-white"></i></button>
			    </div>
			</div>
		    </div>
		
		<?php
		    $this->placeholder( 'form' )->captureEnd();
		    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
		?>
	    </div>
	</div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Buka FEFOP</div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="contract-list">
		    <thead>
			<tr>
			    <th>Programa</th>
			    <th>Modulu</th>
			    <th>Kontratu</th>
			    <th>Data</th>
			    <th>Total</th>
			    <th>Status</th>
			    <th>Action</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>