<div class="row-fluid">
    <table class="table table-striped table-bordered table-hover table-full-width" id="transaction-contract-list">
	<thead>
	    <tr>
		<th style="width: 8%" class="date-column">Data</th>
		<th style="width: 5%">T/P</th>
		<th style="width: 15%">Kontratu</th>
		<th style="width: 14%">Komponente</th>
		<th>Rúbrica</th>
		<th style="width: 7%" class="no-sort">Kont.</th>
		<th style="width: 13%">Valor</th>
		<th class="no-sort" style="width: 7%">Asaun</th>
	    </tr>
	</thead>
	<tbody></tbody>
	<tfoot>
	    <tr>
		<th colspan="6">Total</th>
		<th class="text-right">
		    <span class="bold pull-right"></span>
		</th>
		<th></th>
	    </tr>
	</tfoot>
    </table>
</div>