<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_sysform' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="span6">
		<div class="row-fluid">
		    <?php echo $this->form->getElement( 'fk_id_sysmodule' ); ?>
		</div>
		<div class="row-fluid">
		    <?php echo $this->form->getElement( 'form' ); ?>
		</div>
		<div class="row-fluid">
		    <?php echo $this->form->getElement( 'description' ); ?>
		</div>
		<div class="row-fluid">
		    <?php echo $this->form->getElement( 'active' ); ?>
		</div>
	    </div>
	    <div class="span6">
		<div class="row-fluid">
		    <?php echo $this->form->getElement( 'operations' ); ?>
		</div>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>