<?php 
    $this->placeholder( 'form' )->captureStart();
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'start_date' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'finish_date' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_sysuser' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'description' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_sysmodule' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_sysform' ); ?>
		</div>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="form-actions">
		<button class="btn blue">Buka <i class="icon-search m-icon-white"></i></button>
	    </div>
	</div>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Buka Atividade</div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="audit-list">
		    <thead>
			<tr>
			    <th>Modulu</th>
			    <th>Formulariu</th>
			    <th>Deskrisaum</th>
			    <th>Data</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>