<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->module; ?></td>
	<td>
	    <?php if ( $this->access( Admin_Form_Module::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
		<a class="btn green" href="<?php echo $this->baseUrl( 'admin/module/edit/id/' . $row->id_sysmodule ); ?>">
		    <i class="icon-edit"></i>  
		    Troka                                            
		</a>
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>  
		    La bele acessu                                            
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>