<?php $this->placeholder( 'form' )->captureStart(); ?>
    <div class="row-fluid">
	<div class="row-fluid">
	    <div class="span6">
		<?php echo $this->form->getElement( 'id_fefop_programs' ); ?>
	    </div>
	    <div class="span6">
		<?php echo $this->form->getElement( 'fk_id_fefop_modules' ); ?>
	    </div>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span12">
	    <div class="portlet box blue">
		<div class="portlet-title">
		    <div class="caption"><i class="icon-reorder"></i>Rúbrica Sira</div>
		</div>
		<div class="portlet-body form">
		    <div class="row-fluid">
			<div class="span12">
			    <table class="table table-striped table-bordered table-hover table-full-width" id="expense-module-list">
				<thead>
				    <tr>
					<th class="no-sort"></th>
					<th style="width: 5%" class="no-sort">
					    <input type="checkbox" onClick="General.checkAll( this );" />
					</th>
					<th class="no-sort">Rúbrica Husi Modulu</th>
					<th class="no-sort">Komponente</th>
					<th class="no-sort">Folin</th>
				    </tr>
				</thead>
				<tbody></tbody>
			    </table>
			</div>
		    </div>
		    <div class="row-fluid">
			<div class="span12 text-center">
			    <hr />
			    <button class="btn green" type="button" onclick="Fefop.Expense.insertExpenseModule();">
				<i class="icon-circle-arrow-up"></i>
			    </button>
			    <button class="btn green" type="button" onclick="Fefop.Expense.removeExpenseModule();">
				<i class="icon-circle-arrow-down"></i>
			    </button>
			    <hr />
			</div>
		    </div>
		    <div class="row-fluid">
			<div class="span12">
			    <table class="table table-striped table-bordered table-hover table-full-width" id="expense-all-list">
				<thead>
				    <tr>
					<th class="no-sort"></th>
					<th style="width: 5%" class="no-sort">
					    <input type="checkbox" onClick="General.checkAll( this );" />
					</th>
					<th class="no-sort">Rúbrica Hotu-Hotu</th>
					<th class="no-sort">Komponente</th>
				    </tr>
				</thead>
				<tbody></tbody>
			    </table>
			</div>
		    </div>
		</div>
	    </div>
	</div>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );