<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_pce_contract' );
    echo $this->form->getElement( 'fk_id_fefop_contract' );
    echo $this->form->getElement( 'fk_id_perdata' );
    echo $this->form->getElement( 'fk_id_fefpstudentclass' );
 ?>

    <?php echo $this->fefopContract()->getMessages(); ?>

    <div class="box-content">
	<div class="row-fluid">
	     <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_fefop_modules' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_adddistrict' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span10">
		    <?php echo $this->form->getElement( 'beneficiary' ); ?>
		</div>
		<div class="span1">
		    <div class="control-group">
			<label class="control-label">&#160;</label>
			<div class="controls">
			    <button type="button" id="btn-search-client" class="btn green" title="Buka Kliente" onclick="Fefop.PceFaseContract.searchClient()">
				 <i class="icon-search"></i>  
			     </button>
			</div>
		    </div>
		</div>
		<div class="span1">
		    <div class="control-group">
			<label class="control-label">&#160;</label>
			<div class="controls">
			    <button type="button" id="btn-export-contract" disabled="disabled" 
				    class="btn green" title="Exporta Kontratu" onclick="Fefop.PceFaseContract.exportContract()">
				 <i class="icon-print"></i>  
			     </button>
			</div>
		    </div>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span10">
		    <?php echo $this->form->getElement( 'class_name' ); ?>
		</div>
		<div class="span2">
		    <div class="control-group">
			<label class="control-label">&#160;</label>
			<div class="controls">
			    <button type="button" id="btn-search-class" class="btn green" title="Buka Formasaun" onclick="Fefop.PceFaseContract.searchClass()">
				 <i class="icon-search"></i>  
			     </button>
			</div>
		    </div>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span4">
		    <?php echo $this->form->getElement( 'date_start' ); ?>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'date_finish' ); ?>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'duration' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_isicdivision' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_isicclasstimor' ); ?>
		</div>
	    </div>
	    
	    <div class="row-fluid">
		<div class="span12">
		    <div class="portlet box blue ">
			<div class="portlet-title">
			    <div class="caption"><i class="icon-dollar"></i>
				Rúbrika despeza kona-ba faze dahuluk Start-up Kit ne'ebé uza durante formasaun téknika espesífika
			    </div>
			    <div class="tools"><a href="javascript:;" class="collapse"></a></div>
			</div>
			<div class="portlet-body form">
			    <table class="table table-striped table-bordered table-hover table-full-width" id="expense-list">
				<thead>
				    <tr>
					<th style="width: 7%">#</th>
					<th>Rúbrika</th>			
					<th style="width: 15%">Folin Hira</th>
				    </tr>
				</thead>
				<tbody>
				    <?php 
					if ( !empty( $this->expenses ) ) :
					    $count = 'A';
					    foreach ( $this->expenses as $expense ) : 
				    ?>
					<tr>
					    <td><?php echo $count++; ?>.</td>
					    <td><?php echo str_replace( '&', ' ', $expense->description ); ?></td>
					    <td>
						<?php
						    $attribsText = array(
							'class'	    => 'm-wrap span12 focused cost-expense submit-field money-mask',
							'id'	    => 'total_expense_' . $expense->id_budget_category,
							'readonly'  => true
						    );

						    $amount = 0;
						    if ( !empty( $expense->amount ) )
							$amount = $expense->amount;

						    $amount = number_format( $amount, 2, '.', '.' );
						    
						    echo $this->formText( 'expense[cost_expense][' . $expense->id_budget_category . ']', $amount, $attribsText );  
						 ?>
					    </td>
					</tr>
				    <?php 
					    endforeach; 
					endif;
				    ?>
					
				</tbody>
				<tfoot>
				    <tr>
					<td colspan="2">TOTAL</td>
					<td>
					    <?php echo $this->form->getElement( 'amount' ); ?>
					</td>
				    </tr>
				</tfoot>
			    </table>
			</div>
		    </div>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span12">
		    <div class="portlet box grey ">
			<div class="portlet-title">
			    <div class="caption"><i class="icon-dollar"></i>Rúbrika Detalladu</div>
			</div>
			<div class="portlet-body form">
			     <?php 
				if ( !empty( $this->expenses ) ) :
				    $count = 'A';
				    foreach ( $this->expenses as $expense ) : 
			    ?>
				<div class="row-fluid">
				    <div class="span12">
					<div class="portlet box light-grey expense-portlet" id="expense-portlet-<?php echo $expense->id_budget_category; ?>" >
					    <input type="hidden" name="expense-detailed" class="expense-id" value="<?php echo $expense->id_budget_category; ?>" />
					    <div class="portlet-title">
						<div class="caption" style="font-size: 11px">
						    <strong><?php echo ( $count++ ) . ' - ' . str_replace( '&', ' ', $expense->description ); ?></strong>
						</div>
						<div class="tools"><a href="javascript:;" class="collapse"></a></div>
						<div class="actions">
						    <button type="button" id="btn-add-expense-detailed" class="btn mini green" onclick="Fefop.PceFaseContract.addDetailedExpense( event, this );"> 
							 <i class="icon-plus-sign"></i>
							 Aumenta
						    </button>
						</div>
					    </div>
					    <div class="portlet-body form">
						<table class="table table-striped table-bordered table-hover table-full-width" id="expense-detailed-list-<?php echo $expense->id_budget_category; ?>">
						    <thead>
							<tr>
							    <th>Item</th>
							    <th style="width: 10%">Qtd.</th>
							    <th style="width: 12%">Folin Ketak</th>			
							    <th style="width: 10%">Folin Total</th>
							    <th style="width: 5%"></th>
							</tr>
						    </thead>
						    <tbody>
							<?php 
							    if ( !empty( $this->itemsExpense ) && !empty( $this->itemsExpense[$expense->id_budget_category] ) ) {
								
								foreach ( $this->itemsExpense[$expense->id_budget_category] as $itemExpense )
								    echo $this->action( 'add-detailed-expense', 'pce-fase', 'fefop', array( 'expense' => $expense->id_budget_category, 'row' => $itemExpense ) );
							    }
							?>
						    </tbody>
						</table>
					    </div>
					</div>
				    </div>
				</div>
			    <?php 
				    endforeach; 
				endif;
			    ?>
			</div>
		    </div>
		</div>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>