<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_fp_contract' );
    echo $this->form->getElement( 'fk_id_annual_planning' );
    echo $this->form->getElement( 'fk_id_fefpeduinstitution' );
    echo $this->form->getElement( 'fk_id_planning_course' );
    echo $this->form->getElement( 'fk_id_fefop_contract' );
    echo $this->form->getElement( 'fk_id_unit_cost' );
    echo $this->form->getElement( 'fk_id_fefpstudentclass' );
    echo $this->form->getElement( 'fk_id_perscholarity' );
    echo $this->form->getElement( 'id_budget_category' );
 ?>

    <?php echo $this->fefopContract()->getMessages(); ?>

    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span4">
		    <?php echo $this->form->getElement( 'institute' ); ?>
		</div>
		<div class="span1">
		    <div class="control-group">
			<label class="control-label">&#160;</label>
			<div class="controls">
			    <button type="button" id="btn-search-planning" class="btn green" title="Buka Planeamentu" onclick="Fefop.FPContract.searchAnnualPlanning()">
				 <i class="icon-search"></i>  
			     </button>
			</div>
		    </div>
		</div>
		<div class="span1">
		    <div class="control-group">
			<label class="control-label">&#160;</label>
			<div class="controls">
			    <button type="button" id="btn-export-contract" disabled="disabled" 
				    class="btn green" title="Exporta Kontratu" onclick="Fefop.FPContract.exportContract()">
				 <i class="icon-print"></i>  
			     </button>
			</div>
		    </div>
		</div>
		<div class="span5">
		    <?php echo $this->form->getElement( 'class_name' ); ?>
		</div>
		<div class="span1">
		    <div class="control-group">
			<label class="control-label">&#160;</label>
			<div class="controls">
			    <button type="button" id="btn-search-class" disabled="disabled" class="btn green" title="Buka Klase Formasaun" onclick="Fefop.FPContract.searchClass()">
				 <i class="icon-search"></i>  
			    </button>
			</div>
		    </div>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'scholarity' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_adddistrict' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'start_date' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'finish_date' ); ?>
		</div>
	    </div>
	    <h4 class="form-section bold">
		Dadus Planeamentu
	    </h4>
	    <div class="row-fluid" id="planning-course-detail">
		<?php 
		    if ( !empty( $this->id_planning_course ) )
			echo $this->action( 'detail-planning', 'fp-contract', 'fefop', array( 'id' => $this->id_planning_course ) );
		?>
	    </div>
	    <h4 class="form-section bold">
		Finansiamentu
	    </h4>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'unit_cost' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'amount' ); ?>
		</div>
	    </div>
	    
	    <div class="row-fluid">
		<div class="span12">
		    <div class="portlet box blue ">
			<div class="portlet-title">
			    <div class="caption"><i class="icon-user"></i>Benefisiariu</div>
			    <div class="tools"><a href="javascript:;" class="collapse"></a></div>
			</div>
			<div class="portlet-body form">
			    <table class="table table-striped table-bordered table-hover table-full-width" id="client-list">
				<thead>
				    <tr>
					<th style="width: 15%">Numeru</th>
					<th style="width: 35%">Kliente</th>			
					<th style="width: 10%">Seksu</th>			
					<th style="width: 15%">Eleitoral</th>			
					<th style="width: 10%">Defisiensia</th>
					<th style="width: 15%" class="no-sort">Kustu Unitariu</th>
				    </tr>
				</thead>
				<tbody></tbody>
			    </table>
			</div>
		    </div>
		</div>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>