<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->institution; ?></td>
	<td><?php echo ( empty( $row->external_code ) ? '' : $row->external_code . ' - ' ) . $row->scholarity; ?></td>
	<td><?php echo $row->year_planning; ?></td>
	<td><?php echo $this->date( $row->date_start ); ?></td>
	<td><?php echo $this->date( $row->date_finish ); ?></td>
	<td>
	    <a class="btn red action-ajax" href="javascript:;" data-id="<?php echo $row->id_planning_course; ?>">
		<i class="icon-ok"></i>                                     
	    </a>
	</td>
    </tr>
<?php endforeach; ?>