<?php $this->placeholder( 'form' )->captureStart(); ?>

	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'category' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_perscholarity' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span4">
		    <?php echo $this->form->getElement( 'cost' ); ?>
		</div>
		<div class="span8">
		    <?php echo $this->form->getElement( 'comment' ); ?>
		</div>
	    </div>
	</div>

    <?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );