<div class="filters">
    <p><?php echo $this->filterReport($this->data['filters']); ?></p>
</div>

<?php if(!empty($this->data['item'])): ?>
    <?php foreach($this->data['item']['ceop'] as $id_dec => $name_dec): ?>
        <table class="relatorio">
            <thead>
                <tr>
                    <th colspan="6"><?php echo $name_dec; ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->data['item']['konselleiru'][$id_dec] as $id_counselor => $konselleiru): ?>
                    <tr>
                        <td colspan="6"><?php echo $konselleiru; ?></td>
                    </tr>
                    <tr>
                        <th>Naran Kliente</th>
                        <th>Kartaun Evidensia</th>
                        <th>Statuto</th>
                        <th>Intervensaun Identifika</th>
                        <th>Intervensaun Kompletu</th>
                        <th>Intervensaun Mati</th>
                    </tr>
                    <?php foreach($this->data['item']['data'][$id_dec][$id_counselor] as $data): ?>
                        <tr>
                            <td><?php echo $data['naran_kliente']; ?></td>
                            <td><?php echo $data['kartaun_evidensia']; ?></td>
                            <td><?php echo $data['statuto']; ?></td>
                            <td><?php echo $data['intervensaun_identifika']; ?></td>
                            <td><?php echo $data['intervensaun_kompletu']; ?></td>
                            <td><?php echo $data['intervensaun_mati']; ?></td>
                        </tr>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="3"></th>
                    <th><?php echo $this->data['item']['count'][$id_dec]['intervensaun_identifika']; ?></th>
                    <th><?php echo $this->data['item']['count'][$id_dec]['intervensaun_kompletu']; ?></th>
                    <th><?php echo $this->data['item']['count'][$id_dec]['intervensaun_mati']; ?></th>
                </tr>
            </tfoot>
        </table>
    <?php endforeach; ?>
<?php endif; ?>