<div class="filters">
    <p><?php echo $this->filterReport( $this->data['filters'] ); ?></p>
</div>

<table class="relatorio">
    <thead>
	<tr>
	    <th>Naran</th>
	    <th>Login</th>
	    <th>CEOP</th>
	    <th>Status</th>
	</tr>
    </thead>
    <tbody>
	<?php foreach ( $this->data['rows'] as $user ) : ?>
	    <tr class="<?php echo $this->cycle( array( 'one', 'two') )->next(); ?>">
		<td><?php echo $user->name; ?></td>
		<td><?php echo $user->login; ?></td>
		<td><?php echo $user->name_dec; ?></td>
		<td><?php echo $user->active ? 'Ativu' : 'Inativu'; ?></td>
	    </tr>
	<?php endforeach; ?>
    </tbody>
    <tfoot>
	<tr>
	    <th colspan="3">Total</th>
	    <th><?php echo count( $this->data['rows'] ); ?></th>
	</tr>
    </tfoot>
</table>