<div class="row-fluid">
    <div class="span6">
	<!-- BEGIN Portlet PORTLET-->
	<div class="portlet box blue">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-bar-chart"></i>Kliente tuir CEOP</div>
		<div class="tools">
		    <a href="javascript:;" class="collapse"></a>
		</div>
	    </div>
	    <div class="portlet-body">
		<div id="graph-client-ceop" class="graph-container"></div>
	    </div>
	</div>
	<!-- END Portlet PORTLET-->
    </div>
    <div class="span6">
	<!-- BEGIN Portlet PORTLET-->
	<div class="portlet box purple">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-bar-chart"></i>Vagas tuir Okupasaun</div>
		<div class="tools">
		    <a href="javascript:;" class="collapse"></a>
		</div>
	    </div>
	    <div class="portlet-body">
		<div id="graph-vacancy-occupation" class="graph-container"></div>
	    </div>
	</div>
	<!-- END Portlet PORTLET-->
    </div>
</div>
<div class="row-fluid">
    <div class="span6">
	<!-- BEGIN Portlet PORTLET-->
	<div class="portlet box red">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-bar-chart"></i>Graduados tuir Kursu</div>
		<div class="tools">
		    <a href="javascript:;" class="collapse"></a>
		</div>
	    </div>
	    <div class="portlet-body">
		<div id="graph-graduated-course" class="graph-container"></div>
	    </div>
	</div>
	<!-- END Portlet PORTLET-->
    </div>
    <div class="span6">
	<!-- BEGIN Portlet PORTLET-->
	<div class="portlet box yellow">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-bar-chart"></i>Vagas tuir CEOP</div>
		<div class="tools">
		    <a href="javascript:;" class="collapse"></a>
		</div>
	    </div>
	    <div class="portlet-body">
		<div id="graph-vacancy-ceop" class="graph-container"></div>
	    </div>
	</div>
	<!-- END Portlet PORTLET-->
    </div>
</div>