<!-- 
<div id="dashboard" class="custom-dashboard">
    
    BEGIN DASHBOARD STATS
    <div class="row-fluid">
	<div class="span4 responsive" data-tablet="span4" data-desktop="span4">
	    <a href="<?php echo $this->baseUrl( 'admin' ); ?>">
		<div class="dashboard-stat blue">
		    <div class="visual">
			<i class="icon-wrench"></i>
		    </div>
		    <div class="details">
			<div class="desc">                           
			    Admin
			</div>
		    </div>      
		</div>
	    </a>
	</div>
	<div class="span4 responsive" data-tablet="span4" data-desktop="span4">
	    <a href="<?php echo $this->baseUrl( 'register' ); ?>">
		<div class="dashboard-stat green">
		    <div class="visual">
			<i class="icon-globe"></i>
		    </div>
		    <div class="details">
			<div class="desc">
			    Rejistu Geral
			</div>
		    </div>              
		</div>
	    </a>
	</div>
	<div class="span4 responsive" data-tablet="span4" data-desktop="span4">
	    <a href="<?php echo $this->baseUrl( 'client' ); ?>">
		<div class="dashboard-stat purple">
		    <div class="visual">
			<i class="icon-male"></i>
		    </div>
		    <div class="details">
			<div class="desc">
			    Jestaun Kazu
			</div>
		    </div>            
		</div>
	    </a>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span4 responsive" data-tablet="span4" data-desktop="span4">
	    <a href="<?php echo $this->baseUrl( 'job' ); ?>">
		<div class="dashboard-stat yellow">
		    <div class="visual">
			<i class="icon-briefcase"></i>
		    </div>
		    <div class="details">
			<div class="desc">
			    Empregu
			</div>
		    </div>             
		</div>
	    </a>
	</div>
	<div class="span4 responsive" data-tablet="span4" data-desktop="span4">
	    <a href="#">
		<div class="dashboard-stat red">
		    <div class="visual">
			<i class="icon-list-alt"></i>
		    </div>
		    <div class="details">
			<div class="desc">
			    FEFOP
			</div>
		    </div>             
		</div>
	    </a>
	</div>
	<div class="span4 responsive" data-tablet="span4" data-desktop="span4">
	    <a href="<?php echo $this->baseUrl( 'student-class' ); ?>">
		<div class="dashboard-stat grey">
		    <div class="visual">
			<i class="icon-book"></i>
		    </div>
		    <div class="details">
			<div class="desc">
			    Formasaun
			</div>
		    </div>             
		</div>
	    </a>
	</div>
    </div>
</div>
     -->

<?php echo $this->render( 'index/indicators.phtml' ); ?>
<?php echo $this->render( 'index/graphs.phtml' ); ?>