<div class="row-fluid">
    <div class="span12">
	<!-- BEGIN Portlet PORTLET-->
	<div class="portlet">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Indicadores</div>
		<div class="tools">
		    <a href="javascript:;" class="collapse"></a>
		</div>
	    </div>
	    <div class="portlet-body">
		<div class="row-fluid" id="indicators">
		    <div class="span3 responsive clients" data-tablet="span6" data-desktop="span3">
			<div class="dashboard-stat blue">
			    <div class="visual">
				<i class="icon-male"></i>
			    </div>
			    <div class="details">
				<div class="number">
				    0
				</div>
				<div class="desc">                           
				    Kliente
				</div>
			    </div>
			</div>
		    </div>
		    <div class="span3 responsive graduated" data-tablet="span6" data-desktop="span3">
			<div class="dashboard-stat grey">
			    <div class="visual">
				<i class="icon-book"></i>
			    </div>
			    <div class="details">
				<div class="number">0</div>
				<div class="desc">Graduados</div>
			    </div>                 
			</div>
		    </div>
		    <div class="span3 responsive job-vacancy" data-tablet="span6  fix-offset" data-desktop="span3">
			<div class="dashboard-stat yellow">
			    <div class="visual">
				<i class="icon-briefcase"></i>
			    </div>
			    <div class="details">
				<div class="number">0</div>
				<div class="desc">Vaga Empregu</div>
			    </div>               
			</div>
		    </div>
		    <div class="span3 responsive find-job" data-tablet="span6" data-desktop="span3">
			<div class="dashboard-stat red">
			    <div class="visual">
				<i class="icon-trophy"></i>
			    </div>
			    <div class="details">
				<div class="number">0</div>
				<div class="desc">Hetan Serbisu</div>
			    </div>             
			</div>
		    </div>
		</div>
	    </div>
	</div>
	<!-- END Portlet PORTLET-->
    </div>
</div>