<?php foreach ($this->activities as $activity) : ?>
  <li>
    <a href="javascript:;" onclick="Activity.trigger('<?php echo $activity->type ?>', '<?php echo $activity->id ?>');">
      <span class="subject">
        <span style="display: block" class="from muted">
          <em><?php echo $this->truncate($activity->title, 100); ?></em>
        </span>
      </span>
      <span class="message">
        <?php echo $this->truncate($activity->description, 100); ?>
      </span>
      <span class="time text-right" style="display: block"><?php echo $this->date($activity->date); ?></span>
    </a>
  </li>
<?php endforeach; ?>