<div class="form-view">
    <div class="row-fluid">
	<div class="span12">
	    <div class="control-group">
		<label class="control-label bold">Benefisiariu:</label>
		<div class="controls">
		    <span class="text">
			<?php echo $this->row->beneficiary; ?>
		    </span>
		</div>
	    </div>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span4">
	    <div class="control-group">
		<label class="control-label bold">Programa:</label>
		<div class="controls">
		    <span class="text">
			<?php echo $this->row->program_acronym; ?>
		    </span>
		</div>
	    </div>
	</div>
	<div class="span4">
	    <div class="control-group">
		<label class="control-label bold">Modulu:</label>
		<div class="controls">
		    <span class="text">
			<?php echo $this->row->module_acronym; ?>
		    </span>
		</div>
	    </div>
	</div>
	<div class="span4">
	    <div class="control-group">
		<label class="control-label bold">Ativu:</label>
		<div class="controls">
		    <span class="label label-<?php echo $this->row->active ? 'success' : 'warning'; ?>">
			<?php echo $this->row->active ? 'Sim' : 'Lae'; ?>
		    </span>
		</div>
	    </div>
	</div>
    </div>
     <div class="row-fluid">
	<div class="span6">
	    <div class="control-group">
		<label class="control-label bold">Uzuariu Rejistu:</label>
		<div class="controls">
		    <span class="text">
			<?php echo $this->row->user_inserted; ?>
		    </span>
		</div>
	    </div>
	</div>
	<div class="span6">
	    <div class="control-group">
		<label class="control-label bold">Uzuariu Remove:</label>
		<div class="controls">
		    <span class="text">
			<?php echo empty( $this->row->user_removed ) ? '-' : $this->row->user_removed; ?>
		    </span>
		</div>
	    </div>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span12">
	    <div class="control-group">
		<label class="control-label bold">Comentariu:</label>
		<div class="controls">
		    <span class="text">
			<?php echo $this->row->comment; ?>
		    </span>
		</div>
	    </div>
	</div>
    </div>
    <?php if ( empty( $this->row->active ) ) : ?>
	<div class="row-fluid">
	    <div class="span12">
		<div class="control-group">
		    <label class="control-label bold">Comentariu Remove:</label>
		    <div class="controls">
			<span class="text">
			    <?php echo $this->row->comment_remove; ?>
			</span>
		    </div>
		</div>
	    </div>
	</div>
    <?php endif; ?>
</div>