<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-search"></i>Buka benefisiariu la kumpridor</div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<?php $this->placeholder( 'form' )->captureStart(); ?>

		    <div class="box-content">
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'id_fefop_programs' ); ?>
			    </div>
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_fefop_modules' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
                            <div class="span6">
                                <?php echo $this->form->getElement( 'fk_id_user_inserted' ); ?>
                            </div>
                            <div class="span6">
                                <?php echo $this->form->getElement( 'fk_id_user_removed' ); ?>
                            </div>
                        </div>
			<div class="row-fluid">
			    <div class="span4">
				<?php echo $this->form->getElement( 'status' ); ?>
			    </div>
			    <div class="span8">
				<?php echo $this->form->getElement( 'beneficiary_name' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span4">
				<?php echo $this->form->getElement( 'type_beneficiary' ); ?>
			    </div>
			    <div class="span4">
				<?php echo $this->form->getElement( 'date_registration_fim' ); ?>
			    </div>
			    <div class="span4">
				<?php echo $this->form->getElement( 'date_registration_fim' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="form-actions">
				<button class="btn blue" id="btn-search-beneficiary">Buka <i class="icon-search m-icon-white"></i></button>
				<button class="btn green" type="reset" id="clear">Hamoos <i class="icon-trash m-icon-white"></i></button>
			    </div>
			</div>
		    </div>
		
		<?php
		    $this->placeholder( 'form' )->captureEnd();
		    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
		?>
	    </div>
	</div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Buka Benefisiariu la kumpridor</div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="beneficiary-blacklist-list">
		    <thead>
			<tr>
			    <th>Benefisiariu</th>
			    <th>Kontatu</th>
			    <th>Programa</th>
			    <th>Modulu</th>
			    <th>Tipu</th>
			    <th>Ativu?</th>
			    <th>Haree</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>