<?php 
    $this->placeholder( 'form' )->captureStart();
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'max_length' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'sms_unit_cost' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'error_attempts' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'sent_by_second' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'sim_cards' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'gateway_url' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'sms_prefix' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'sms_sufix' ); ?>
		</div>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>