<div class="form-view">
    <div class="row-fluid">
	<div class="span12">
	    <div class="control-group">
		<label class="control-label bold">Titulu:</label>
		<div class="controls">
		    <span class="text">
			<?php echo $this->note->title; ?>
		    </span>
		</div>
	    </div>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span3">
	    <div class="control-group">
		<label class="control-label bold">Se mak haruka:</label>
		<div class="controls">
		    <span class="text">
			<?php echo empty( $this->note->name ) ? 'Sistema' : $this->note->name; ?>
		    </span>
		</div>
	    </div>
	</div>
	<div class="span3">
	    <div class="control-group">
		<label class="control-label bold">Data Rejistu:</label>
		<div class="controls">
		    <span class="text">
			<?php echo $this->note->date; ?>
		    </span>
		</div>
	    </div>
	</div>
	<div class="span3">
	    <div class="control-group">
		<label class="control-label bold">Nivel:</label>
		<div class="controls">
		    <span class="text">
			<label class="label label-<?php echo $this->note->level == 0 ? 'important' : 'warning'; ?>">
			    <?php echo $this->note->level == 0 ? 'Urgente' : 'Normal'; ?>
			</label>
		    </span>
		</div>
	    </div>
	</div>
	<div class="span3">
	    <div class="control-group">
		<label class="control-label bold">Ajendadu:</label>
		<div class="controls">
		    <span class="text">
			<?php echo $this->note->scheduled ? $this->note->scheduled : '-' ; ?>
		    </span>
		</div>
	    </div>
	</div>
    </div>
    <hr />
    <div class="row-fluid">
	<div class="span12">
	    <div class="control-group">
		<label class="control-label bold">Mensagem:</label>
	    </div>
	</div>
    </div>
    <div class="row-fluid">
	<?php echo $this->note->message; ?>
    </div>
</div>