<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_sysuser' );
 ?>
    <div class="row-fluid">
	<div class="span12">
	    <?php echo $this->form->getElement( 'title' ); ?>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span4">
	    <?php echo $this->form->getElement( 'level' ); ?>
	</div>
	<div class="span4">
	    <?php echo $this->form->getElement( 'date_scheduled' ); ?>
	</div>
	<div class="span4">
	    <?php echo $this->form->getElement( 'status' ); ?>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span6">
	    <?php echo $this->form->getElement( 'users' ); ?>
	</div>
	<div class="span6">
	    <?php echo $this->form->getElement( 'groups' ); ?>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span12">
	    <?php echo $this->form->getElement( 'message' ); ?>
	</div>
    </div>

<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>