<table class="table table-striped table-bordered table-hover table-full-width" id="note-to-user">
    <thead>
	<tr>
	    <th>Titulu</th>
	    <th style="width: 12%">Data Rejistu</th>
	    <th style="width: 12%">Nivel</th>
	    <th>Husi</th>
	    <th style="width: 12%">Le tiha ona?</th>
	    <th style="width: 10%" class="no-sort">Action</th>
	</tr>
    </thead>
    <tbody></tbody>
</table>
