<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_businessplan' );
 ?>

    <div class="box-content">
	
	<div class="row-fluid">
	    <div class="span12">
		<div class="alert alert-info not-remove">
		    Konsidera análize klean iha dokumentu Rekomendasaun Téknika, prioridade nasionál sira no viabilidade ekonómika iha área negósiu projetu nian, Konsellu Administrasaun delibera katak:
		</div>
	    </div>
	</div>

	<div class="row-fluid">
	    <div class="span6">
		<?php echo $this->form->getElement( 'approved' ); ?>
	    </div>
	    <div class="span6">
		<?php echo $this->form->getElement( 'date_contract' ); ?>
	    </div>
	</div>
	<hr />
	<div class="row-fluid">
	    <div class="span12">
		<?php echo $this->form->getElement( 'council_negative' ); ?>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>