<?php echo $this->fefopContract()->getMessages(); ?>

<input type="hidden" name="id_contract" id="id_contract" value="<?php echo $this->contract->fk_id_fefop_contract; ?>" />
<input type="hidden" name="business-plan" id="business-plan" value="<?php echo $this->contract->id_businessplan; ?>" />
<div class="portlet gren box blue">
    <div class="portlet-title">
	<div class="caption">
	    <i class="icon-reorder"></i>Dadus Indívidu nian
	</div>
	<div class="tools">
	    <a href="javascript:;" class="collapse"></a>
	</div>
    </div>
    <div class="portlet-body">
	<div class="row-fluid">
	    <div class="span7">
		<div class="control-group">
		    <label class="control-label">Naran Kliente:</label>
		    <div class="controls">
			<span class="text bold">
			    <?php echo Client_Model_Mapper_Client::buildName( $this->client ); ?>
			</span>
		    </div>
		</div>
	    </div>
	    <div class="span3">
		<div class="control-group">
		    <label class="control-label">E-mail:</label>
		    <div class="controls">
			<span class="text bold">
			    <?php echo $this->client->email; ?>
			</span>
		    </div>
		</div>
	    </div>
	    <?php if ( !$this->print && $this->contract->submitted ) : ?>
		<div class="span2">
		    <div class="control-group">
			<div class="controls">
			    <div class="btn-group">
				<a class="btn red" href="javascript:;" data-toggle="dropdown">
				    <i class="icon-print"></i>  
				    <i class="icon-angle-down"></i>
				</a>
				<ul class="dropdown-menu">
				    <li>
					<a href="javascript:;" onClick="Fefop.PceContract.printContract();">
					    <i class="icon-book"></i> 
					    Planu Negosiu
					</a>
				    </li>
				    <?php if ( $this->contract->fk_id_fefop_contract ) : ?>
					<li>
					    <a href="javascript:;" onClick="Fefop.PceContract.exportContract();">
						<i class="icon-group"></i> 
						Kontratu
					    </a>
					</li>
				    <?php endif; ?>
				</ul>
			    </div>
			</div>
		    </div>
		</div>
	    <?php endif; ?>
	</div>
	<div class="row-fluid">
	    <div class="span4">
		<div class="control-group">
		    <label class="control-label">Kartaun Evidensia:</label>
		    <div class="controls">
			<span class="text bold">
			    <strong><?php echo Client_Model_Mapper_Client::buildNumRow( $this->client ); ?></strong>
			</span>
		    </div>
		</div>
	    </div>
	    <div class="span4">
		<div class="control-group">
		    <label class="control-label">Kartaun eleitorál:</label>
		    <div class="controls">
			<span class="text bold">
			    <?php echo $this->client->electoral; ?>
			</span>
		    </div>
		</div>
	    </div>
	    <div class="span4">
		<div class="control-group">
		    <label class="control-label">Telefone:</label>
		    <div class="controls">
			<span class="text bold">
			    <?php echo $this->client->client_fone; ?>
			</span>
		    </div>
		</div>
	    </div>
	</div>
	<hr />

	<div class="row-fluid">
	    <div class="span4">
		<div class="control-group">
		    <label class="control-label">Setor de Atividade nian</label>
		    <div class="controls"><strong><?php echo $this->contract->name_disivion ; ?></strong></div>
		</div>
	    </div>
	    <div class="span4">
		<div class="control-group">
		    <label class="control-label">Atividade de Negosiu nian</label>
		    <div class="controls"><strong><?php echo $this->contract->name_classtimor ; ?></strong></div>
		</div>
	    </div>
	    <div class="span4">
		<div class="control-group">
		    <label class="control-label">Distritu</label>
		    <div class="controls"><strong><?php echo $this->contract->district ; ?></strong></div>
		</div>
	    </div>
	</div>
    </div>
</div>

<div class="portlet gren box blue">
    <div class="portlet-title">
	<div class="caption">
	    <i class="icon-reorder"></i>Dadus grupu
	</div>
	<div class="tools">
	    <a href="javascript:;" class="collapse"></a>
	</div>
    </div>
    <div class="portlet-body">
	<div class="row-fluid">
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label">Grupu</label>
		    <div class="controls"><strong><?php echo $this->contract->partisipants == 'G' ? 'Sin' : 'Lae' ; ?></strong></div>
		</div>
	    </div>
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label">Totál membru benefisiáriu</label>
		    <div class="controls"><strong><?php echo $this->contract->total_partisipants ; ?></strong></div>
		</div>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="span12">
		<div class="portlet box light-grey">
		    <div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i>Benefisiariu Sira</div>
		    </div>
		    <div class="portlet-body form" id="partisipants-group" style="overflow: auto">
			<table class="table table-striped table-bordered table-hover table-full-width" id="client-pce-list">
			    <thead>
				<tr>
				    <th>Naran indívidu</th>
				    <th>Kartaun Evidensia</th>
				    <th>Kartaun Eleitoral</th>
				    <th>Seksu</th>
				    <th>Defisiénsia</th>
				    <th></th>
				</tr>
			    </thead>
			    <tbody>
				<tr>
				    <td><?php echo Client_Model_Mapper_Client::buildName( $this->client ); ?></td>
				    <td><?php echo Client_Model_Mapper_Client::buildNumRow( $this->client ); ?></td>
				    <td><?php echo $this->client->electoral; ?></td>
				    <td><?php echo $this->client->gender; ?></td>
				    <td><?php echo Client_Model_Mapper_Client::isHandicapped(  $this->client->id_perdata ) ? 'Sin' : 'Lae'; ?></td>
				    <td>
					
				    </td>
				</tr>
				<?php if ( $this->clientsBusinessPlan ) : ?>
				    <?php 
					foreach ( $this->clientsBusinessPlan as $client )
					    echo $this->action( 'add-client', 'pce', 'external', array( 'row' => $client, 'no_edit' => true ) );
				    ?>
				<?php endif; ?>
			    </tbody>
			</table>
		    </div>
		</div>
	    </div>
	</div>
    </div>
</div>

<div class="portlet gren box blue">
    <div class="portlet-title">
	<div class="caption">
	    <i class="icon-reorder"></i>Dadus Empreza nian
	</div>
	<div class="tools">
	    <a href="javascript:;" class="collapse"></a>
	</div>
    </div>
    <div class="portlet-body">
	<div class="row-fluid">
	    <div class="span12">
		<div class="control-group">
		    <label class="control-label">Naran Projetu</label>
		    <div class="controls"><strong><?php echo $this->contract->project_name ; ?></strong></div>
		</div>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="span4">
		<div class="control-group">
		    <label class="control-label">Distritu</label>
		    <div class="controls"><strong><?php echo $this->contract->district ; ?></strong></div>
		</div>
	    </div>
	    <div class="span4">
		<div class="control-group">
		    <label class="control-label">Sub Distritu</label>
		    <div class="controls"><strong><?php echo $this->contract->sub_district ; ?></strong></div>
		</div>
	    </div>
	    <div class="span4">
		<div class="control-group">
		    <label class="control-label">Suku</label>
		    <div class="controls"><strong><?php echo $this->contract->sucu ; ?></strong></div>
		</div>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="span12">
		<div class="control-group">
		    <label class="control-label">Deskrisaun kona-ba lokalizasaun</label>
		    <div class="controls"><strong><?php echo $this->contract->location_description ; ?></strong></div>
		</div>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label">Telefone</label>
		    <div class="controls"><strong><?php echo $this->contract->phone ; ?></strong></div>
		</div>
	    </div>
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label">E-mail</label>
		    <div class="controls"><strong><?php echo $this->contract->email ; ?></strong></div>
		</div>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label">Naran ema ne'ebé dezenvolve Planu Negósiu nian</label>
		    <div class="controls"><strong><?php echo Client_Model_Mapper_Client::buildNameById( $this->contract->bussines_plan_developer ); ?></strong></div>
		</div>
	    </div>
	    <div class="span3">
		<div class="control-group">
		    <label class="control-label">Tipu empreza</label>
		    <div class="controls"><strong><?php echo $this->contract->type_enterprise ; ?></strong></div>
		</div>
	    </div>
	    <div class="span3">
		<div class="control-group">
		    <label class="control-label">Tinan atu hahú atividade</label>
		    <div class="controls"><strong><?php echo $this->contract->year_activity ; ?></strong></div>
		</div>
	    </div>
	</div>
    </div>
</div>

<div class="portlet red box">
    <div class="portlet-title">
	<div class="caption">
	    <i class="icon-reorder"></i>Planeamentu Estratéjiku Negósiu nian
	</div>
	<div class="tools">
	    <a href="javascript:;" class="collapse"></a>
	</div>
    </div>
    <div class="portlet-body">
	<div class="row-fluid">
	    <div class="span12">
		<div class="control-group">
		    <label class="control-label bold"><?php echo htmlspecialchars( $this->description_fields['visao'] ); ?></label>
		    <div class="controls">
			<?php echo @$this->values_description_fields['visao']; ?>
		    </div>
		</div>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="span12">
		<div class="control-group">
		    <label class="control-label bold"><?php echo htmlspecialchars( $this->description_fields['missao'] ); ?></label>
		    <div class="controls">
			<?php echo @$this->values_description_fields['missao']; ?>
		    </div>
		</div>
	    </div>
	</div>
	
	<h4 class="bold">Análize kona- ba Ambiente Esternu</h4>
	<div class="row-fluid">
	    <div class="span11 offset1">
		<div class="control-group">
		    <label class="control-label bold"><?php echo htmlspecialchars( $this->description_fields['ameacas'] ); ?></label>
		    <div class="controls">
			<?php echo @$this->values_description_fields['ameacas']; ?>
		    </div>
		</div>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="span11 offset1">
		<div class="control-group">
		    <label class="control-label bold"><?php echo htmlspecialchars( $this->description_fields['oportunidades'] ); ?></label>
		    <div class="controls">
			<?php echo @$this->values_description_fields['oportunidades']; ?>
		    </div>
		</div>
	    </div>
	</div>
	
	<h4 class="bold">Análize kona-ba Ambiente Internu</h4>
	<div class="row-fluid">
	    <div class="span11 offset1">
		<div class="control-group">
		    <label class="control-label bold"><?php echo htmlspecialchars( $this->description_fields['forcas'] ); ?></label>
		    <div class="controls">
			<?php echo @$this->values_description_fields['forcas']; ?>
		    </div>
		</div>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="span11 offset1">
		<div class="control-group">
		    <label class="control-label bold"><?php echo htmlspecialchars( $this->description_fields['fraquezas'] ); ?></label>
		    <div class="controls">
			<?php echo @$this->values_description_fields['fraquezas']; ?>
		    </div>
		</div>
	    </div>
	</div>
	
	<h4 class="bold">Objetivu no Meta</h4>
	<div class="row-fluid">
	    <div class="span11 offset1">
		<div class="control-group">
		    <label class="control-label bold"><?php echo htmlspecialchars( $this->description_fields['objetivos_metas'] ); ?></label>
		    <div class="controls">
			<?php echo @$this->values_description_fields['objetivos_metas']; ?>
		    </div>
		</div>
	    </div>
	</div>
	
	<h4 class="bold">Estratéjia</h4>
	<div class="row-fluid">
	    <div class="span11 offset1">
		<div class="control-group">
		    <label class="control-label bold"><?php echo htmlspecialchars( $this->description_fields['estrategia'] ); ?></label>
		    <div class="controls">
			<?php echo @$this->values_description_fields['estrategia']; ?>
		    </div>
		</div>
	    </div>
	</div>
	
	<h4 class="bold">Produtu no/ka Servisu sira</h4>
	<div class="row-fluid">
	    <div class="span11 offset1">
		<div class="control-group">
		    <label class="control-label bold"><?php echo htmlspecialchars( $this->description_fields['desc_produto'] ); ?></label>
		    <div class="controls">
			<?php echo @$this->values_description_fields['desc_produto']; ?>
		    </div>
		</div>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="span11 offset1">
		<div class="control-group">
		    <label class="control-label bold"><?php echo htmlspecialchars( $this->description_fields['why_produto'] ); ?></label>
		    <div class="controls">
			<?php echo @$this->values_description_fields['why_produto']; ?>
		    </div>
		</div>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="span12">
		<div class="control-group">
		    <label class="control-label bold"><?php echo htmlspecialchars( $this->description_fields['analise_mercado'] ); ?></label>
		    <div class="controls">
			<?php echo @$this->values_description_fields['analise_mercado']; ?>
		    </div>
		</div>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="span12">
		<div class="control-group">
		    <label class="control-label bold"><?php echo htmlspecialchars( $this->description_fields['canais_dist'] ); ?></label>
		    <div class="controls">
			<?php echo @$this->values_description_fields['canais_dist']; ?>
		    </div>
		</div>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="span12">
		<div class="control-group">
		    <label class="control-label bold"><?php echo htmlspecialchars( $this->description_fields['plano_marketing'] ); ?></label>
		    <div class="controls">
			<?php echo @$this->values_description_fields['plano_marketing']; ?>
		    </div>
		</div>
	    </div>
	</div>
    </div>
</div>

<div class="portlet green box">
    <div class="portlet-title">
	<div class="caption">
	    <i class="icon-reorder"></i>Planu Finanseiru
	</div>
	<div class="tools">
	    <a href="javascript:;" class="collapse"></a>
	</div>
    </div>
    <div class="portlet-body">
	
	<div class="row-fluid">
	    <div class="span12">
		<h4><strong>Rúbrika despeza</strong></h4>
		<table class="table table-striped table-bordered table-hover table-full-width" id="expense-list">
		    <thead>
			<tr>
			    <th style="width: 7%">#</th>
			    <th>Rúbrika</th>			
			    <th style="width: 15%">Folin Hira</th>
			</tr>
		    </thead>
		    <tbody>
			<?php 
			    $count = 'A';
			    foreach ( $this->expenses as $expense ) :
				echo $this->partial( 'pce-contract/row-expense.phtml', array( 'expense' => $expense, 'name' => 'cost_expense', 'count' => $count++, 'readonly' => true ) );
			    endforeach; 
			?>
			<tr>
			    <td><?php echo $count; ?>.</td>
			    <td>Fundu Maneiu (600 USD + 10% rúbrika sira iha leten)</td>
			    <td>
				<div class="control-group">
				    <div class="controls">
					<strong>
					    <?php 
						$total = 0;
						if ( !empty( $this->totals_fields['reserve_fund'] ) )
						    $total = $this->totals_fields['reserve_fund'];
						
						echo $this->currency( $total ); 
					    ?>
					</strong>
				    </div>
				</div>
			    </td>
			</tr>
		    </tbody>
		    <tfoot>
			 <tr>
			    <td colspan="2">TOTAL</td>
			    <td>
				<div class="control-group">
				    <div class="controls">
					<strong>
					    <?php 
						$total = 0;
						if ( !empty( $this->totals_fields['total_expense'] ) )
						    $total = $this->totals_fields['total_expense'];
						
						echo $this->currency( $total ); 
					    ?>
					</strong>
				    </div>
				</div>
			    </td>
			</tr>
		    </tfoot>
		</table>
	    </div>
	</div>
	
	<div class="row-fluid">
	    <div class="span12">
		<h4><strong>Rúbrika Detallada</strong></h4>
		<?php 
		    $count = 'A';
		    foreach ( $this->expenses as $expense ) : 
		?>
		    <div class="row-fluid">
			<div class="span12">
			    <div class="portlet box light-grey expense-portlet" id="expense-portlet-<?php echo $expense->id_budget_category; ?>" >
				<input type="hidden" name="expense-detailed" class="expense-id" value="<?php echo $expense->id_budget_category; ?>" />
				<div class="portlet-title">
				    <div class="caption" style="font-size: 11px">
					<strong><?php echo ( $count++ ) . ' - ' . $expense->description; ?></strong>
				    </div>
				    <div class="tools"><a href="javascript:;" class="expand"></a></div>
				</div>
				<div class="portlet-body form hide">
				    <table class="table table-striped table-bordered table-hover table-full-width" id="expense-detailed-list-<?php echo $expense->id_budget_category; ?>">
					<thead>
					    <tr>
						<th>Item</th>
						<th style="width: 10%">Ktd.</th>
						<th style="width: 12%">Kustu unitáriu</th>			
						<th style="width: 10%">Totál</th>
						<th style="width: 5%"></th>
					    </tr>
					</thead>
					<tbody>
					    <?php 
						if ( !empty( $this->itemsExpense ) && !empty( $this->itemsExpense[$expense->id_budget_category] ) ) {

						    foreach ( $this->itemsExpense[$expense->id_budget_category] as $itemExpense )
							echo $this->action( 'add-detailed-expense', 'pce', 'external', array( 'expense' => $expense->id_budget_category, 'no_edit' => $this->no_edit, 'row' => $itemExpense ) );
						}
					    ?>
					</tbody>
				    </table>
				</div>
			    </div>
			</div>
		    </div>
		<?php endforeach; ?>
	    </div>
	</div>
	
	<h3><strong>Retornu anuál Investimentu nian</strong></h3>
	
	<div class="row-fluid">
	    <div class="span12">
		<h4><strong>Investimentu Inisiál ne'ebé FEFOP la finansia - tinan dahuluk</strong></h4>
		<table class="table table-striped table-bordered table-hover table-full-width" id="initial-expense-list">
		    <thead>
			<tr>
			    <th style="width: 7%">#</th>
			    <th>Rúbrika</th>			
			    <th style="width: 15%">Folin Hira</th>
			</tr>
		    </thead>
		    <tbody>
			<?php 
			    $count = 'A';
			    foreach ( $this->initial_expense as $expense ) :
				echo $this->partial( 'pce-contract/row-expense.phtml', array( 'expense' => $expense, 'name' => 'initial_expense', 'count' => $count++ ) );
			    endforeach; 
			?>
			    <tr>
				<td colspan="2">TOTAL</td>
				<td>
				    <div class="control-group">
					<div class="controls">
					    <strong>
						<?php 
						    $total = 0;
						    if ( !empty( $this->totals_fields['investiment'] ) )
							$total = $this->totals_fields['investiment'];

						    echo $this->currency( $total ); 
						?>
					    </strong>
					</div>
				    </div>
				</td>
			    </tr>
		    </tbody>
		</table>
	    </div>
	</div>
	
	<div class="row-fluid">
	    <div class="span12">
		<h4><strong>Kustus anuál - hahú iha tinan daruak</strong></h4>
		<table class="table table-striped table-bordered table-hover table-full-width" id="annual-expense-list">
		    <thead>
			<tr>
			    <th style="width: 7%">#</th>
			    <th>Rúbrika</th>			
			    <th style="width: 15%">Folin Hira</th>
			</tr>
		    </thead>
		    <tbody>
			<?php 
			    $count = 'A';
			    foreach ( $this->annual_expense as $expense ) :
				echo $this->partial( 'pce-contract/row-expense.phtml', array( 'expense' => $expense, 'name' => 'annual_expense', 'count' => $count++ ) );
			    endforeach; 
			?>
			    <tr>
				<td colspan="2">TOTAL</td>
				<td>
				    <div class="control-group">
					<div class="controls">
					    <strong>
						<?php 
						    $total = 0;
						    if ( !empty( $this->totals_fields['annual_expense'] ) )
							$total = $this->totals_fields['annual_expense'];

						    echo $this->currency( $total ); 
						?>
					    </strong>
					</div>
				    </div>
				</td>
			    </tr>
		    </tbody>
		</table>
	    </div>
	</div>
	
	<div class="row-fluid">
	    <div class="span12">
		<h4><strong>Reseita sira</strong></h4>
		<table class="table table-striped table-bordered table-hover table-full-width" id="revenue-expense-list">
		    <thead>
			<tr>
			    <th style="width: 7%">#</th>
			    <th>Rúbrika</th>			
			    <th style="width: 15%">Folin Hira</th>
			</tr>
		    </thead>
		    <tbody>
			<?php 
			    $count = 'A';
			    foreach ( $this->revenue_expense as $expense ) :
				echo $this->partial( 'pce-contract/row-expense.phtml', array( 'expense' => $expense, 'name' => 'revenue_expense', 'count' => $count++ ) );
			    endforeach; 
			?>
			    <tr>
				<td colspan="2">TOTAL</td>
				<td>
				    <div class="control-group">
					<div class="controls">
					    <strong>
						<?php 
						    $total = 0;
						    if ( !empty( $this->totals_fields['revenue'] ) )
							$total = $this->totals_fields['revenue'];

						    echo $this->currency( $total ); 
						?>
					    </strong>
					</div>
				    </div>
				</td>
			    </tr>
		    </tbody>
		</table>
	    </div>
	</div>
	
	<h4><strong>LUKRU NE'EBÉ HEIN</strong></h4>
	
	<div class="row-fluid">
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label">TINAN DAHULUK</label>
		    <div class="controls">
			<strong>
			    <?php 
				$total = 0;
				if ( !empty( $this->totals_fields['first_year'] ) )
				    $total = $this->totals_fields['first_year'];

				echo $this->currency( $total ); 
			    ?>
			</strong>
		    </div>
		</div>
	    </div>
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label">TINAN SIRA TUIRMAI</label>
		    <div class="controls">
			<strong>
			    <?php 
				$total = 0;
				if ( !empty( $this->totals_fields['following_year'] ) )
				    $total = $this->totals_fields['following_year'];

				echo $this->currency( $total ); 
			    ?>
			</strong>
		    </div>
		</div>
	    </div>
	</div>
	
    </div>
</div>