<?php $this->headScript()->appendFile( $this->baseUrl( 'public/scripts/controller/fefop/contract.js' ) );  ?>
<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-search"></i>Buka Kontratu Kriasaun Empreza</div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<?php $this->placeholder( 'form' )->captureStart(); ?>

		    <div class="box-content">
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_adddistrict' ); ?>
			    </div>
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_fefop_modules' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_isicdivision' ); ?>
			    </div>
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_isicclasstimor' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span4">
				<?php echo $this->form->getElement( 'partisipants' ); ?>
			    </div>
			    <div class="span4">
				<?php echo $this->form->getElement( 'submitted' ); ?>
			    </div>
			    <div class="span4">
				<?php echo $this->form->getElement( 'contract' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span12">
				<?php echo $this->form->getElement( 'bussines_plan_developer' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="form-actions">
				<button class="btn blue">Buka <i class="icon-search m-icon-white"></i></button>
				<button class="btn green" type="reset" id="clear">Hamoos <i class="icon-trash m-icon-white"></i></button>
				<button onclick="Fefop.Contract.printGrid( '#pce-contract-list' );" class="btn purple" type="button">Print <i class="icon-print m-icon-white"></i></button>
			    </div>
			</div>
		    </div>
		
		<?php
		    $this->placeholder( 'form' )->captureEnd();
		    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
		?>
	    </div>
	</div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Buka Kontratu Kriasaun Empreza</div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="pce-contract-list">
		    <thead>
			<tr>
			    <th>Planu Negosiu</th>
			    <th>Kontratu</th>
			    <th>Desenvolvedor</th>
			    <th>Modulu</th>
			    <th>Grupu</th>
			    <th>Submit</th>
			    <th>Status</th>
			    <th class='no-sort'>Action</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>