<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-volume-up"></i>Revizaun</div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<?php echo $this->form; ?>
	    </div>
	</div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Revizaun hotu-hotu</div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="revision-list">
		    <thead>
			<tr>
			    <th>Uzuariu</th>
			    <th>Deskrisaun</th>
			    <th>Data/Óra</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>