<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_businessplan' );
 ?>

    <?php echo $this->fefopContract()->getMessages(); ?>

    <div class="box-content">
	<h4>Benefisiariu</h4>
	
	<table class="table table-striped table-bordered table-hover table-full-width">
	    <tbody>
		<?php 
		    $count = 0;
		    foreach ( $this->feedbackFields as $key => $item ): 
		?>
		    <tr>
			<td><?php echo ++$count; ?></td>
			<td>
			    <strong><?php echo $item['label']; ?></strong>
			    <?php if ( !empty( $item['description'] ) ) : ?>
				<p><?php echo $item['description']; ?></p>
			    <?php endif; ?>
			</td>
			<td>
			    <a class="btn icn-only <?php echo $item['valid'] ? 'green' : 'red'; ?>" href="javascript:;" title="<?php echo $item['label']; ?>">
				<i class="m-icon-white icon-<?php echo $item['valid'] ? 'ok' : 'warning-sign'; ?>"></i>
			    </a>
			</td>
		    </tr>
		<?php endforeach; ?>
	    </tbody>
	</table>
	
	<h4>Vizita Prévia</h4>
	<div class="row-fluid">
	    <div class="span12">
		<?php echo $this->form->getElement( 'previous_visit' ); ?>
	    </div>
	</div>
	<hr />
	
	<h4>Apoiu Finanseiru sira</h4>
	
	<div class="row-fluid">
	    <div class="span4">
		<?php echo $this->form->getElement( 'amount' ); ?>
	    </div>
	    <div class="span4">
		<div class="control-group">
		    <label class="control-label">Valór másimu:</label>
		    <div class="controls">
			<span class="text bold">
			    <?php echo $this->currency( $this->amount_max ); ?>
			</span>
		    </div>
		</div>
	    </div>
	    <div class="span4">
		<div class="control-group">
		    <label class="control-label">Valór kontratu nian:</label>
		    <div class="controls">
			<span class="text bold">
			    <?php echo $this->currency( $this->amount_contract ); ?>
			</span>
		    </div>
		</div>
	    </div>
	</div>
	<hr />
	<div class="row-fluid">
	    <div class="span12">
		<?php echo $this->form->getElement( 'expenses' ); ?>
	    </div>
	</div>
	<hr />
	<div class="row-fluid">
	    <div class="span12">
		<?php echo $this->form->getElement( 'other_sponsors' ); ?>
	    </div>
	</div>
	<hr />
	
	
	<div class="row-fluid">
	    <div class="span12">
		<?php echo $this->form->getElement( 'business_plan' ); ?>
	    </div>
	</div>
	<hr />
	<div class="row-fluid">
	    <div class="span12">
		<?php echo $this->form->getElement( 'viability' ); ?>
	    </div>
	</div>
	<hr />
	<div class="row-fluid text-bold">
	    <div class="span12">
		<h3>Rekomendasaun</h3>
		<?php echo $this->form->getElement( 'approved' ); ?>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>