<div class="box-content">
    <?php $this->placeholder('form')->captureStart(); ?>
    
        <?php foreach($this->form->getElements() as $element): ?>
            <?php if ($element instanceof Zend_Form_Element_Hidden): ?>
                <?php echo $element; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        
        <div class="row-fluid">
            <div class="control-group span6">
                <?php echo $this->form->getElement('date_start'); ?>
            </div>
            <div class="control-group span6">
                <?php echo $this->form->getElement('date_finish'); ?>
            </div>
        </div>
        
        <div class="row-fluid">   
    		<div class="control-group span6">
                <?php echo $this->form->getElement('fk_id_fefop_type_transaction'); ?>
            </div>
            <div class="control-group span6">
                <?php echo $this->form->getElement('fk_id_fefopfund'); ?>
            </div>
        </div>
    
        <div class="row-fluid">   
	    <div class="control-group span6">
                <?php echo $this->form->getElement('status'); ?>
            </div>
            <div class="control-group span6">
                <?php echo $this->form->getElement('bank_payment'); ?>
            </div>
        </div>
    	
        <?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    
    <?php $this->placeholder('form')->captureEnd(); ?>
        
    <?php echo $this->form($this->form->getId(), $this->form->getAttribs(), $this->placeholder('form')); ?>
</div>

<div class="row-fluid" id="report-iframe"></div>