<div class="box-content">
    <?php $this->placeholder('form')->captureStart(); ?>
    
        <?php foreach($this->form->getElements() as $element): ?>
            <?php if ($element instanceof Zend_Form_Element_Hidden): ?>
                <?php echo $element; ?>
            <?php endif; ?>
        <?php endforeach; ?>
    
    	<div class="row-fluid">
			<div class="span6">
				<?php echo $this->form->getElement( 'id_fefop_programs' ); ?>
			</div>
			<div class="span6">
				<?php echo $this->form->getElement( 'fk_id_fefop_modules' ); ?>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6">
				<?php echo $this->form->getElement( 'fk_id_user_inserted' ); ?>
			</div>
			<div class="span6">
				<?php echo $this->form->getElement( 'fk_id_user_removed' ); ?>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6">
				<?php echo $this->form->getElement( 'status' ); ?>
			</div>
			<div class="span6">
				<?php echo $this->form->getElement( 'type_beneficiary' ); ?>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6">
				<?php echo $this->form->getElement( 'date_registration_fim' ); ?>
			</div>
			<div class="span6">
				<?php echo $this->form->getElement( 'date_registration_fim' ); ?>
			</div>
		</div>
        
    	<div class="row-fluid">
    		<div class="form-actions">
                <input id="save" class="btn blue" type="submit" value="Haree Relatoriu" name="save">
                <input id="clear" class="btn green" type="reset" value="Hamoos" name="clear">
            </div>
    	</div>
    	
    	<?php echo $this->form->getDisplayGroup('toolbar'); ?>
    	
	<?php $this->placeholder('form')->captureEnd(); ?>
	
	<?php echo $this->form($this->form->getId(), $this->form->getAttribs(), $this->placeholder('form')); ?>
</div>

<div class="row-fluid" id="report-iframe"></div>