<div class="box-content">
    <?php $this->placeholder('form')->captureStart(); ?>
    
        <?php foreach($this->form->getElements() as $element): ?>
            <?php if ($element instanceof Zend_Form_Element_Hidden): ?>
                <?php echo $element; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        
        <div class="row-fluid">
    		<div class="control-group span3">
                <?php echo $this->form->getElement('date_start'); ?>
            </div>
    		<div class="control-group span3">
                <?php echo $this->form->getElement('date_finish'); ?>
            </div>
            <div class="control-group span3">
                <?php echo $this->form->getElement('fk_id_dec'); ?>
            </div>
            <div class="control-group span3">
                <?php echo $this->form->getElement('id_beneficiary'); ?>
            </div>
        </div>
        
        <div class="row-fluid">
            <div class="control-group span3">
                <?php echo $this->form->getElement('id_fefop_programs'); ?>
            </div>
            <div class="control-group span3">
                <?php echo $this->form->getElement('id_fefop_modules'); ?>
            </div>
            <div class="control-group span3">
                <?php echo $this->form->getElement('id_adddistrict'); ?>
            </div>
            <div class="control-group span3">
                <?php echo $this->form->getElement('id_fefop_status'); ?>
            </div>
    	</div>
    	
        <?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    
    <?php $this->placeholder('form')->captureEnd(); ?>
        
    <?php echo $this->form($this->form->getId(), $this->form->getAttribs(), $this->placeholder('form')); ?>
</div>

<div class="row-fluid" id="report-iframe"></div>