<div class="filters">
    <p><?php echo $this->filterReport($this->data['filters']); ?></p>
</div>

<?php if (!empty($this->data['rows'])): ?>
	<table class="relatorio">
	    <thead>
	    	<tr>
	    	    <th>Komponente</th>
			    <th>Rúbrica</th>
			    <th>Total</th>
	    	</tr>
	    </thead>
	    <tbody>
	    	<?php foreach ($this->data['rows'] as $row) : ?>
	    	    <tr class="<?php echo $this->cycle(array('one', 'two'))->next(); ?>">
	        		<td><?php echo $row['category_type']; ?></td>
	        		<td><?php echo $row['category']; ?></td>
	        		<td><?php echo $this->currency($row['amount']); ?></td>
	    	    </tr>
	    	<?php endforeach; ?>
	    </tbody>
	    <tfoot>
	        <tr>
	    	    <th colspan="2"></th>
	    	    <th>
	                <?php 
	                    echo $this->currency(array_sum(array_map(function($item){return App_General_String::toFloat($item['amount']);}, $this->data['rows']))); 
	                ?>
	            </th>
	    	</tr>
	    	<tr>
	    	    <th colspan="2">Total</th>
	    	    <th><?php echo count($this->data['rows']); ?></th>
	    	</tr>
	    </tfoot>
	</table>
<?php endif; ?>