<div class="filters">
    <p><?php echo $this->filterReport($this->data['filters']); ?></p>
</div>

<table class="relatorio">
    <thead>
    	<tr>
    		<th>Data</th>
    		<th>T/P</th>
    		<th>Komponente</th>
    		<th>Rúbrica</th>
		    <th>Kontratu</th>
		    <th>Programa</th>
		    <th>Modulu</th>
		    <th>Status</th>
		    <th>Total</th>
    	</tr>
    </thead>
    <tbody>
    	<?php foreach ($this->data['rows'] as $row) : ?>
    	    <tr class="<?php echo $this->cycle(array('one', 'two'))->next(); ?>">
    	    	<td><?php echo $this->date($row['date_inserted']); ?></td>
    	    	<td><?php echo $row['code_transaction']; ?></td>
    	    	<td><?php echo empty($row['component']) ? 'N/A' : ucwords(strtolower($row['component'])); ?></td>
    	    	<td><?php echo ucwords(strtolower($row['expense'])); ?></td>
        		<td><?php echo $row['code_contract']; ?></td>
        		<td><?php echo $row['program']; ?></td>
        		<td><?php echo $row['module']; ?></td>
        		<td><?php echo $row['status_contract']; ?></td>
        		<td><?php echo $this->currency($row['amount'] * (('C' == $row['code_transaction']) ? -1 : 1)); ?></td>
    	    </tr>
    	<?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
    	    <th colspan="8"></th>
    	    <th><?php echo $this->currency(array_sum(array_map(function($item){return App_General_String::toFloat($item['amount'] * (('C' == $item['code_transaction']) ? -1 : 1));}, $this->data['rows']))); ?></th>
    	</tr>
    	<tr>
    	    <th colspan="8">Total</th>
    	    <th><?php echo count($this->data['rows']); ?></th>
    	</tr>
    </tfoot>
</table>