<div class="filters">
    <p><?php echo $this->filterReport($this->data['filters']); ?></p>
</div>

<?php if (!empty($this->data['item'])): ?>
    <table class="relatorio">
        <thead>
        	<tr>
        	    <!-- <th rowspan="3"> --> <th>Kontratu</th>
    		    <!-- <th rowspan="3"> --> <th>Benefisiariu</th>
    		    <!-- <th rowspan="3"> --> <th>Status</th>
    		    <!-- <th rowspan="3"> --> <th>Program</th>
    		    <!-- <th rowspan="3"> --> <th>Module</th>
    		    <th colspan="<?php echo array_sum(array_map(function($fund){ return count($fund); }, $this->data['item']['fund'])) + 1; ?>">Financiamento dos Custos Acrescidos</th>
        	</tr>
        	
        	<?php if (!empty($this->data['item']['fund'])): ?>
            	<tr>
            	   <th></th>
            	   <th></th>
            	   <th></th>
            	   <th></th>
            	   <th></th>
            	   <?php foreach (array_keys($this->data['item']['fund']) as $type): ?>
            	       <?php if (!empty($this->data['item']['fund'][$type])): ?>
            	           <th colspan="<?php echo count($this->data['item']['fund'][$type]);?>">
            	               <?php
            	               		switch ($type) {
										case 'D':
											echo 'Donor';
											break;

										case 'G': 
											echo 'Government';
											break;
											
										default:
											echo 'N/A';
									}
            	               ?>
        	               </th>
    	               <?php endif; ?>
        	       <?php endforeach; ?>
        	       
        	       <!-- <th rowspan="2"> --> <th>Total</th>
            	</tr>
            	
            	<tr>
            	   <th></th>
            	   <th></th>
            	   <th></th>
            	   <th></th>
            	   <th></th>
            	   <?php foreach ($this->data['item']['fund'] as $fund): ?>
            	       <?php foreach ($fund as $value): ?>
            	           <th><?php echo $value; ?></th>
            	       <?php endforeach; ?>
            	   <?php endforeach; ?>
            	   <th></th>
            	</tr>
            	
        	<?php endif; ?>
        </thead>
        <tbody>
        	<?php foreach ($this->data['item']['contract'] as $contract): ?>
        	    <tr class="<?php echo $this->cycle(array('one', 'two'))->next(); ?>">
            		<td><?php echo $contract['contract']; ?></td>
            		<td><?php echo $contract['beneficiary']; ?></td>
            		<td><?php echo $contract['status']; ?></td>
            		<td><?php echo $contract['program']; ?></td>
            		<td><?php echo $contract['module']; ?></td>
            		
            		<?php foreach ($this->data['item']['fund'] as $fund): ?>
                        <?php foreach (array_keys($fund) as $key): ?>
                            <td>
                                <?php if (!empty($contract['fund'][$key])): ?>
                                    <?php echo $this->currency($contract['fund'][$key]); ?> 
                                <?php endif; ?>
                            </td>
                        <?php endforeach; ?>
            		<?php endforeach; ?>
            		
            		<td><?php echo $this->currency(array_sum($contract['fund'])); ?></td>
        	    </tr>
        	<?php endforeach; ?>
        </tbody>
        <tfoot>
        	<tr>
        		<th colspan="5"></th>
        		<?php foreach ($this->data['item']['total'] as $total): ?>
        			<th><?php echo $this->currency($total); ?></th>
        		<?php endforeach; ?>
        		<th><?php echo $this->currency(array_sum($this->data['item']['total'])); ?></th>
        	</tr>
        	<tr>
        	    <th colspan="<?php echo array_sum(array_map(function($fund){ return count($fund); }, $this->data['item']['fund'])) + 5; ?>">Total</th>
        	    <th><?php echo count($this->data['item']['contract']); ?></th>
        	</tr>
        </tfoot>
    </table>
<?php endif; ?>