<div class="box-content">
    <?php $this->placeholder('form')->captureStart(); ?>
    
        <?php foreach($this->form->getElements() as $element): ?>
            <?php if ($element instanceof Zend_Form_Element_Hidden): ?>
                <?php echo $element; ?>
            <?php endif; ?>
        <?php endforeach; ?>

		<div class="row-fluid">
			<div class="span6">
				<?php echo $this->form->getElement( 'fk_id_fefop_status' ); ?>
		    </div>
			<div class="span6">
				<div class="control-group">
					<label class="control-label optional margin-bottom-10-">Kustu total</label>
					<div class="controls">
						<div id="slider-amount" class="slider bg-blue"></div>
						<div class="slider-value">
							Kustu: 
							<span id="slider-age-amount">
                                <?php echo $this->currency(0) . ' - ' . $this->currency(50000); ?>
                            </span>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span3">
				<?php echo $this->form->getElement( 'fk_id_fefop_programs' ); ?>
		    </div>
			<div class="span2">
				<?php echo $this->form->getElement( 'fk_id_fefop_modules' ); ?>
		    </div>
			<div class="span2">
				<?php echo $this->form->getElement( 'num_district' ); ?>
		    </div>
			<div class="span2">
				<?php echo $this->form->getElement( 'num_year' ); ?>
		    </div>
			<div class="span3">
				<?php echo $this->form->getElement( 'num_sequence' ); ?>
		    </div>
		</div>
		<div class="row-fluid">
    		<div class="form-actions">
                <input id="save" class="btn blue" type="submit" value="Haree Relatoriu" name="save">
                <input id="clear" class="btn green" type="reset" value="Hamoos" name="clear">
            </div>
    	</div>

    	
        <?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    
    <?php $this->placeholder('form')->captureEnd(); ?>
        
    <?php echo $this->form($this->form->getId(), $this->form->getAttribs(), $this->placeholder('form')); ?>
</div>

<div class="row-fluid" id="report-iframe"></div>