<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_drh_contract' );
    echo $this->form->getElement( 'fk_id_drh_trainingplan' );
    echo $this->form->getElement( 'fk_id_fefop_contract' );
    echo $this->form->getElement( 'fk_id_drh_beneficiary' );
    echo $this->form->getElement( 'fk_id_perdata' );
 ?>

    <?php echo $this->fefopContract()->getMessages(); ?>

    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span5">
		    <?php echo $this->form->getElement( 'num_training_plan' ); ?>
		</div>
		<div class="span1">
		    <div class="control-group">
			<label class="control-label">&#160;</label>
			<div class="controls">
			    <button type="button" id="btn-search-planning" class="btn green" title="Buka Planeamentu" onclick="Fefop.DRHContract.searchPlanning()">
				 <i class="icon-search"></i>  
			     </button>
			</div>
		    </div>
		</div>
		<div class="span1">
		    <div class="control-group">
			<label class="control-label">&#160;</label>
			<div class="controls">
			    <button type="button" id="btn-export-contract" disabled="disabled" 
				    class="btn green" title="Exporta Kontratu" onclick="Fefop.DRHContract.exportContract()">
				 <i class="icon-print"></i>  
			     </button>
			</div>
		    </div>
		</div>
		<div class="span5">
		    <?php echo $this->form->getElement( 'modality' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'scholarity_area' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'ocupation_name_timor' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'country' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'city' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span4">
		    <?php echo $this->form->getElement( 'date_start' ); ?>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'date_finish' ); ?>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'duration_days' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_adddistrict' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'entity' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'training_provider' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'beneficiary' ); ?>
		</div>
	    </div>
	    
	    <div class="row-fluid">
		<div class="span12">
		    <div class="portlet box blue ">
			<div class="portlet-title">
			    <div class="caption"><i class="icon-dollar"></i>Finansiamentu</div>
			    <div class="tools"><a href="javascript:;" class="collapse"></a></div>
			</div>
			<div class="portlet-body form">
			    <table class="table table-striped table-bordered table-hover table-full-width" id="expense-list">
				<thead>
				    <tr>
					<th style="width: 7%">#</th>
					<th>Komponente</th>			
					<th style="width: 15%">Folin Hira</th>
				    </tr>
				</thead>
				<tbody>
				    <?php 
					$count = 'A';
					foreach ( $this->expenses as $expense ) : 
				    ?>
					<tr>
					    <td><?php echo $count++; ?>.</td>
					    <td><?php echo $expense->description; ?></td>
					    <td>
						<div class="control-group">
						    <div class="controls">
							<?php
							    $attribsText = array(
								'class'	    => 'm-wrap span12 focused required cost-expense submit-field money-mask',
								'id'	    => 'total_expense_' . $expense->id_budget_category
							    );

							    $amount = null;
							    if ( !empty( $expense->amount ) )
								$amount = number_format( $expense->amount, 2, '.', '.' );

							    echo $this->formText( 'expense[' . $expense->id_budget_category . ']', $amount, $attribsText );  
							 ?>
						    </div>
						</div>
					    </td>
					</tr>
				    <?php endforeach; ?>
				</tbody>
			    </table>
			</div>
		    </div>
		</div>
	    </div>
	    
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>