<h4 class="bold">Benefisiariu Sira</h4>
<hr/>

<?php if ( $this->beneficiaries->count() < 1 ) : ?>
    <div class="alert alert-error not-remove">
	Plano Formasaun ne'e la iha benefisiariu ba halo kontratu.
    </div>
<?php endif; ?>

<?php foreach ( $this->beneficiaries as $beneficiary ) : ?>
    <div class="row-fluid contract">
        <div class="span12">
    	<div class="portlet box blue ">
    	    <div class="portlet-title">
    		<div class="caption"><i class="icon-user"></i><?php echo $beneficiary->staff_name; ?></div>
    		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
    	    </div>
    	    <div class="portlet-body form">

    		<input type="hidden" name="beneficiary[<?php echo $beneficiary->id_drh_beneficiary; ?>]" value="<?php echo $beneficiary->id_drh_beneficiary; ?>" />
    		<input type="hidden" name="unit_cost[<?php echo $beneficiary->id_drh_beneficiary; ?>]" value="<?php echo $beneficiary->final_cost; ?>" />
    		<input type="hidden" name="training_fund[<?php echo $beneficiary->id_drh_beneficiary; ?>]" value="<?php echo $beneficiary->training_fund; ?>" />

		<div class="row-fluid">
		    <div class="span12">
    			<div class="control-group">
    			    <label class="control-label required" for="training_provider">Entidade responsável</label>
    			    <div class="controls">
    				<input type="text" readonly="" class="m-wrap span12" value="<?php echo $beneficiary->institution; ?>" id="training_provider" name="training_provider">
    			    </div>
    			</div>		
    		    </div>
		</div>
    		<div class="row-fluid">
    		    <div class="span4">
    			<div class="control-group"><label class="control-label required" for="date_start">Loron Inisiu</label>
    			    <div class="controls">
    				<input name="date_start[<?php echo $beneficiary->id_drh_beneficiary; ?>]" type="text"
    				       class="m-wrap span12 date-mask" maxlength="10" value="<?php echo $this->date( $this->training_plan->date_start ); ?>" id="date_start">
    			    </div>
    			</div>		
    		    </div>
    		    <div class="span4">
    			<div class="control-group"><label class="control-label required" for="date_finish">Loron Remata</label>
    			    <div class="controls">
    				<input name="date_finish[<?php echo $beneficiary->id_drh_beneficiary; ?>]" type="text"
    				       class="m-wrap span12 date-mask" maxlength="10" value="<?php echo $this->date( $this->training_plan->date_finish ); ?>" id="date_finish">
    			    </div>
    			</div>		
    		    </div>
    		    <div class="span4">
    			<div class="control-group"><label class="control-label required" for="duration_days">Loron hira</label>
    			    <div class="controls">
    				<input name="duration_days[<?php echo $beneficiary->id_drh_beneficiary; ?>]" 
    				       type="text" readonly="" class="m-wrap span12" value="<?php echo $this->training_plan->duration_days; ?>" id="duration_days">
    			    </div>
    			</div>	
    		    </div>
    		</div>
		
		<div class="row-fluid">
		    <div class="span12">
			<div class="portlet box red ">
			    <div class="portlet-title">
				<div class="caption"><i class="icon-dollar"></i>Finansiamentu</div>
				<div class="tools"><a href="javascript:;" class="collapse"></a></div>
			    </div>
			    <div class="portlet-body form">
				<table class="table table-striped table-bordered table-hover table-full-width" id="expense-list">
				    <thead>
					<tr>
					    <th style="width: 7%">#</th>
					    <th>Komponente</th>			
					    <th style="width: 15%">Folin Hira</th>
					</tr>
				    </thead>
				    <tbody>
					<?php 
					    $count = 'A';
					    foreach ( $this->expenses as $key => $expense ) : 
					?>
					    <tr>
						<td><?php echo $count++; ?>.</td>
						<td><?php echo $expense->description; ?></td>
						<td>
						    <div class="control-group">
							<div class="controls">
							    <?php
								$attribsText = array(
								    'class'	    => 'm-wrap span12 focused required cost-expense submit-field money-mask',
								    'id'	    => 'total_expense_' . $expense->id_budget_category
								);

								$amount = null;
								
								if ( $key == 0 && !empty( $beneficiary->training_fund ) )
								    $amount = number_format( $beneficiary->training_fund, 2, '.', ',' );
								
								if ( $key == 1 && !empty( $beneficiary->final_cost ) )
								    $amount = number_format( $beneficiary->final_cost, 2, '.', ',' );

								echo $this->formText( 'expense[' . $beneficiary->id_drh_beneficiary . '][' . $expense->id_budget_category . ']', $amount, $attribsText );  
							     ?>
							</div>
						    </div>
						</td>
					    </tr>
					<?php endforeach; ?>
				    </tbody>
				</table>
			    </div>
			</div>
		    </div>
		</div>

    	    </div>
    	</div>
        </div>
    </div>
<?php endforeach; ?>