<div class="row-fluid">
    <table class="table table-striped table-bordered table-hover table-full-width" id="incoming-list">
	<thead>
	    <tr>
		<th>Kontatu</th>
		<th>Tipu</th>
		<th>Telemóvel</th>
		<th>Data</th>
		<th style="width: 50%">Messaje</th>
	    </tr>
	</thead>
	<tbody>
	    <?php foreach ( $this->rows as $row ) : ?>
		<tr>
		    <td><?php echo $row->contact; ?></td>
		    <td><?php echo $row->type; ?></td>
		    <td><?php echo App_General_String::cleanFone( $row->source ); ?></td>
		    <td><?php echo $this->date( $row->date_time, 'dd/MM/yyyy HH:mm' ); ?></td>
		    <td><?php echo $row->content; ?></td>
		</tr>
	    <?php endforeach; ?>
	</tbody>
    </table>
</div>