<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-search"></i>Buka Kampanha SMS</div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<?php
		    $this->placeholder( 'form' )->captureStart();
		?>

		    <div class="box-content">
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'campaign_title' ); ?>
			    </div>
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_department' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_campaign_type' ); ?>
			    </div>
			    <div class="span6">
				<?php echo $this->form->getElement( 'status' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="control-group span12">
				<label class="control-label">Grupu</label>
				<div class="container-checkbox"><?php echo $this->form->getElement( 'group' ); ?></div>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="form-actions">
				<button class="btn blue">Buka <i class="icon-search m-icon-white"></i></button>
				<button class="btn green" type="reset" id="clear">Hamoos <i class="icon-trash m-icon-white"></i></button>
			    </div>
			</div>
		    </div>
		
		<?php
		    $this->placeholder( 'form' )->captureEnd();
		    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
		?>
	    </div>
	</div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Buka Kampanha</div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="campaign-list">
		    <thead>
			<tr>
			    <th style="width: 25%">Kampanha</th>
			    <th>Departamentu</th>
			    <th>Tipu</th>
			    <th style="width: 8%">Enviu</th>
			    <th style="width: 8%">Haruka</th>
			    <th style="width: 8%">Hein</th>
			    <th>Status</th>
			    <th>Action</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>