<div class="row-fluid">
    <table class="table table-striped table-bordered table-hover table-full-width" id="log-list">
	<thead>
	    <tr>
		<th style="width: 80%">Log</th>
		<th>Data</th>
	    </tr>
	</thead>
	<tbody>
	    <?php foreach ( $this->rows as $row ) : ?>
		<tr>
		    <td><?php echo $row->campaign_log; ?></td>
		    <td><?php echo $this->date( $row->date_time, 'dd/MM/yyyy HH:mm' ); ?></td>
		</tr>
	    <?php endforeach; ?>
	</tbody>
    </table>
</div>