<div class="row-fluid">
    <div class="span12">
	<div class="portlet">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-dashboard"></i>Estatistika</div>
	    </div>
	    <div class="portlet-body form">
		<div class="row-fluid" id="indicators">
		    <div class="span3 responsive to-send" data-tablet="span6" data-desktop="span3">
			<div class="dashboard-stat blue">
			    <div class="visual">
				<i class="icon-upload-alt"></i>
			    </div>
			    <div class="details">
				<div class="number">
				    0
				</div>
				<div class="desc">                           
				    Haruka Hira
				</div>
			    </div>
			</div>
		    </div>
		    <div class="span3 responsive sent" data-tablet="span6" data-desktop="span3">
			<div class="dashboard-stat green">
			    <div class="visual">
				<i class="icon-signout"></i>
			    </div>
			    <div class="details">
				<div class="number">0</div>
				<div class="desc">Haruka tiha ona</div>
			    </div>                 
			</div>
		    </div>
		    <div class="span3 responsive waiting" data-tablet="span6  fix-offset" data-desktop="span3">
			<div class="dashboard-stat yellow">
			    <div class="visual">
				<i class="icon-time"></i>
			    </div>
			    <div class="details">
				<div class="number">0</div>
				<div class="desc">Hein atu aruka</div>
			    </div>               
			</div>
		    </div>
		    <div class="span3 responsive sent-error" data-tablet="span6" data-desktop="span3">
			<div class="dashboard-stat red">
			    <div class="visual">
				<i class="icon-warning-sign"></i>
			    </div>
			    <div class="details">
				<div class="number">0</div>
				<div class="desc">Sala</div>
			    </div>             
			</div>
		    </div>
		</div>
	    </div>
	</div>
    </div>
</div>

<div class="row-fluid">
    <div class="span6">
	<!-- BEGIN Portlet PORTLET-->
	<div class="portlet box blue">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-bar-chart"></i>Haruka tiha ona / Hein atu haruka</div>
		<div class="tools">
		    <a href="javascript:;" class="collapse"></a>
		</div>
	    </div>
	    <div class="portlet-body">
		<div id="graph-sending" class="graph-container"></div>
	    </div>
	</div>
	<!-- END Portlet PORTLET-->
    </div>
    <div class="span6">
	<!-- BEGIN Portlet PORTLET-->
	<div class="portlet box purple">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-bar-chart"></i>Haruka husi loron</div>
		<div class="tools">
		    <a href="javascript:;" class="collapse"></a>
		</div>
	    </div>
	    <div class="portlet-body">
		<div id="graph-sent-day" class="graph-container"></div>
	    </div>
	</div>
	<!-- END Portlet PORTLET-->
    </div>
</div>
<div class="row-fluid">
    <div class="span6">
	<!-- BEGIN Portlet PORTLET-->
	<div class="portlet box red">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-bar-chart"></i>Haruka husi ora</div>
		<div class="tools">
		    <a href="javascript:;" class="collapse"></a>
		</div>
	    </div>
	    <div class="portlet-body">
		<div id="graph-sent-hour" class="graph-container"></div>
	    </div>
	</div>
	<!-- END Portlet PORTLET-->
    </div>
    <div class="span6">
	<!-- BEGIN Portlet PORTLET-->
	<div class="portlet box yellow">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-bar-chart"></i>Haruka husi grupu</div>
		<div class="tools">
		    <a href="javascript:;" class="collapse"></a>
		</div>
	    </div>
	    <div class="portlet-body">
		<div id="graph-sent-group" class="graph-container"></div>
	    </div>
	</div>
	<!-- END Portlet PORTLET-->
    </div>
</div>