<div class="portlet">
	<div class="portlet-title">
	    <div class="caption"><i class="icon-info"></i>Deskrisaun Vaga</div>
	</div>
	<div class="portlet-body well" style="padding: 5px">
	    <div class="row-fluid">
		<div class="span6">
		    <div class="control-group">
			<label class="control-label">Titulu Vaga Empregu:</label>
			<div class="controls">
			    <span class="text bold">
				<?php echo $this->vacancy->vacancy_titule; ?>
			    </span>
			</div>
		    </div>
		</div>
		<div class="span4">
		    <div class="control-group">
			<label class="control-label">Empreza:</label>
			<div class="controls">
			    <span class="text bold">
				<?php echo $this->vacancy->enterprise_name; ?>
			    </span>
			</div>
		    </div>
		</div>
		<div class="span2">
		    <div class="control-group">
			<label class="control-label">Kodigu:</label>
			<div class="controls">
			    <span class="text bold">
				<?php echo str_pad( $this->vacancy->id_jobvacancy, 5, 0, STR_PAD_LEFT ); ?>
			    </span>
			</div>
		    </div>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span3">
		    <div class="control-group">
			<label class="control-label">Okupasaun:</label>
			<div class="controls">
			    <span class="text bold">
				<?php echo $this->vacancy->ocupation_name_timor; ?>
			    </span>
			</div>
		    </div>
		</div>
		<div class="span3">
		    <div class="control-group">
			<label class="control-label">CEOP:</label>
			<div class="controls">
			    <span class="text bold">
				<?php echo $this->vacancy->name_dec; ?>
			    </span>
			</div>
		    </div>
		</div>
		<div class="span4">
		    <div class="control-group">
			<label class="control-label">Data Loke:</label>
			<div class="controls">
			    <span class="text bold">
				<?php echo $this->vacancy->open_date_formated; ?>
			    </span>
			</div>
		    </div>
		</div>
		<div class="span2">
		    <div class="control-group">
			<label class="control-label">Data Taka:</label>
			<div class="controls">
			    <span class="text bold">
				<?php echo $this->vacancy->close_date_formated; ?>
			    </span>
			</div>
		    </div>
		</div>
	    </div>
	</div>
</div>

<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_jobvacancy' );
    echo $this->form->getElement( 'num_position' );
    echo $this->form->getElement( 'step' );
?>

<div class="row-fluid margin-bottom-25">
    <div class="span12 text-center">
	<a class="btn blue" href="<?php echo $this->baseUrl( '/job/vacancy/view/id/' . $this->id ); ?>">
	    <i class="m-icon-swapleft m-icon-white"></i>
	    Fila ba Vaga
	</a>
	<button class="btn green" <?php echo !$this->jobActive()->hasAccessEdit() ? 'disabled' : ''; ?> >
	    <i class="icon-off m-icon-white"></i>
	    Taka Vaga Emprego
	</button>
	<?php if ( $this->access( Job_Form_VacancyCancel::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
	    <button type="button" onClick="Job.Vacancy.cancelVacancy( <?php echo $this->id; ?> );" class="btn red" <?php echo !$this->jobActive()->hasAccessEdit() ? 'disabled' : ''; ?> >
		<i class="icon-remove-sign m-icon-white"></i>
		Kansela Vaga
	    </button>
	<?php endif; ?>
    </div>
</div>

<?php echo $this->jobActive()->getMessage(); ?>

<div class="row-fluid">
    <table class="table table-striped table-bordered table-hover table-full-width" id="shortlist-list">
	<thead>
	    <tr>
		<th style="width: 4%" class="no-sort">
		    <input type="checkbox" onClick="Job.Vacancy.checkAll( this );" />
		</th>
		<th style="width: 16%">Numeru</th>
		<th>Kliente</th>
		<th style="width: 11%" class="hidden-phone hidden-tablet">Data Moris</th>
		<th style="width: 3%" class="hidden-phone hidden-tablet">Idade</th>
		<th style="width: 13%">Hetan Serbisu</th>
		<th class="hidden-phone hidden-tablet">CEOP</th>
	    </tr>
	</thead>
	<tbody>
	    <?php foreach ( $this->rows as $row ) : ?>
		<tr>
		    <td style="width: 4%">
			<input type="checkbox" class="clients" <?php echo !empty( $row->hired ) ? 'disabled checked' : ''; ?>
			       onChange="Job.Vacancy.setCloseList( this );"  value="<?php echo $row->id_perdata; ?>" />
		    </td>
		    <td style="width: 16%"><?php echo Client_Model_Mapper_Client::buildNumRow( $row ); ?></td>
		    <td
			 <?php if ( $this->access( Client_Form_ClientInformation::ID) ) : ?>
			    <a href="<?php echo $this->baseUrl( '/client/client/print/id/' . $row->id_perdata ); ?>" target="_blank">
				<?php echo Client_Model_Mapper_Client::buildName( $row ); ?>
			    </a>
			<?php else : ?>
				<?php echo Client_Model_Mapper_Client::buildName( $row ); ?>
			<?php endif; ?>
		    </td>
		    <td style="width: 11%" class="hidden-phone hidden-tablet"><?php echo $row->birth_date_format; ?></td>
		    <td style="width: 2%" class="hidden-phone hidden-tablet"><?php echo $row->age; ?></td>
		    <td style="width: 13%">
			<span class="label label-<?php echo $row->hired ? 'success' : 'important'; ?>">
			    <?php echo $row->hired ? 'SIM' : 'LAE'; ?>
			</span>
		    </td>
		    <td class="hidden-phone hidden-tablet"><?php echo $row->name_dec; ?></td>
		</tr>
	    <?php endforeach; ?>
	</tbody>
    </table>
</div>

<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>