<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_jobvacancy' );
    echo $this->form->getElement( 'id_handicapped' );
    echo $this->form->getElement( 'step' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span6">
		    <div class="row-fluid">
			<?php echo $this->form->getElement( 'fk_id_typehandicapped' ); ?>
		    </div>
		    <div class="row-fluid">
			<?php echo $this->form->getElement( 'handicapped' ); ?>
		    </div>
		    <div class="row-fluid">
			<?php echo $this->form->getElement( 'needs' ); ?>
		    </div>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'details' ); ?>
		</div>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Defisiensia Sira</div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="handicapped-list">
		    <thead>
			<tr>
			    <th>Tipu Defisiensia</th>
			    <th>Defisiensia</th>
			    <th>Nesesidade Especial</th>
			    <th>Action</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>