<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-search"></i>Buka Vaga Empregu</div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<?php
		    $this->placeholder( 'form' )->captureStart();
		?>

		    <div class="box-content">
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'vacancy_titule' ); ?>
			    </div>
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_dec' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_profocupation' ); ?>
			    </div>
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_fefpenterprise' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'active' ); ?>
			    </div>
			    <div class="span6">
				<div class="span6">
				    <?php echo $this->form->getElement( 'open_date' ); ?>
				</div>
				<div class="span6">
				    <?php echo $this->form->getElement( 'close_date' ); ?>
				</div>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="form-actions">
				<button class="btn blue">Buka <i class="icon-search m-icon-white"></i></button>
				<button class="btn green" type="reset" id="clear">Hamoos <i class="icon-trash m-icon-white"></i></button>
			    </div>
			</div>
		    </div>
		
		<?php
		    $this->placeholder( 'form' )->captureEnd();
		    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
		?>
	    </div>
	</div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Buka Vaga</div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="vacancy-list">
		    <thead>
			<tr>
			    <th class="hidden-tablet hidden-phone" style="width: 7%">Kodigu</th>
			    <th style="width: 12%">Titulu</th>
			    <th>Empreza</th>
			    <th style="width: 22%">Okupasaun</th>
			    <th class="hidden-tablet hidden-phone date-column" style="width: 6%">Loke</th>
			    <th class="hidden-tablet hidden-phone date-column" style="width: 6%">Taka</th>
			    <th style="width: 7%">Status</th>
			    <th style="width: 10%">Action</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>