<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->type_handicapped; ?></td>
	<td><?php echo $row->handicapped; ?></td>
	<td><?php echo $row->needs; ?></td>
	<td>
	    <?php if ( $this->jobActive()->hasAccessEdit() && $this->access( Job_Form_VacancyHandicapped::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
		<a class="btn green" data-handicapped='<?php echo $row->id_handicapped; ?>' onclick="Job.Vacancy.editHandicapped( this );">
		    <i class="icon-edit"></i>              
		</a>
		<a class="btn red" data-handicapped='<?php echo $row->id_handicapped; ?>' onclick="Job.Vacancy.removeHandicapped( this );">
		    <i class="icon-remove-sign"></i>            
		</a>
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>  
		    La bele acessu                                            
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>