<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->country; ?></td>
	<td><?php echo $row->District; ?></td>
	<td><?php echo $row->sub_district; ?></td>
	<td>
	    <?php if ( $this->jobActive()->hasAccessEdit() && $this->access( Job_Form_VacancyAddress::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
		<a class="btn red" data-address='<?php echo $row->id_relationship; ?>' onclick="Job.Vacancy.removeAddress( this );">
		    <i class="icon-remove-sign"></i>            
		</a>
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>  
		    La bele acessu                                            
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>