<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_jobvacancy' );
    echo $this->form->getElement( 'step' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'category' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_perscholarity' ); ?>
		</div>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Nivel Eskola Sira</div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="scholarity-list">
		    <thead>
			<tr>
			    <th style="width: 20%">Kategoria</th>
			    <th>Kursu</th>
			    <th>Titulu</th>
			    <th style="width: 9%">Action</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>