<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td class="hidden-tablet hidden-phone"><?php echo $row->id_jobvacancy; ?></td>
	<td><?php echo $row->vacancy_titule; ?></td>
	<td><?php echo $row->enterprise_name; ?></td>
	<td><?php echo $row->ocupation_name_timor; ?></td>
	<td class="hidden-tablet hidden-phone"><?php echo $row->open_date_formated; ?></td>
	<td class="hidden-tablet hidden-phone"><?php echo $row->close_date_formated; ?></td>
	<td>
	    <?php 
		if ( $row->active == 1 ) {
		    
		    if ( $row->expired ) {
			
			$label = 'warning';
			$status = 'Expirado';
		    
		    } else {
			
			$label = 'success';
			$status = 'Loke';
		    }
		    
		} else {
		    
		    $label = 'important';
		    $status = ( $row->active == 2 ) ? 'Kansela' : 'Taka';	
		}
	    ?>
	    
	    <span class="label label-<?php echo $label; ?>">
		<?php echo $status; ?>
	    </span>
	</td>
	<td>
	    <?php if ( $this->access( Job_Form_VacancyInformation::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
	    
		<?php if ( empty( $this->listAjax ) ) : ?>
		    <a class="btn red-stripe" href="<?php echo $this->baseUrl( 'job/vacancy/view/id/' . $row->id_jobvacancy ); ?>">
			<i class="icon-eye-open"></i>  
			Haree                                            
		    </a>
		<?php else : ?>
	    
		    <a class="btn red-stripe" target="_blank" href="<?php echo $this->baseUrl( 'job/vacancy/print/id/' . $row->id_jobvacancy ); ?>">
			<i class="icon-eye-open"></i>                                     
		    </a>
		    
		    <?php if ( $row->active == 1 ) : ?>
			<a class="btn red action-ajax" href="javascript:;" data-id="<?php echo $row->id_jobvacancy; ?>">
			    <i class="icon-ok"></i>                                     
			</a>
		    <?php endif; ?>
	    
		<?php endif; ?>
	    
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>  
		    La bele acessu                                            
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>