<div class="row-fluid">
    <div class="span6">
	<div class="control-group">
	    <label class="control-label">Titulu Vaga Empregu:</label>
	    <div class="controls">
		<span class="text bold">
		    <?php echo $this->vacancy->vacancy_titule; ?>
		</span>
	    </div>
	</div>
    </div>
    <div class="span5">
	<div class="control-group">
	    <label class="control-label">Empreza:</label>
	    <div class="controls">
		<span class="text bold">
		    <?php echo $this->vacancy->enterprise_name; ?>
		</span>
	    </div>
	</div>
    </div>
    <div class="span1">
	<div class="control-group">
	    <label class="control-label">Kodigu:</label>
	    <div class="controls">
		<span class="text bold">
		    <?php echo str_pad( $this->vacancy->id_jobvacancy, 5, 0, STR_PAD_LEFT ); ?>
		</span>
	    </div>
	</div>
    </div>
</div>

<?php echo $this->jobActive()->getMessage(); ?>

<div class="row-fluid top-news button-dashboard">
    <div class="span12">
	<a href="<?php echo $this->baseUrl( '/job/vacancy/edit/id/' . $this->vacancy->id_jobvacancy ); ?>" class="btn green">
	    <span>Edita dados</span>
	    <i class="icon-edit top-news-icon"></i>                             
	</a>
    </div>
</div>
<div class="row-fluid top-news button-dashboard">
    <div class="span6">
	<a href="javascript:;" class="btn blue" onClick="Job.Vacancy.printJob( <?php echo $this->vacancy->id_jobvacancy; ?> );">
	    <span>Imprime vaga</span>
	    <i class="icon-print top-news-icon"></i>
	</a>
    </div>
    <div class="span6">
	<a href="<?php echo $this->baseUrl( '/job/match/index/id/' . $this->vacancy->id_jobvacancy ); ?>" class="btn yellow">
	    <span>Mediasaun Empregu</span>
	    <i class="icon-group top-news-icon"></i>                             
	</a>
    </div>
</div>
<div class="row-fluid top-news button-dashboard">
    <div class="span6">
	<a href="javascript:;" class="btn purple" onClick="Job.Vacancy.printShortlist( <?php echo $this->vacancy->id_jobvacancy; ?> );">
	    <span>Shortlist</span>
	    <i class="icon-list top-news-icon"></i>                             
	</a>
    </div>
    <div class="span6">
	<a href="<?php echo $this->baseUrl( '/job/vacancy/close/id/' . $this->vacancy->id_jobvacancy ); ?>" class="btn red">
	    <span>Taka Vaga</span>
	    <i class="icon-remove-sign top-news-icon"></i>                              
	</a>
    </div>
</div>
