<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-search"></i>Buka Empreza</div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<?php $this->placeholder( 'form' )->captureStart(); ?>

		    <div class="box-content">
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'enterprise_name' ); ?>
			    </div>
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_adddistrict' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_fefptypeenterprite' ); ?>
			    </div>
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_sectorindustry' ); ?>
			    </div>
			</div>
                        <div class="row-fluid">
                            <div class="span6">
                                <?php echo $this->form->getElement( 'fk_nationality' ); ?>
                            </div>
                            <div class="span6">
                                <?php echo $this->form->getElement( 'fk_id_dec' ); ?>
                            </div>
                        </div>
			<div class="row-fluid">
			    <div class="form-actions">
				<button class="btn blue">Buka <i class="icon-search m-icon-white"></i></button>
				<button class="btn green" type="reset" id="clear">Hamoos <i class="icon-trash m-icon-white"></i></button>
			    </div>
			</div>
		    </div>
		
		<?php
		    $this->placeholder( 'form' )->captureEnd();
		    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
		?>
	    </div>
	</div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Buka Empreza</div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="enterprise-list">
		    <thead>
			<tr>
			    <th>Empreza</th>
			    <th>Tipu Empreza</th>
			    <th>CEOP</th>
			    <th>Action</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>