<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->contact_name; ?></td>
	<td><?php echo $row->cell_fone; ?></td>
	<td><?php echo $row->email; ?></td>
	<td>
	    <?php if ( $this->access( Register_Form_EnterpriseContact::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
		<a class="btn green" data-contact='<?php echo $row->id_percontact; ?>' onclick="Register.Enterprise.editContact( this );">
		    <i class="icon-edit"></i>                       
		</a>
		<a class="btn red" data-contact='<?php echo $row->id_percontact; ?>' onclick="Register.Enterprise.removeContact( this );">
		    <i class="icon-remove-sign"></i>        
		</a>
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>  
		    La bele acessu                                            
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>