<div class="filters">
    <p><?php echo $this->filterReport( $this->data['filters'] ); ?></p>
</div>

<table class="relatorio">
    <thead>
	<tr>
	    <th>ID</th>
	    <th>Tipu Kursu</th>
	    <th>Naran Kursu</th>
	    <th>Area Kursu</th>
	    <th>Kategoria</th>
	    <th>Nivel</th>
	</tr>
    </thead>
    <tbody>
	<?php foreach ( $this->data['rows'] as $row ) : ?>
	    <tr class="<?php echo $this->cycle( array( 'one', 'two') )->next(); ?>">
		<td><?php echo $row->id_perscholarity; ?></td>
		<td><?php echo $row->type_scholarity; ?></td>
		<td><?php echo ( empty( $row->external_code ) ? '' : $row->external_code . ' - ' ) . $row->scholarity; ?></td>
		<td><?php echo $row->scholarity_area; ?></td>
		<td><?php echo $this->nomenclature()->scholarityCategory( $row->category ); ?></td>
		<td><?php echo empty( $row->level_scholarity ) ? '-' : $row->level_scholarity; ?></td>
	    </tr>
	<?php endforeach; ?>
    </tbody>
    <tfoot>
	<tr>
	    <th colspan="5">Total</th>
	    <th><?php echo count( $this->data['rows'] ); ?></th>
	</tr>
    </tfoot>
</table>