<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_isicclass' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="span6"><?php echo $this->form->getElement( 'fk_id_isicsection' ); ?></div>
	    <div class="span6"><?php echo $this->form->getElement( 'fk_id_isicdivision' ); ?></div>
	</div>
	<div class="row-fluid">
	    <div class="span6"><?php echo $this->form->getElement( 'fk_id_isicgroup' ); ?></div>
	    <div class="span6"><?php echo $this->form->getElement( 'name_class' ); ?></div>
	</div>
	<div class="row-fluid">
	    <div class="span6"><?php echo $this->form->getElement( 'acronym' ); ?></div>
	    <div class="span6"><?php echo $this->form->getElement( 'description' ); ?></div>
	</div>
	
	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>