<?php $this->placeholder( 'form' )->captureStart(); ?>
    <div class="row-fluid">
	<div class="row-fluid">
	    <div class="span6">
		<?php echo $this->form->getElement( 'fk_id_fefopfund' ); ?>
	    </div>
	    <div class="span6">
		<?php echo $this->form->getElement( 'year_planning' ); ?>
	    </div>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span12">
	    <div class="portlet box blue">
		<div class="portlet-title">
		    <div class="caption"><i class="icon-dollar"></i>Programa FEFOP</div>
		</div>
		<div class="portlet-body form">
		    <table class="table table-striped table-bordered table-hover table-full-width">
			<tbody>
			    <?php foreach ( $this->programs as $program => $modules ) : ?>
				<tr>
				    <th colspan='2'>
					<?php echo $modules['program']['num_program']; ?> - <?php echo $modules['program']['program']; ?>
				    </th>
				</tr>
				<?php foreach ( $modules['modules'] as $module ) : ?>
				    <tr>
					<td><?php echo $module->num_module; ?> - <?php echo $module->module; ?></td>
					<td>
					    <div class="control-group">
						<div class="controls">
						    <?php
							$attribsText = array(
							    'class'	    => 'm-wrap span12 focused cost-module required submit-field money-mask',
							    'id'	    => 'modules_cost_' . $module->num_module
							);

							echo $this->formText( 'modules_cost[' . $module->id_fefop_modules . ']', null, $attribsText );  
						     ?>
						</div>
					    </div>
					</td>
				    </tr>
				<?php endforeach; ?>
			    <?php endforeach; ?>
			    <tr>
				<th>Kusto Extra</th>
				<td><?php echo $this->form->getElement( 'additional_cost' ); ?></td>
			    </tr>   
			    <tr>
				<th>Total</th>
				<td><?php echo $this->form->getElement( 'amount' ); ?></td>
			    </tr>   
			</tbody>
		    </table>
		</div>
	    </div>
	</div>
    </div>

    <?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );