<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->type == 'G' ? 'Governo' : 'Doador'; ?></td>
	<td><?php echo $row->name_fund; ?></td>
	<td><?php echo $this->date( $row->register_date ); ?></td>
	<td>
	    <?php if ( $this->access( Fefop_Form_Fund::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
		<a class="btn green" href="<?php echo $this->baseUrl( 'fefop/fund/edit/id/' . $row->id_fefopfund ); ?>">
		    <i class="icon-edit"></i>  
		    Troka                                            
		</a>
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>  
		    La bele acessu                                            
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>