<?php $this->headScript()->appendFile( $this->baseUrl( 'public/scripts/controller/fefop/contract.js' ) );  ?>
<div class="row-fluid">
    <div class="span4">
	<fieldset>
	    <legend>Halo transasaun</legend>
	    <button type="button" onclick="Fefop.BankStatement.newStatement()" class="btn yellow">
		<i class="icon-file"></i>
		Transasaun Foun
	    </button>
	</fieldset>
    </div>
    <div class="span8">
	<fieldset>
	    <legend>Total</legend>
	    <div class="row-fluid">
		<div class="span4">
		    <div class="control-group">
			<label class="control-label">Saldo Atual</label>
			<div class="controls">
			    <span class="text bold totals total_current">
				0.00
			    </span>
			</div>
		    </div>
		</div>
		<div class="span4">
		    <div class="control-group">
			<label class="control-label">Total Consolidado</label>
			<div class="controls">
			    <span class="text bold totals total_consolidated">
				0.00
			    </span>
			</div>
		    </div>
		</div>
		<div class="span4">
		    <div class="control-group">
			<label class="control-label">Total iha <?php echo $this->date( $this->lastMonth ); ?></label>
			<div class="controls">
			    <span class="text bold totals total_last_month">
				0.00
			    </span>
			</div>
		    </div>
		</div>
	    </div>
	</fieldset>
    </div>
</div>

<hr />
<div class="row-fluid">
    <div class="span12">
	<div class="row-fluid">
	    <div class="span12">
		<div class="portlet box green ">
		    <div class="portlet-title">
			<div class="caption"><i class="icon-search"></i>Buka</div>
			<div class="tools"><a href="javascript:;" class="expand"></a></div>
		    </div>
		    <div class="portlet-body form hide">
			<?php $this->placeholder( 'form' )->captureStart();?>
			    <div class="box-content">
				<div class="row-fluid">
				    <div class="span6">
					<?php echo $this->formSearch->getElement( 'fk_id_fefop_type_transaction' ); ?>
				    </div>
				    <div class="span6">
					<?php echo $this->formSearch->getElement( 'fk_id_fefopfund' ); ?>
				    </div>
				</div>
				<div class="row-fluid">
				    <div class="span6">
					<?php echo $this->formSearch->getElement( 'fk_id_budget_category_type' ); ?>
				    </div>
				    <div class="span6">
					<?php echo $this->formSearch->getElement( 'fk_id_budget_category' ); ?>
				    </div>
				</div>
				<div class="row-fluid">
				    <div class="span4">
					<?php echo $this->formSearch->getElement( 'date_start' ); ?>
				    </div>
				    <div class="span4">
					<?php echo $this->formSearch->getElement( 'date_finish' ); ?>
				    </div>
				    <div class="span4">
					<?php echo $this->formSearch->getElement( 'status' ); ?>
				    </div>
				</div>
				<div class="row-fluid">
				    <div class="span4">
					<?php echo $this->formSearch->getElement( 'minimum_amount' ); ?>
				    </div>
				    <div class="span4">
					<?php echo $this->formSearch->getElement( 'maximum_amount' ); ?>
				    </div>
				    <div class="span4">
					<?php echo $this->formSearch->getElement( 'num_contract' ); ?>
				    </div>
				</div>
				<div class="row-fluid">
				    <div class="form-actions">
					<button class="btn blue">Buka <i class="icon-search m-icon-white"></i></button>
					<button class="btn green" type="reset" id="clear">Hamoos <i class="icon-trash m-icon-white"></i></button>
					<button onclick="Fefop.Contract.printGrid( '#statement-list' );" class="btn purple" type="button">Print <i class="icon-print m-icon-white"></i></button>
				    </div>
				</div>
			    </div>

			<?php
			    $this->placeholder( 'form' )->captureEnd();
			    echo $this->form( $this->formSearch->getId(), $this->formSearch->getAttribs(), $this->placeholder( 'form' ) );
			?>
		    </div>
		</div>
	    </div>
	</div>

	<div class="row-fluid">
	    <div class="span12">
		<div class="portlet box green ">
		    <div class="portlet-title">
			<div class="caption"><i class="icon-dollar"></i>Transasaun Hotu-Hotu</div>
			<div class="tools"><a href="javascript:;" class="collapse"></a></div>
		    </div>
		    <div class="portlet-body form">
			<table class="table table-striped table-bordered table-hover table-full-width" id="statement-list">
			    <thead>
				<tr>
				    <th style="width: 8%" class="no-sort">Consol.</th>
				    <th style="width: 8%" class="date-column">Data</th>
				    <th>Deskrisaun</th>
				    <th style="width: 13%">Valor</th>
				    <th style="width: 13%">Total</th>
				    <th style="width: 15%">Tipo Mov.</th>
				    <th>Fonte</th>
				    <th style="width: 5%" class="no-sort"></th>
				</tr>
			    </thead>
			    <tbody></tbody>
			</table>
		    </div>
		</div>
	    </div>
	</div>
    </div>
</div>