<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_fefop_bank_statements' );
    echo $this->form->getElement( 'status' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'date_statement' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'amount' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span4">
		    <?php echo $this->form->getElement( 'fk_id_fefop_type_transaction' ); ?>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'operation' ); ?>
		</div>
		<div class="span4 hide container">
		    <?php echo $this->form->getElement( 'fk_id_fefopfund' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span12">
		    <?php echo $this->form->getElement( 'description' ); ?>
		</div>
	    </div>	    
	</div>
	
	<div class="row-fluid <?php echo empty( $this->contracts ) ? 'hide' : ''; ?>">
	    <div class="span12">
		<div class="portlet box green ">
		    <div class="portlet-title">
			<div class="caption"><i class="icon-dollar"></i>Kontratu</div>
			<div class="actions">
			    <a href="javascript:;" class="btn blue" onclick="Fefop.BankStatement.searchContract();"> 
				<i class="icon-plus-sign"></i>
				Aumenta
			    </a>
			</div>
		    </div>
		    <div class="portlet-body form">
			<table class="table table-striped table-bordered table-hover table-full-width" id="contract-list">
			    <thead>
				<tr>
				    <th style="width: 5%"></th>
				    <th>Kontratu</th>
				    <th style="width: 20% !important">Total</th>			
				    <th style="width: 15%"></th>
				</tr>
			    </thead>
			    <tbody>
				<?php 
				    if ( !empty( $this->contracts ) ) :
					foreach ( $this->contracts as $contract ) :
					    echo $this->action( 'add-contract', 'bank-statement', 'fefop', array( 'row' => $contract ) );
					    foreach ( $contract['expenses'] as $expense ) :
						echo $this->action( 'add-expense', 'bank-statement', 'fefop', array( 'row' => $expense ) );
					    endforeach;
					endforeach;
				    endif;
				?>
			    </tbody>
			</table>
		    </div>
		</div>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>