<div class="box-content">
    <div class="row-fluid hide" id="info-class-list">
	<div class="alert alert-info">
	    <strong>
		Atensaun!
	    </strong> 
	    Job Training iha ne'e seidauk iha lista Kandidatu.
	</div>
    </div>

    <div class="row-fluid margin-bottom-25">
	<div class="span12 text-center">
	    <button class="btn red" type="button" <?php echo $this->jobTrainingActive()->hasAccessEdit() ? '' : 'disabled'; ?>
		    onclick="StudentClass.JobTraining.saveTrainee();">
		<i class="icon-list-alt m-icon-white"></i>
		Halot Partisipante
	    </button>
	</div>
    </div>
    <div class="row-fluid">
	<table class="table table-striped table-bordered table-hover table-full-width" id="candidate-list">
	    <thead>
		<tr>
		    <th style="width: 4%" class="no-sort">
			<input type="checkbox" onClick="General.checkAll( this );" />
		    </th>
		    <th style="width: 16%">Numeru</th>
		    <th>Kliente</th>
		    <th style="width: 3%" class="hidden-phone hidden-tablet">Rejistu</th>
		    <th style="width: 11%" class="hidden-phone hidden-tablet">Data Moris</th>
		    <th style="width: 3%" class="hidden-phone hidden-tablet">Idade</th>
		    <th style="width: 2%">Seksu</th>
		    <th class="hidden-phone hidden-tablet">CEOP</th>
		</tr>
	    </thead>
	    <tbody></tbody>
	</table>
    </div>

</div>