<div class="box-content">
    <div class="row-fluid hide" id="info-job-training-client">
	<div class="alert alert-info">
	    <strong>
		Atensaun!
	    </strong> 
	    Job Training ida ne'e seidauk iha Partisipante.
	</div>
    </div>
    <div class="row-fluid">
	<table class="table table-striped table-bordered table-hover table-full-width" id="client-list">
	    <thead>
		<tr>
		    <th style="width: 17%">Numeru</th>
		    <th style="width: 50%">Kliente</th>			
		    <th style="width: 17%">Seksu</th>			
		    <th>Remata</th>
		    <th>Kontratu</th>
		    <th>Kompletu</th>
		    <th class="no-sort">Asaun</th>
		</tr>
	    </thead>
	    <tbody></tbody>
	</table>
    </div>
</div>