<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_jobtraining' );
    echo $this->form->getElement( 'step' );
 ?>
    <div class="row-fluid">
	<div class="span6">
	    <?php echo $this->form->getElement( 'category' ); ?>
	</div>
	<div class="span6">
	    <?php echo $this->form->getElement( 'fk_id_perscholarity' ); ?>
	</div>
    </div>

    <?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box light-grey">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Kursu Sira</div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="course-list">
		    <thead>
			<tr>
			    <th>Kursu</th>
			    <th>Action</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>