<?php 
    $this->placeholder( 'form' )->captureStart();
 ?>
    <div class="box-content">
	
	<div class="row-fluid">
	    <div class="span12">
		<div class="portlet box blue">
		    <div class="portlet-title">
			<div class="caption"><i class="icon-search"></i> Buka Job Training</div>
			<div class="tools"><a class="collapse" href="javascript:;"></a></div>
		    </div>
		    <div class="portlet-body form">
	
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'title' ); ?>
			    </div>
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_dec' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_fefpenterprise' ); ?>
			    </div>
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_fefpeduinstitution' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span4">
				<?php echo $this->form->getElement( 'fk_id_perscholarity' ); ?>
			    </div>
			     <div class="span2">
				<?php echo $this->form->getElement( 'status' ); ?>
			    </div>
			    <div class="span3">
				<?php echo $this->form->getElement( 'date_start' ); ?>
			    </div>
			    <div class="span3">
				<?php echo $this->form->getElement( 'date_finish' ); ?>
			    </div>
			</div>

			<div class="row-fluid">
			    <div class="form-actions">
				<button class="btn blue">Buka <i class="icon-search m-icon-white"></i></button>
				<button class="btn green" type="reset" id="clear">Hamoos <i class="icon-trash m-icon-white"></i></button>
			    </div>
			</div>
		    </div>
		</div>
	    </div>
	</div>
	
	<div class="row-fluid">
	    <div class="span12">
		<div class="portlet box blue">
		    <div class="portlet-title">
			<div class="caption"><i class="icon-list"></i> Resultado Buka</div>
			<div class="tools"><a class="collapse" href="javascript:;"></a></div>
		    </div>
		    <div class="portlet-body form">
			<table class="table table-striped table-bordered table-hover table-full-width" id="job-training-list">
			    <thead>
				<tr>
				    <th style="width: 10%">ID</th>
				    <th>Titulu</th>
				    <th>Entidade</th>
				    <th>Area</th>
				    <th style="width: 10%">Posisaun Hira</th>
				    <th style="width: 10%" class="hidden-phone hidden-tablet">Status</th>
				    <th style="width: 15%">Action</th>
				</tr>
			    </thead>
			    <tbody></tbody>
			</table>
		    </div>
		</div>
	    </div>
	</div>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>