<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_jobtraining' );
    echo $this->form->getElement( 'source' );
 ?>
    <div class="box-content">
	
	<div class="row-fluid">
	    <div class="span6">
		<?php echo $this->form->getElement( 'fk_id_dec' ); ?>
	    </div>
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label" for="fk_id_dec">Numeru Rejistu</label>
		    <div class="controls">
			<?php 
			    echo $this->form->getElement( 'num_district' ); 
			    echo $this->form->getElement( 'num_subdistrict' ); 
			    echo $this->form->getElement( 'num_servicecode' ); 
			    echo $this->form->getElement( 'num_year' ); 
			    echo $this->form->getElement( 'num_sequence' ); 
			?>
		    </div>
		</div>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="span6">
		<?php echo $this->form->getElement( 'first_name' ); ?>
	    </div>
	    <div class="span6">
		<?php echo $this->form->getElement( 'last_name' ); ?>
	    </div>
	</div>
	
	<div class="row-fluid margin-bottom-25">
	    <div class="form-actions">
		<button class="btn blue">Buka <i class="icon-search m-icon-white"></i></button>
		<button class="btn green" type="reset" id="clear">Hamoos <i class="icon-trash m-icon-white"></i></button>
		<button <?php echo $this->jobTrainingActive()->hasAccessEdit( false ) ? '' : 'disabled'; ?>
		    class="btn red" type="button" onclick="StudentClass.JobTraining.addListCandidate( this );">
		    <i class="icon-list m-icon-white"></i>
		    Hili Kandidatu
		</button>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="span12">
		<div class="portlet box light-grey">
		    <div class="portlet-title">
			<div class="caption"><i class="icon-list"></i> Resultado Buka</div>
		    </div>
		    <div class="portlet-body form">
			<table class="table table-striped table-bordered table-hover table-full-width" id="match-list">
			    <thead>
				<tr>
				    <th style="width: 5%" class="no-sort">
					<input type="checkbox" onClick="General.checkAll( this );" />
				    </th>
				    <th style="width: 18%">Numeru</th>
				    <th style="width: 40%">Kliente</th>
				    <th class="hidden-phone hidden-tablet">Rejistu</th>
				    <th class="hidden-phone hidden-tablet">Data Moris</th>
				    <th class="hidden-phone hidden-tablet">Idade</th>
				    <th>Seksu</th>
				    <th class="hidden-phone hidden-tablet">CEOP</th>
				</tr>
			    </thead>
			    <tbody></tbody>
			</table>
		    </div>
		</div>
	    </div>
	</div>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>