<div class="form-actions no-print">
    <button type="button" class="btn blue" onClick="self.print();"><i class="icon-print"></i> Print</button>
    <button type="button" class="btn red" onClick="self.close();"><i class="icon-remove-sign"></i> Taka</button>
</div>

<?php echo $this->action( 'header-report', 'index', 'default', array( 'id' => $this->jobtraining->fk_id_dec ) ); ?>

<div class="form-view">
    
    <h4 class="form-section bold">
	Job Training: <?php echo str_pad( $this->jobtraining->id_jobtraining, 5, '0', STR_PAD_LEFT ); ?>
    </h4>
    
    <?php 
	
	$this->jobtraining->salary = (float)$this->jobtraining->salary;
	
	$dataJobTraining = array(
	    'Titulu'		    => $this->jobtraining->title,
	    'Entity'		    => $this->jobtraining->entity,
	    'Area'		    => $this->jobtraining->scholarity_area,
	    'Status'		    => $this->jobtraining->status ? 'Loke' : 'Taka', 
	    'Mane Nain'		    => $this->jobtraining->total_man, 
	    'Feto Nain'		    => $this->jobtraining->total_woman, 
	    'Total Partisipante'    => $this->jobtraining->total_participants, 
	    'Salariu'		    => empty( $this->jobtraining->salary ) ? null : '$' . number_format( $this->jobtraining->salary, 2, '.', '' ),
	    'Loron Inisiu'	    => $this->jobtraining->date_start_formated,
	    'Loron Remata'	    => $this->jobtraining->date_finish_formated,
	    'Deskrisaun'	    => $this->jobtraining->description
	);
    ?>
    
    <div class="row-fluid">
	<?php 
	    $columns = 0;
	    foreach ( $dataJobTraining as $title => $value ) : 
		
		if ( empty( $value ) )
		    continue;
		
		$columns++;
	?>
	
	    <div class="span4">
		<div class="control-group">
		    <label class="control-label bold"><?php echo $title; ?>:</label>
		    <div class="controls">
			<span class="text">
			    <?php echo $value; ?>
			</span>
		    </div>
		</div>
	    </div>
	
	    <?php if ( $columns % 3 == 0 ) : ?>
		</div>
		<div class="row-fluid">
	    <?php endif; ?>
	
	<?php endforeach; ?>
    </div>
    
    <h4 class="form-section bold">
	Kursu
    </h4>
    
    <div class="row-fluid">
    <?php foreach ( $this->courses as $c => $course ) : ?>
	    <div class="span6">
		<strong><?php echo $course->scholarity; ?></strong>
	    </div>
	    
	    <?php if ( ++$c % 2 == 0 ) : ?>
		</div>
		<div class="row-fluid">
	    <?php endif; ?>	
    <?php endforeach; ?>
    </div>
    
    <div class="margin-bottom-25"></div>
    
    <h4 class="form-section bold">
	Partisipantes
    </h4>
    
    <div class="row-fluid margin-bottom-25">
	<table class="table table-striped table-hover table-bordered">
		<thead>
			<tr>
			    <th>No KARTAUN EVIDENSIA</th>
			    <th>NARAN</th>
			    <th>SEKSU</th>
			    <th>REMATA</th>
			    <th>KOMPLETU</th>
			    <th>DATA INISIU</th>
			    <th>DATA REMATA</th>
			    <th>TELEMOVEL</th>
			</tr>
		</thead>
		<tbody>
		    <?php foreach ( $this->clients as $key => $client ) : ?>
			<tr>
			    <td><?php echo Client_Model_Mapper_Client::buildNumRow( $client ); ?></td>
			    <td><?php echo Client_Model_Mapper_Client::buildName( $client ); ?></td>
			    <td><?php echo $client->gender; ?></td>
			    <td><?php echo $client->status ? 'SIM' : 'LAE'; ?></td>
			    <td><?php echo $client->completed ? 'SIM' : 'LAE'; ?></td>
			    <td><?php echo $client->date_start_formated; ?></td>
			    <td><?php echo $client->date_finish_formated; ?></td>
			    <td><?php echo empty( $client->client_fone ) ? ' - ' : $client->client_fone; ?></td>
			</tr>

		    <?php endforeach; ?>
		</tbody>
	</table>
    </div>
    
    <div class="row-fluid">
	<div class="span4 offset8 text-center">
	    <div class="row-fluid">
		<?php
		    $auth = Zend_Auth::getInstance()->getIdentity();
		    echo $auth->name_dec . ' - ' . Zend_Date::now()->toString( 'dd/MM/yyyy' );
		?>
	    </div>
	    <div class="row-fluid">Tekniknu Profisional Empregu</div>
	    <div class="row-fluid">
		<br />
	    </div>
	    <div class="row-fluid">
		<?php echo $auth->name; ?>
	    </div>
	</div>
    </div>
    
</div>