<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo str_pad( $row->id_jobtraining, 5, '0', STR_PAD_LEFT ); ?></td>
	<td><?php echo $row->title; ?></td>
	<td><?php echo $row->entity; ?></td>
	<td><?php echo Client_Model_Mapper_Client::buildNumById( $row->fk_id_perdata ) . ' - ' . Client_Model_Mapper_Client::buildName( $row ); ?></td>
	<td style="width: 10%" class="hidden-phone hidden-tablet">
	    <?php 
		if ( $row->status == 1 ) {
		    $label = 'success';
		    $status = 'Loke';
		} else {
		    
		    $label = 'important';
		    $status = ( $row->status == 2 ) ? 'Kansela' : 'Taka';	
		}
	    ?>
	    <span class="label label-<?php echo $label; ?>">
		<?php echo $status; ?>
	    </span>
	</td>
	<td style="width: 12%">
	    <a class="btn red-stripe" target="_blank" href="<?php echo $this->baseUrl( 'student-class/job-training/print/id/' . $row->id_jobtraining ); ?>">
		<i class="icon-eye-open"></i>                                     
	    </a>

	    <?php if ( $row->status == 1 ) : ?>
		<a class="btn red action-ajax" href="javascript:;" data-id="<?php echo $row->id_trainee; ?>">
		    <i class="icon-ok"></i>                                     
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>