<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_barrier_intervention' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_barrier_type' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_barrier_name' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'barrier_Intervention_name' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'barrier_intervention_observation' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'barrier_Intervention_active' ); ?>
		</div>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>