<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->barrier_type_name; ?></td>
	<td><?php echo $row->barrier_name; ?></td>
	<td><?php echo $row->barrier_Intervention_name; ?></td>
	<td>
	    <?php if ( $this->access( Register_Form_Scholarity::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
		<a class="btn green" href="<?php echo $this->baseUrl( 'register/barrier-intervention/edit/id/' . $row->id_barrier_intervention ); ?>">
		    <i class="icon-edit"></i>  
		    Troka                                            
		</a>
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>  
		    La bele acessu                                            
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>