<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_addsucu' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="span6"><?php echo $this->form->getElement( 'fk_id_addcountry' ); ?></div>
	    <div class="span6"><?php echo $this->form->getElement( 'fk_id_adddistrict' ); ?></div>
	</div>
	<div class="row-fluid">
	    <div class="span6"><?php echo $this->form->getElement( 'fk_id_addsubdistrict' ); ?></div>
	    <div class="span6"><?php echo $this->form->getElement( 'sucu' ); ?></div>
	</div>
	
	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>