<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->country; ?></td>
	<td><?php echo $row->District; ?></td>
	<td><?php echo $row->sub_district; ?></td>
	<td><?php echo $row->sucu; ?></td>
	<td>
	    <?php if ( $this->access( Register_Form_Suku::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
		<a class="btn green" href="<?php echo $this->baseUrl( 'register/suku/edit/id/' . $row->id_addsucu ); ?>">
		    <i class="icon-edit"></i>  
		    Troka                                            
		</a>
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>  
		    La bele acessu                                            
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>