<div class="row-fluid">
    <div class="span12">
	<fieldset>
	    <legend>Dadus Kontratu</legend>
	    <div class="row-fluid">
		<div class="span4">
		    <div class="control-group">
			<label class="control-label">Kontratu</label>
			<div class="controls">
			    <span class="text bold">
				<?php echo $this->params['contract']; ?>
			    </span>
			</div>
		    </div>
		</div>
		<div class="span4">
		    <div class="control-group">
			<label class="control-label">Komponente</label>
			<div class="controls">
			    <span class="text bold">
				<?php echo $this->params['component']; ?>
			    </span>
			</div>
		    </div>
		</div>
		<div class="span4">
		    <div class="control-group">
			<label class="control-label">Komponente</label>
			<div class="controls">
			    <span class="text bold">
				<?php echo $this->params['expense']; ?>
			    </span>
			</div>
		    </div>
		</div>
	    </div>
	</fieldset>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
	<fieldset>
	    <legend>Totals</legend>
	    <div class="row-fluid">
		<div class="span6">
		    <div class="control-group">
			<label class="control-label">Total Banku</label>
			<div class="controls">
			    <span class="text bold">
				<?php echo $this->currency( $this->params['bank_amount'] ); ?>
			    </span>
			</div>
		    </div>
		</div>
		<div class="span6">
		    <div class="control-group">
			<label class="control-label">Komponente</label>
			<div class="controls">
			    <span class="text bold">
				<?php echo $this->currency( $this->params['total_financial'] ); ?>
			    </span>
			</div>
		    </div>
		</div>
	    </div>
	</fieldset>
    </div>
</div>

<hr />

<h4>Lansamentu Banku</h4>
<table class="table table-striped table-bordered table-hover table-full-width">
    <thead>
	<tr>
	    <th style="width: 8%" class="date-column">Data</th>
	    <th>Deskrisaun</th>
	    <th style="width: 20%">Tipo Mov.</th>
	    <th>Fonte</th>
	    <th style="width: 13%">Valor</th>
	</tr>
    </thead>
    <tbody>
	<?php foreach ( $this->params['bankStatements'] as $row ) : ?>
	    <tr>
		<td><?php echo $this->date( $row->date_statement ); ?></td>
		<td><?php echo $row->description; ?></td>
		<td><?php echo $row->type_transaction; ?></td>
		<td><?php echo $row->name_fund; ?></td>
		<td class="text-right">
		    <p class="pull-right bold text-<?php echo $row->operation == 'C' ? 'success' : 'error'; ?>">
			 <?php echo $this->currency( $row->amount_contract * ( $row->operation == 'C' ? 1 : -1 ) ); ?>
		    </p>
		</td>
	    </tr>
	<?php endforeach; ?>
    </tbody>
</table>

<h4>Lansamentu Financeiru</h4>
<table class="table table-striped table-bordered table-hover table-full-width">
    <thead>
	<tr>
	    <th style="width: 8%" class="date-column">Data</th>
	    <th style="width: 5%">T/P</th>
	    <th>Deskrisaun</th>
	    <th style="width: 13%">Valor</th>
	</tr>
    </thead>
    <tbody>
	<?php foreach ( $this->params['financialTransactions'] as $row ) : ?>
	    <tr>
		<td style="width: 8%"><?php echo $this->date( $row->date_reference ); ?></td>
		<td style="width: 5%"><?php echo $row->code_transaction; ?></td>
		<td><?php echo empty( $row->description ) ? 'N/A' : ucwords( strtolower( $row->description ) ); ?></td>
		<td class="text-right" style="width: 13%">
		    <p class="pull-right bold text-<?php echo $row->operation == 'C' ? 'success' : 'error'; ?>">
			 <?php echo $this->currency( $row->amount * ( $row->operation == 'C' ? 1 : -1 ) ); ?>
		    </p>
		</td>
	    </tr>
	<?php endforeach; ?>
    </tbody>
</table>
