<div class="row-fluid">
    <div class="span12">
	<div class="row-fluid">
	    <div class="span12">
		<div class="portlet box green ">
		    <div class="portlet-title">
			<div class="caption"><i class="icon-search"></i>Buka</div>
			<div class="tools"><a href="javascript:;" class="expand"></a></div>
		    </div>
		    <div class="portlet-body form hide">
			<?php 
			    $this->placeholder( 'form' )->captureStart();
			    echo $this->formSearch->getElement( 'id_fefop_bank_contract' );
			?>

			    <div class="box-content">
				<div class="row-fluid">
				    <div class="span4">
					<?php echo $this->formSearch->getElement( 'fk_id_fefop_type_transaction' ); ?>
				    </div>
				    <div class="span4">
					<?php echo $this->formSearch->getElement( 'date_start' ); ?>
				    </div>
				    <div class="span4">
					<?php echo $this->formSearch->getElement( 'date_finish' ); ?>
				    </div>
				</div>
				<div class="row-fluid">
				    <div class="span6">
					<?php echo $this->formSearch->getElement( 'fk_id_budget_category_type' ); ?>
				    </div>
				    <div class="span6">
					<?php echo $this->formSearch->getElement( 'fk_id_budget_category' ); ?>
				    </div>
				</div>
				<div class="row-fluid">
				    <div class="span11">
					<?php echo $this->formSearch->getElement( 'contract' ); ?>
				    </div>
				    <div class="span1">
					<div class="control-group">
					    <label class="control-label">&#160;</label>
					    <div class="controls">
						<button type="button" id="btn-search-contract"
							class="btn green" title="Buka Kontratu" onclick="Fefop.BankConsolidate.searchContract()">
						     <i class="icon-search"></i>  
						 </button>
					    </div>
					</div>
				    </div>
				</div>
				<div class="row-fluid">
				    <div class="span6">
					<?php echo $this->formSearch->getElement( 'minimum_amount' ); ?>
				    </div>
				    <div class="span6">
					<?php echo $this->formSearch->getElement( 'maximum_amount' ); ?>
				    </div>
				</div>
				<div class="row-fluid">
				    <div class="form-actions">
					<button class="btn blue">Buka <i class="icon-search m-icon-white"></i></button>
					<button class="btn green" type="reset" id="clear">Hamoos <i class="icon-trash m-icon-white"></i></button>
				    </div>
				</div>
			    </div>

			<?php
			    $this->placeholder( 'form' )->captureEnd();
			    echo $this->form( $this->formSearch->getId(), $this->formSearch->getAttribs(), $this->placeholder( 'form' ) );
			?>
		    </div>
		</div>
	    </div>
	</div>

	<div class="row-fluid">
	    <div class="span12">
		<div class="portlet box green ">
		    <div class="portlet-title">
			<div class="caption"><i class="icon-dollar"></i>Transasaun Konsolida</div>
			<div class="tools"><a href="javascript:;" class="collapse"></a></div>
		    </div>
		    <div class="portlet-body form">
			<table class="table table-striped table-bordered table-hover table-full-width" id="statement-list">
			    <thead>
				<tr>
				    <th style="width: 8%" class="no-sort">Consol.</th>
				    <th style="width: 8%" class="date-column">Data Konsolida</th>
				    <th style="width: 8%" class="date-column">Data Lansamentu</th>
				    <th>Deskrisaun</th>
				    <th style="width: 13%">Valor Konsolida</th>
				    <th style="width: 13%">Valor Lansamentu</th>
				    <th style="width: 10%" class="no-sort"></th>
				</tr>
			    </thead>
			    <tbody></tbody>
			</table>
		    </div>
		</div>
	    </div>
	</div>
    </div>
</div>