<?php $this->placeholder( 'form' )->captureStart(); ?>

    
    <div class="box-content">
	
	<?php if ( empty( $this->items ) ) : ?>
	    <div class="alert alert-info">
		La iha transasaun ba halo konsiliasaun.
	    </div>
	<?php endif ;?>
	
	<table class="table table-striped table-bordered table-hover table-full-width" id="consolidate-list">
	    <thead>
		<tr>
		    <th style="width: 8%" class="no-sort">Consolida?</th>
		    <th style="width: 15%">Kontratu</th>
		    <th>Komponente</th>
		    <th>Rúbrica</th>
		    <th>Folin Banku</th>
		    <th>Folin Finanseiru</th>
		    <th></th>
		</tr>
	    </thead>
	    <tbody>
		<?php 
		    
		    $attribsTotal = array( 'class' => 'text-right span10 pull-right', 'disabled' => true );
		
		    $allConsolidated = false;
		    foreach ( $this->items as $id => $item ) : 
			$allConsolidated = $allConsolidated || $item['consolidate'];
		?>
		    <tr class="<?php echo $item['consolidate'] ? 'muted text-success' : 'text-error'; ?>">
			<td>
			    <input type="checkbox" name="consolidate[<?php echo $id; ?>]" 
				   value="1" <?php echo $item['consolidate'] ? 'checked="checked"' : 'disabled="1"'; ?> class="toggle-check"  />
			</td>
			<td><?php echo $item['contract']; ?></td>
			<td><?php echo $item['component']; ?></td>
			<td><?php echo $item['expense']; ?></td>
			<td>
			    <strong><?php echo $this->currency( $item['bank_amount'] ); ?></strong>
			</td>
			<td>
			    <strong><?php echo $this->currency( $item['total_financial'] ); ?></strong>
			</td>
			<td>
			    <a class="btn blue" title="Detalha Lansamentu"
			    onclick="Fefop.BankConsolidate.detailSession( '<?php echo $id; ?>' );">
			     <i class="icon-info-sign"></i>            
			  </a>
			</td>
		    </tr>
		<?php endforeach; ?>
	    </tbody>
	</table>
	
	<?php 
	    if ( $allConsolidated )
		echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>