<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_fe_contract' );
    echo $this->form->getElement( 'fk_id_fefop_contract' );
    echo $this->form->getElement( 'fk_id_fefpeduinstitution' );
    echo $this->form->getElement( 'fk_id_fefpenterprise' );
    echo $this->form->getElement( 'fk_id_perdata' );
    echo $this->form->getElement( 'fk_id_trainee' );
    echo $this->form->getElement( 'fk_id_fe_registration' );
 ?>

    <?php echo $this->fefopContract()->getMessages(); ?>

    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span9">
		    <?php echo $this->form->getElement( 'entity' ); ?>
		</div>
		<div class="span2">
		    <div class="control-group">
			<label class="control-label">&#160;</label>
			<div class="controls">
			    <div class="btn-group">
				<a class="btn red" id="btn-search-entity" href="javascript:;" data-toggle="dropdown">
				    <i class="icon-search"></i> Buka
				    <i class="icon-angle-down"></i>
				</a>
				<ul class="dropdown-menu">
				    <li>
					<a href="javascript:;" onClick="Fefop.FEContract.searchRegistration();">
					    <i class="icon-file"></i> 
					    Fixa Inskrisaun
					</a>
				    </li>
				    <li>
					<a href="javascript:;" onClick="Fefop.FEContract.searchInstitute();">
					    <i class="icon-book"></i> 
					    Inst. Ensinu
					</a>
				    </li>
				    <li>
					<a href="javascript:;" onClick="Fefop.FEContract.searchEnterprise();">
					    <i class="icon-group"></i> 
					    Empreza
					</a>
				    </li>
				    <li>
					<a href="javascript:;" onClick="Fefop.FEContract.searchTrainee();">
					    <i class="icon-briefcase"></i> 
					    Job Training
					</a>
				    </li>
				</ul>
			    </div>
			</div>
		    </div>
		</div>
		<div class="span1">
		    <div class="control-group">
			<label class="control-label">&#160;</label>
			<div class="controls">
			    <button type="button" id="btn-export-contract" disabled="disabled" 
				    class="btn green" title="Exporta Kontratu" onclick="Fefop.FEContract.exportContract()">
				 <i class="icon-print"></i>  
			     </button>
			</div>
		    </div>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span11">
		    <?php echo $this->form->getElement( 'beneficiary' ); ?>
		</div>
		<div class="span1">
		    <div class="control-group">
			<label class="control-label">&#160;</label>
			<div class="controls">
			    <button type="button" id="btn-search-beneficiary" class="btn green" title="Buka Benefisiariu" onclick="Fefop.FEContract.searchClient()">
				 <i class="icon-search"></i>  
			     </button>
			</div>
		    </div>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_scholarity_area' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_profocupationtimor' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_adddistrict' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_addsubdistrict' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span4">
		    <?php echo $this->form->getElement( 'date_start' ); ?>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'date_finish' ); ?>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'duration_month' ); ?>
		</div>
		<!--
		<div class="span3">
		    <?php //echo $this->form->getElement( 'date_formation' ); ?>
		</div>
		-->
	    </div>
	    <!--
	    <div class="row-fluid">
		<div class="span3 offset9">
		    <div class="alert alert-info not-remove" style="font-size: 10px; padding: 5px; overflow: auto; width: auto">
			Formação não pode iniciar-se depois da data acima, sob pena de perda do crédito para formação referido no presente contrato.
		    </div>
		</div>
	    </div>
	    -->
	    
	    <div class="row-fluid">
		<div class="span12">
		    <div class="portlet box blue ">
			<div class="portlet-title">
			    <div class="caption"><i class="icon-dollar"></i>Finansiamentu</div>
			    <div class="tools"><a href="javascript:;" class="collapse"></a></div>
			</div>
			<div class="portlet-body form">
			    <table class="table table-striped table-bordered table-hover table-full-width" id="expense-list">
				<thead>
				    <tr>
					<th style="width: 7%">#</th>
					<th>Rúbrika</th>			
					<th style="width: 15%">Folin Hira</th>
				    </tr>
				</thead>
				<tbody>
				    <?php 
					$count = 'A';
					foreach ( $this->expenses as $expense ) : 
				    ?>
					<tr>
					    <td><?php echo $count++; ?>.</td>
					    <td><?php echo $expense->description; ?></td>
					    <td>
						<div class="control-group">
						    <div class="controls">
							<?php
							    $attribsText = array(
								'class'	    => 'm-wrap span12 focused required cost-expense submit-field money-mask',
								'id'	    => 'total_expense_' . $expense->id_budget_category
							    );

							    $amount = null;
							    if ( !empty( $expense->amount ) )
								$amount = number_format( $expense->amount, 2, '.', '.' );

							    echo $this->formText( 'cost_expense[' . $expense->id_budget_category . ']', $amount, $attribsText );  
							 ?>
						    </div>
						</div>
					    </td>
					</tr>
				    <?php endforeach; ?>
				</tbody>
			    </table>
			</div>
		    </div>
		</div>
	    </div>
	    
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>