<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_perdata' );
    echo $this->form->getElement( 'step' );
 ?>
    <div class="row-fluid">
	<div class="span12">
	    <?php echo $this->form->getElement( 'learn_option' ); ?>
	</div>
    </div>

    <?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box light-grey">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Hatene CEOP Sira</div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="about-list">
		    <thead>
			<tr>
			    <th>Deskrisaun</th>
			    <th>Action</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>