<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_perdata' );
    echo $this->form->getElement( 'id_addaddress' );
    echo $this->form->getElement( 'step' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_addcountry' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_adddistrict' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_addsubdistrict' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_addsucu' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span3">
		    <?php echo $this->form->getElement( 'street' ); ?>
		</div>
		<div class="span3">
		    <?php echo $this->form->getElement( 'number' ); ?>
		</div>
		<div class="span3">
		    <?php echo $this->form->getElement( 'postal_code' ); ?>
		</div>
		<div class="span3">
		    <?php echo $this->form->getElement( 'village' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span12">
		    <?php echo $this->form->getElement( 'complement' ); ?>
		</div>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box light-grey ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Hela Fatin Sira</div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="address-list">
		    <thead>
			<tr>
			    <th>Nasaun</th>
			    <th>Distritu</th>
			    <th>Sub-Distritu</th>
			    <th>Suku</th>
			    <th>Vila</th>
			    <th>Action</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>