<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_perdata' );
    echo $this->form->getElement( 'step' );
 ?>
    <div class="row-fluid">
	<div class="span4">
	    <?php echo $this->form->getElement( 'contact_name' ); ?>
	</div>
	<div class="span4">
	    <?php echo $this->form->getElement( 'cell_fone' ); ?>
	</div>
	<div class="span4">
	    <?php echo $this->form->getElement( 'house_fone' ); ?>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span4">
	    <?php echo $this->form->getElement( 'job_fone' ); ?>
	</div>
	<div class="span4">
	    <?php echo $this->form->getElement( 'email' ); ?>
	</div>
	<div class="span4">
	    <?php echo $this->form->getElement( 'website' ); ?>
	</div>
    </div>

    <?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box light-grey">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Kontatu Sira</div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="contact-list">
		    <thead>
			<tr>
			    <th>Naran</th>
			    <th>Telemovel</th>
			    <th>Tel/Serbisu</th>
			    <th>Tel/Uma</th>
			    <th>Email</th>
			    <th>Website</th>
			    <th>Action</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>