<div style="padding:90px 0px 0px 75px; font-weight:bold; font-family:arial; font-size:10px;">
     <?php echo $this->client->name_dec; ?>
</div>
<div style="padding:10px 0px 0px 75px; font-weight:bold; font-family:arial; font-size:10px;">
    <?php echo Client_Model_Mapper_Client::buildName( $this->client ); ?>
</div>
<div style="padding:10px 0px 0px 75px; font-weight:bold; font-family:arial; font-size:10px;">
    <?php echo Client_Model_Mapper_Client::buildNumRow( $this->client ); ?>
</div>