<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_perdata' );
    echo $this->form->getElement( 'step' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'enterprise_name' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_profocupation' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span4">
		    <?php echo $this->form->getElement( 'start_date' ); ?>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'finish_date' ); ?>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'experience_year' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span12">
		    <?php echo $this->form->getElement( 'description' ); ?>
		</div>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box light-grey ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Esperiensia Profisional Sira</div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="experience-list">
		    <thead>
			<tr>
			    <th>Empreza</th>
			    <th>Okupasaun</th>
			    <th>Dt Inisiu</th>
			    <th>Dt Fim</th>
			    <th>Tinan Hira</th>
			    <th>Action</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>