<?php echo $this->render( 'client/detail.phtml' ); ?>

<div class="row-">
    <div class="span12">
	<div class="span4" id="button-back">
	    <a class="btn red margin-bottom-10" href="<?php echo $this->path( 'view/id/' . $this->id ); ?>">
		<i class="m-icon-swapleft m-icon-white"></i>
		Fila ba Kliente
	    </a>
	</div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box light-grey">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Istoriku Sira</div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width auto-init">
		    <thead>
			<tr>
			    <th>Atividade CEOP</th>
			    <th>Data Visita</th>
			    <th>CEOP</th>
			    <th>Funsionariu</th>
			</tr>
		    </thead>
		    <tbody>
			<?php foreach ( $this->history as $row ) : ?>
			    <tr>
				<td><?php echo $row->action; ?></td>
				<td><?php echo $row->date_time_formated; ?></td>
				<td><?php echo $row->name_dec; ?></td>
				<td><?php echo $row->name; ?></td>
			    </tr>
			<?php endforeach; ?>
		    </tbody>
		</table>
	    </div>
	</div>
    </div>
</div>