<div class="row-fluid">
    <div class="alert not-remove alert-danger">
	<strong><i class="icon-remove-sign"></i></strong> Tinan hira >= 16. Obrigatoriu informa kartaun Eleitorau ka Pasaporte husi kliente
    </div>
</div>
<div class="row-fluid">
    <div class="span4">
	<?php echo $this->form->getElement( 'fk_id_pertypedocument' ); ?>
    </div>
    <div class="span4">
	<?php echo $this->form->getElement( 'number' ); ?>
    </div>
    <div class="span4">
	<?php echo $this->form->getElement( 'original_proof' ); ?>
    </div>
</div>
<div class="row-fluid">
    <div class="span4">
	<?php echo $this->form->getElement( 'fk_id_country' ); ?>
    </div>
    <div class="span4">
	<?php echo $this->form->getElement( 'issue_date' ); ?>
    </div>
</div>