<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->purpose; ?></td>
	<td><?php echo $row->description; ?></td>
	<td><?php echo $row->observation; ?></td>
	<td><?php echo $row->visit_date_formated; ?></td>
	<td>
	    <?php if ( $this->access( Client_Form_ClientVisit::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
		<a class="btn red" data-visit='<?php echo $row->id_pervisitpurpose; ?>' onclick="Client.Client.removeVisit( this );">
		    <i class="icon-remove-sign"></i>            
		</a>
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>  
		    La bele acessu                                            
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>