<?php 
    $this->headScript()->appendFile( $this->baseUrl( 'public/scripts/controller/client/case.js' ) );
    $this->placeholder( 'form' )->captureStart();
 ?>
    <div class="box-content">
	
	<div class="row-fluid">
	    <div class="span12">
		<div class="portlet box blue">
		    <div class="portlet-title">
			<div class="caption"><i class="icon-search"></i> Buka Kliente</div>
			<div class="tools"><a class="collapse" href="javascript:;"></a></div>
		    </div>
		    <div class="portlet-body form">
	
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_dec' ); ?>
			    </div>
			    <div class="span6">
				<div class="control-group">
				    <label class="control-label" for="fk_id_dec">Numeru Rejistu</label>
				    <div class="controls">
					<?php 
					    echo $this->form->getElement( 'num_district' ); 
					    echo $this->form->getElement( 'num_subdistrict' ); 
					    echo $this->form->getElement( 'num_servicecode' ); 
					    echo $this->form->getElement( 'num_year' ); 
					    echo $this->form->getElement( 'num_sequence' ); 
					?>
				    </div>
				</div>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span4">
				<?php echo $this->form->getElement( 'first_name' ); ?>
			    </div>
			    <div class="span4">
				<?php echo $this->form->getElement( 'last_name' ); ?>
			    </div>
			    <div class="span4">
				<?php echo $this->form->getElement( 'evidence' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span3">
				<?php echo $this->form->getElement( 'active' ); ?>
			    </div>
			    <div class="span3">
				<?php echo $this->form->getElement( 'hired' ); ?>
			    </div>
			    <div class="span3">
				<?php echo $this->form->getElement( 'date_registration_ini' ); ?>
			    </div>
			    <div class="span3">
				<?php echo $this->form->getElement( 'date_registration_fim' ); ?>
			    </div>
			</div>

			<div class="row-fluid">
			    <div class="form-actions">
				<button class="btn blue">Buka <i class="icon-search m-icon-white"></i></button>
				<button class="btn green" type="reset" id="clear">Hamoos <i class="icon-trash m-icon-white"></i></button>
			    </div>
			</div>
		    </div>
		</div>
	    </div>
	</div>
	
	<div class="row-fluid">
	    <div class="span12">
		<div class="portlet box blue">
		    <div class="portlet-title">
			<div class="caption"><i class="icon-list"></i> Resultado Buka</div>
			<div class="tools"><a class="collapse" href="javascript:;"></a></div>
		    </div>
		    <div class="portlet-body form">
			<table class="table table-striped table-bordered table-hover table-full-width" id="client-list">
			    <thead>
				<tr>
				    <th style="width: 18%">Numeru</th>
				    <th style="width: 40%">Kliente</th>
				    <th class="hidden-phone hidden-tablet date-column">Data Moris</th>
				    <th class="hidden-phone hidden-tablet">Idade</th>
				    <th>Seksu</th>
				    <th class="hidden-phone hidden-tablet">CEOP</th>
				    <th style="width: 21%" class="no-sort">Action</th>
				</tr>
			    </thead>
			    <tbody></tbody>
			</table>
		    </div>
		</div>
	    </div>
	</div>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>