<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->enterprise_name; ?></td>
	<td><?php echo $row->ocupation_name_timor; ?></td>
	<td><?php echo $row->start_date_formated; ?></td>
	<td><?php echo $row->finish_date_formated; ?></td>
	<td><?php echo $row->experience_year; ?></td>
	<td>
	    <?php if ( $this->access( Client_Form_ClientExperience::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
		<a class="btn red" data-experience='<?php echo $row->id_perexperience; ?>' onclick="Client.Client.removeExperience( this );">
		    <i class="icon-remove-sign"></i>            
		</a>
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>  
		    La bele acessu                                            
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>