<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->dependent_name; ?></td>
	<td><?php echo $row->type_dependent; ?></td>
	<td><?php echo $row->birth_date_formated; ?></td>
	<td><?php echo $row->gender == 'M' ? 'MANE' : 'FETO'; ?></td>
	<td>
	    <?php if ( $this->access( Client_Form_ClientDependent::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
		<a class="btn red" data-dependent='<?php echo $row->id_perdependent; ?>' onclick="Client.Client.removeDependent( this );">
		    <i class="icon-remove-sign"></i>            
		</a>
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>  
		    La bele acessu                                            
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>