<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_perdata' );
    echo $this->form->getElement( 'step' );
    echo $this->form->getElement( 'fk_id_pertypescholarity' );
 ?>
    <div class="row-fluid">
	<div class="span6">
	    <?php echo $this->form->getElement( 'category' ); ?>
	</div>
	<div class="span6">
	    <?php echo $this->form->getElement( 'fk_id_perscholarity' ); ?>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span6">
	    <?php echo $this->form->getElement( 'start_date' ); ?>
	</div>
	<div class="span6">
	    <?php echo $this->form->getElement( 'finish_date' ); ?>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span12">
	    <?php echo $this->form->getElement( 'fk_id_fefpeduinstitution' ); ?>
	</div>
    </div>

    <?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box light-grey">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Edukasaun Sira</div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="non-formal-scholarity-list">
		    <thead>
			<tr>
			    <th>Kursu</th>
			    <th>Instituisaun</th>
			    <th style="width: 12%" class="hidden-tablet hidden-phone">Data Inisiu</th>
			    <th style="width: 12%" class="hidden-tablet hidden-phone">Data Fim</th>
			    <th>Action</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>