<div class="form-actions no-print">
    <button type="button" class="btn blue" onClick="self.print();"><i class="icon-print"></i> Print</button>
    <button type="button" class="btn red" onClick="self.close();"><i class="icon-remove-sign"></i> Taka</button>
</div>

<h3 class="text-center">
    CURRICULUM VITAE
</h3>

<div class="form-view">
    <div class="row-fluid">
	<div class="span10">
	    
	    <h4 class="form-section bold">
		DADUS PESSOAIS
	    </h4>
	    
	    <div class="row-fluid">
		<div class="span6">
		    <div class="control-group">
			<label class="control-label bold">Naran Kliente:</label>
			<div class="controls">
			    <span class="text">
				<?php echo Client_Model_Mapper_Client::buildName( $this->client ); ?>
			    </span>
			</div>
		    </div>
		</div>
		<div class="span3">
		    <div class="control-group">
			<label class="control-label bold">Data Moris:</label>
			<div class="controls">
			    <span class="text">
				<?php echo $this->client->birth_date_format; ?>
			    </span>
			</div>
		    </div>
		</div>
		<div class="span3">
		    <div class="control-group">
			<label class="control-label bold">Estado Sivil:</label>
			<div class="controls">
			    <span class="text">
				<?php echo $this->client->marital_status; ?>
			    </span>
			</div>
		    </div>
		</div>
	    </div>

	    <div class="row-fluid">
		<div class="span3">
		    <div class="control-group">
			<label class="control-label bold">E-mail:</label>
			<div class="controls">
			    <span class="text">
				<?php echo $this->client->email; ?>
			    </span>
			</div>
		    </div>
		</div>
		<div class="span3">
		    <div class="control-group">
			<label class="control-label bold">Eleitoral:</label>
			<div class="controls">
			    <span class="text">
				<?php echo $this->client->electoral; ?>
			    </span>
			</div>
		    </div>
		</div>
		<div class="span3">
		    <div class="control-group">
			<label class="control-label bold">Telefone:</label>
			<div class="controls">
			    <span class="text">
				<?php echo $this->client->client_fone; ?>
			    </span>
			</div>
		    </div>
		</div>
		<div class="span3">
		    <div class="control-group">
			<label class="control-label bold">Seksu:</label>
			<div class="controls">
			    <span class="text">
				<?php echo $this->client->gender; ?>
			    </span>
			</div>
		    </div>
		</div>
	    </div>
	</div>
	<div class="span2">
	    <div class="photo">
		<img src="<?php echo $this->baseUrl( 'public/images/no-picture.gif' ); ?>" />
	    </div>
	</div> 
    </div>
    
    <?php if ( $this->address->count() > 0 ) : ?>
    
	<h4 class="form-section bold">
	    Hela Fatin
	</h4>

	<?php foreach ( $this->address as $address ) : ?>
    
	    <?php if ( !empty( $address->District ) ) : ?>
    
		<div class="row-fluid">
		    <div class="span4">
			<label class="control-label bold">Nasaun</label>
		    </div>
		    <div class="span4">
			<label class="control-label bold">Distritu</label>
		    </div>
		    <div class="span4">
			<label class="control-label bold">SubDistritu</label>
		    </div>
		</div>

		<div class="row-fluid">
		    <div class="span4">
			<?php echo $address->country; ?>
		    </div>
		    <div class="span4">
			<?php echo $address->District; ?>
		    </div>
		    <div class="span4">
			<?php echo $address->sub_district; ?>
		    </div>
		</div>

		<div class="row-fluid">
		    <div class="span4">
			<label class="control-label bold">Suku</label>
		    </div>
		    <div class="span4">
			<label class="control-label bold">Vila</label>
		    </div>
		    <div class="span4">
			<label class="control-label bold">Dalan</label>
		    </div>
		</div>

		<div class="row-fluid">
		    <div class="span4">
			<?php echo $address->sucu; ?>
		    </div>
		    <div class="span4">
			<?php echo $address->village; ?>
		    </div>
		    <div class="span4">
			<?php echo $address->street; ?>
		    </div>
		</div>
		
	    <?php else : ?>
	    
		<div class="row-fluid">
		    <div class="span4">
			<label class="control-label bold">Nasaun</label>
		    </div>
		    <div class="span8">
			<label class="control-label bold">Komplementu</label>
		    </div>
		</div>

		<div class="row-fluid">
		    <div class="span4">
			<?php echo $address->country; ?>
		    </div>
		    <div class="span8">
			<?php echo $address->complement; ?>
		    </div>
		</div>
    
	    <?php endif; ?>
    
	    <hr />
    
	<?php endforeach; ?>
    
    <?php endif; ?>
	    
    <?php if ( !empty( $this->language ) || !empty( $this->knowledge ) ) : ?>
    
	<h4 class="form-section bold">
	    Kompetensia
	</h4>

	<?php if ( !empty( $this->language ) ) : ?>
	    
	    <h5 class="bold">Lian Fuan</h5>

	    <?php foreach ( $this->language as $language => $descriptions ) : ?>
		<div class="row-fluid">
		    <div class="span12">
			<strong><?php echo $language; ?></strong>
		    </div>
		</div>

		<?php foreach ( $descriptions as $description ) : ?>
		    <div class="row-fluid">
			<div class="span6">
			    <?php echo $description->name_level . ' - ' . $description->level; ?>
			</div>
			<div class="span6">
			    <?php echo $description->usage; ?>
			</div>
		    </div>
		<?php endforeach; ?>

		<hr />
	    <?php endforeach; ?>
	    
	<?php endif; ?>
		
	<?php if ( !empty( $this->knowledge ) ) : ?>
	    
	    <h5 class="bold">Konesimentu</h5>

	    <?php foreach ( $this->knowledge as $knowledge => $descriptions ) : ?>
		<div class="row-fluid">
		    <div class="span12">
			<strong><?php echo $knowledge; ?></strong>
		    </div>
		</div>

		<?php foreach ( $descriptions as $description ) : ?>
		    <div class="row-fluid">
			<div class="span6">
			    <?php echo $description->name_level . ' - ' . $description->level; ?>
			</div>
			<div class="span6">
			    <?php echo $description->name_knowledge; ?>
			</div>
		    </div>
		<?php endforeach; ?>

		<hr />
	    <?php endforeach; ?>
	    
	<?php endif; ?>
    
    <?php endif; ?>
		

    <?php if ( $this->formalScholarity->count() > 0  || $this->nonFormalScholarity->count() > 0 ) : ?>
    
	<h4 class="form-section bold">
	    Rekursu Akademiku
	</h4>
		
	<div class="row-fluid">
	    <div class="span4">
		<label class="control-label bold">Kursu</label>
	    </div>
	    <div class="span4">
		<label class="control-label bold">Inst. Ensinu</label>
	    </div>
	    <div class="span4">
		<label class="control-label bold">Titulu</label>
	    </div>
	</div>

	<?php if ( $this->formalScholarity->count() > 0 ) : ?>
		
	    <h6 class="bold">EDUCASAUN FORMAL</h6>
	 
	    <?php foreach ( $this->formalScholarity as $scholarity ) : ?>
		<div class="row-fluid">
		    <div class="span4">
			<?php echo ( empty( $scholarity->external_code ) ? '' : $scholarity->external_code . ' - ' ) . $scholarity->scholarity; ?>
		    </div>
		    <div class="span4">
			<?php echo $scholarity->institution; ?>
		    </div>
		    <div class="span4">
			<?php echo $scholarity->Title; ?>
		    </div>
		</div>
	    <?php endforeach; ?>
	    
	<?php endif; ?>
		
	<?php if ( $this->nonFormalScholarity->count() > 0 ) : ?>
	    
	     <h6 class="bold">EDUCASAUN LAOS FORMAL</h6>
	 
	    <?php foreach ( $this->nonFormalScholarity as $scholarity ) : ?>
		<div class="row-fluid">
		    <div class="span4">
			<?php echo ( empty( $scholarity->external_code ) ? '' : $scholarity->external_code . ' - ' ) . $scholarity->scholarity; ?>
		    </div>
		    <div class="span4">
			<?php echo $scholarity->institution; ?>
		    </div>
		    <div class="span4">
			<?php echo $scholarity->Title; ?>
		    </div>
		</div>
	    <?php endforeach; ?>
	    
	<?php endif; ?>
    
    <?php endif; ?>
		
    <?php if ( $this->experience->count() > 0 ) : ?>
    
	<h4 class="form-section bold">
	    Esperiensia
	</h4>
		
	<div class="row-fluid">
	    <div class="span5">
		<label class="control-label bold">Empreza</label>
	    </div>
	    <div class="span5">
		<label class="control-label bold">Okupasaun</label>
	    </div>
	    <div class="span2">
		<label class="control-label bold">Tinan Hira</label>
	    </div>
	</div>
	 
	<?php foreach ( $this->experience as $experience ) : ?>
	    <div class="row-fluid">
		<div class="span5">
		    <?php echo $experience->enterprise_name; ?>
		</div>
		<div class="span5">
		    <?php echo $experience->ocupation_name_timor; ?>
		</div>
		<div class="span2">
		    <?php echo $experience->experience_year; ?>
		</div>
	    </div>
	<?php endforeach; ?>
    
    <?php endif; ?>
		
    <?php if ( $this->contact->count() > 0 ) : ?>
    
	<h4 class="form-section bold">
	    Referensia
	</h4>
		
	<div class="row-fluid">
	    <div class="span5">
		<label class="control-label bold">Naran Kontatu</label>
	    </div>
	    <div class="span3">
		<label class="control-label bold">Telemovel</label>
	    </div>
	    <div class="span4">
		<label class="control-label bold">Email</label>
	    </div>
	</div>
	 
	<?php foreach ( $this->contact as $contact ) : ?>
	    <div class="row-fluid">
		<div class="span5">
		    <?php echo $contact->contact_name; ?>
		</div>
		<div class="span3">
		    <?php echo $contact->cell_fone; ?>
		</div>
		<div class="span4">
		    <?php echo $contact->email; ?>
		</div>
	    </div>
	<?php endforeach; ?>
    
    <?php endif; ?>
    
</div>

<div class="row-fluid margin-bottom-25">
</div>
<div class="row-fluid">
    <div class="span12 text-right">
	<small><em>SECRETARIA DE ESTADO PARA POLÍTICA DA FORMAÇÃO PROFISSIONAL E EMPREGO</em></small>
    </div>
</div>