<div class="row-fluid">
    <div class="span8">
	Kliente cadastro tiha ona ho naran:  <br />
	<a href="<?php echo $this->path( 'edit/id/' . $this->client->id_perdata ); ?>" target="_blank">
	    <strong>
		<?php echo Client_Model_Mapper_Client::buildNumRow( $this->client ); ?>
		-
		<?php echo Client_Model_Mapper_Client::buildName( $this->client ); ?>
	    </strong>
	</a>
    </div>
    <?php if ( !empty( $this->document ) ) : ?>
	<div class="span4">
	    Eleitoral: <strong><?php echo $this->document->number; ?></strong> <br />
	    Data Dokumentu: <strong><?php echo $this->date( $this->document->issue_date ); ?></strong>
	</div>
    <?php endif; ?>
</div>
<div class="row-fluid">
    <div class="span12">
	<?php if ( 'B' == $this->flag ) : ?>
	    Data moris: <strong><?php echo $this->date( $this->client->birth_date_format ); ?></strong>
	    <br />
	    <span class="label label-important">La bele rejistra fila fali</span>
	<?php endif; ?>
    </div>
</div>