<?php echo $this->render( 'client/detail.phtml' ); ?>

<div class="row-fluid top-news button-dashboard">
    <div class="span6">
	<a href="<?php echo $this->baseUrl( '/client/client/edit/id/' . $this->client->id_perdata ); ?>" class="btn green">
	    <span>Edita dados</span>
	    <i class="icon-edit top-news-icon"></i>                             
	</a>
    </div>
    <div class="span6">
	<a href="javascript:;" class="btn blue" onClick="Client.Client.printCurriculum( <?php echo $this->client->id_perdata; ?> );">
	    <span>Curriculum Vitae</span>
	    <i class="icon-list top-news-icon"></i>
	</a>
    </div>
</div>
<div class="row-fluid top-news button-dashboard">
    <?php if ( !empty( $this->client->id_action_plan ) ) : ?>
	<div class="span6">
	    <a href="<?php echo $this->baseUrl( '/client/client/evidence/id/' . $this->client->id_perdata ); ?>" target="_blank" class="btn yellow">
		<span>Kartaun Evidensia</span>
		<i class="icon-credit-card top-news-icon"></i>                             
	    </a>
	</div>
    <?php endif; ?>
    <div class="span6">
	<a href="<?php echo $this->baseUrl( '/client/client/history/id/' . $this->client->id_perdata ); ?>" class="btn red">
	    <span>Istoriku</span>
	    <i class="icon-hdd top-news-icon"></i>                              
	</a>
    </div>
</div>
