<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_perdata' );
    echo $this->form->getElement( 'id_pervisitpurpose' );
    echo $this->form->getElement( 'step' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="span6">
		<div class="row-fluid">
		    <div class="span12">
			<?php echo $this->form->getElement( 'fk_id_visitpurpose' ); ?>
		    </div>
		</div>
		<div class="row-fluid">
		    <div class="span12">
			<?php echo $this->form->getElement( 'description' ); ?>
		    </div>
		</div>
		<div class="row-fluid">
		    <div class="span12">
			<?php echo $this->form->getElement( 'visit_date' ); ?>
		    </div>
		</div>
	    </div>
	    <div class="span6">
		<?php echo $this->form->getElement( 'observation' ); ?>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box light-grey ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Hela Fatin Sira</div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="visit-list">
		    <thead>
			<tr>
			    <th>Objetivu</th>
			    <th>Deskrisaun</th>
			    <th>Observasaun</th>
			    <th>Data Vizita</th>
			    <th>Action</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>