<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td>
	    <?php if ( empty( $row->list ) ) : ?>
	    
		<input type="checkbox" onChange="Job.Match.setClientList( this, $( this ).closest( '.tab-pane' ).attr( 'id' ) );" 
		    class="clients" value="<?php echo $row->id_perdata; ?>" />
		
	    <?php else : ?>
		
		<a href="javascript:;" class="btn red disabled">
		    <i class="icon-ban-circle"></i>
		</a>
		
	    <?php endif; ?>
	</td>
	<td><?php echo Client_Model_Mapper_Client::buildNumRow( $row ); ?></td>
	<td>
	    <?php if ( $this->access( Client_Form_ClientInformation::ID) ) : ?>
		<a href="<?php echo $this->baseUrl( '/client/client/print/id/' . $row->id_perdata ); ?>" target="_blank">
		    <?php echo Client_Model_Mapper_Client::buildName( $row ); ?>
		</a>
	    <?php else : ?>
		    <?php echo Client_Model_Mapper_Client::buildName( $row ); ?>
	    <?php endif; ?>
	</td>
	<td class="hidden-phone hidden-tablet"><?php echo $row->date_registration_format; ?></td>
	<td class="hidden-phone hidden-tablet"><?php echo $row->birth_date_format; ?></td>
	<td class="hidden-phone hidden-tablet"><?php echo $row->age; ?></td>
	<td><?php echo $row->gender; ?></td>
	<td class="hidden-phone hidden-tablet"><?php echo $row->name_dec; ?></td>
    </tr>
<?php endforeach; ?>