<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_jobvacancy' );
    echo $this->form->getElement( 'source' );
 ?>
    <div class="box-content">
	
	<div class="row-fluid">
	    <div class="span6">
		<?php echo $this->form->getElement( 'fk_id_dec' ); ?>
	    </div>
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label" for="fk_id_dec">Numeru Rejistu</label>
		    <div class="controls">
			<?php 
			    echo $this->form->getElement( 'num_district' ); 
			    echo $this->form->getElement( 'num_subdistrict' ); 
			    echo $this->form->getElement( 'num_servicecode' ); 
			    echo $this->form->getElement( 'num_year' ); 
			    echo $this->form->getElement( 'num_sequence' ); 
			?>
		    </div>
		</div>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="span6">
		<?php echo $this->form->getElement( 'first_name' ); ?>
	    </div>
	    <div class="span6">
		<?php echo $this->form->getElement( 'last_name' ); ?>
	    </div>
	</div>
	
	<div class="row-fluid margin-bottom-25">
	    <div class="form-actions">
		<button class="btn blue">Buka <i class="icon-search m-icon-white"></i></button>
		<button class="btn green" type="reset" id="clear">Hamoos <i class="icon-trash m-icon-white"></i></button>
		<button class="btn red" <?php echo !$this->jobActive()->hasAccessEdit( false ) ? 'disabled' : ''; ?> type="button" onclick="Job.Match.addList( $( this ).closest( 'form' ) );">
		    <i class="icon-list m-icon-white"></i>
		    Hili Kandidatu
		</button>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="span12">
		<div class="portlet box green">
		    <div class="portlet-title">
			<div class="caption"><i class="icon-list"></i> Resultado Buka</div>
		    </div>
		    <div class="portlet-body form">
			<?php echo $this->render( 'match/search.phtml' ); ?>
		    </div>
		</div>
	    </div>
	</div>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>