<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_jobvacancy' );
 ?>
    <div class="box-content">
	<div class="row-fluid hide" id="info-vacancy-list">
	    <div class="alert alert-info">
		<strong>
		    Atensaun!
		</strong> 
		Vaga iha ne'e seidauk iha lista Kandidatu.
	    </div>
	</div>

	<div class="row-fluid margin-bottom-25">
	    <div class="span12 text-center">
		<button class="btn red" <?php echo !$this->jobActive()->hasAccessEdit() ? 'disabled' : ''; ?>
			type="button" onclick="Job.Match.doShortlist();">
		    <i class="icon-list-alt m-icon-white"></i>
		    Halot Shortlist
		</button>
	    </div>
	</div>
	<div class="row-fluid">
	    <table class="table table-striped table-bordered table-hover table-full-width" id="list-list">
		<thead>
		    <tr>
			<th style="width: 4%" class="no-sort">
			    <input type="checkbox" onClick="Job.Match.checkAll( this, 'candidates' );" />
			</th>
			<th style="width: 16%">Numeru</th>
			<th>Kliente</th>
			<th style="width: 3%" class="hidden-phone hidden-tablet">Rejistu</th>
			<th style="width: 11%" class="hidden-phone hidden-tablet">Data Moris</th>
			<th style="width: 3%" class="hidden-phone hidden-tablet">Idade</th>
			<th style="width: 2%">Seksu</th>
			<th class="hidden-phone hidden-tablet">CEOP</th>
		    </tr>
		</thead>
		<tbody></tbody>
	    </table>
	</div>

    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>