<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_jobvacancy' );
    echo $this->form->getElement( 'source' );
    echo $this->form->getElement( 'minimum_age' );
    echo $this->form->getElement( 'maximum_age' );
 ?>
    <div class="box-content">
	
	<div class="well">
	    <fieldset>
		<legend>1 - Kliente Hela Fatin</legend>
		<div class="row-fluid">
		    <div class="span6">
			<?php echo $this->form->getElement( 'fk_id_adddistrict' ); ?>
		    </div>
		    <div class="span6">
			<?php echo $this->form->getElement( 'fk_id_addsubdistrict' ); ?>
		    </div>
		</div>
	    </fieldset>
	</div>
	<div class="well">
	    <fieldset>
		<legend>2 - Nivel Edukasaun Formal</legend>
		<div class="row-fluid">
		    <div class="span6">
			<?php echo $this->form->getElement( 'category' ); ?>
		    </div>
		    <div class="span6">
			<?php echo $this->form->getElement( 'fk_id_perscholarity' ); ?>
		    </div>
		</div>
	    </fieldset> 
	</div>
	<div class="well">
	    <fieldset>
		<legend>3 - Formasaun Profisional</legend>
		<div class="row-fluid">
		    <div class="span12">
			<?php echo $this->form->getElement( 'fk_id_training' ); ?>
		    </div>
		</div>
	    </fieldset> 
	</div>
	<div class="well">
	    <fieldset>
		<legend>4 - Esperiensia Serbisu</legend>
		<div class="row-fluid">
		    <div class="span6">
			<?php echo $this->form->getElement( 'fk_id_profocupation' ); ?>
		    </div>
		    <div class="span6">
			<?php echo $this->form->getElement( 'minimum_experience' ); ?>
		    </div>
		</div>
	    </fieldset> 
	</div>
	<div class="well">
	    <fieldset>
		<legend>5 - Informasaun Kandidatu</legend>
		<div class="row-fluid">
		    <div class="span4">
			<?php echo $this->form->getElement( 'gender' ); ?>
		    </div>
		    <div class="span4">
			<?php echo $this->form->getElement( 'drive_licence' ); ?>
		    </div>
		    <div class="span4">
			<div class="control-group">
			    <label class="control-label optional margin-bottom-10-">Tinan Kandidatu</label>
			    <div class="controls">
				<div id="slider-age" class="slider bg-blue"></div>
				<div class="slider-value">
				    Tinan hira:
				    <span id="slider-age-amount">20 - 40</span>
				</div>
			    </div>
			</div>
		    </div>
		</div>
	    </fieldset> 
	</div>
	<div class="well">
	    <fieldset>
		<legend>6 - Nivel Lian Fuan</legend>
		<div class="row-fluid">
		    <div class="span12">
			<?php echo $this->form->getElement( 'fk_id_perlanguage' ); ?>
		    </div>
		</div>
	    </fieldset> 
	</div>
	<div class="row-fluid margin-bottom-25">
	    <div class="form-actions">
		<button class="btn blue">Buka <i class="icon-search m-icon-white"></i></button>
		<button class="btn green" type="reset" id="clear">Hamoos <i class="icon-trash m-icon-white"></i></button>
		<button class="btn red" <?php echo !$this->jobActive()->hasAccessEdit( false ) ? 'disabled' : ''; ?> type="button" 
			onclick="Job.Match.addList( $( this ).closest( 'form' ) );">
		    <i class="icon-list m-icon-white"></i>
		    Hili Kandidatu
		</button>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="span12">
		<div class="portlet box green">
		    <div class="portlet-title">
			<div class="caption"><i class="icon-list"></i> Resultado Buka</div>
		    </div>
		    <div class="portlet-body form">
			<?php echo $this->render( 'match/search.phtml' ); ?>
		    </div>
		</div>
	    </div>
	</div>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>