<table class="table table-striped table-bordered table-hover table-full-width" id="client-list">
    <thead>
	<tr>
	    <th style="width: 5%" class="no-sort">
		<input type="checkbox" onClick="Job.Match.checkAll( this );" />
	    </th>
	    <th style="width: 18%">Numeru</th>
	    <th style="width: 40%">Kliente</th>
	    <th class="hidden-phone hidden-tablet">Rejistu</th>
	    <th class="hidden-phone hidden-tablet">Data Moris</th>
	    <th class="hidden-phone hidden-tablet">Idade</th>
	    <th>Seksu</th>
	    <th class="hidden-phone hidden-tablet">CEOP</th>
	</tr>
    </thead>
    <tbody></tbody>
</table>