<?php 
    $this->placeholder( 'formShortlist' )->captureStart();
    echo $this->form->getElement( 'fk_id_jobvacancy' );
 ?>
    <div class="box-content">
	<div class="row-fluid hide" id="info-vacancy-shortlist">
	    <div class="alert alert-info">
		<strong>
		    Atensaun!
		</strong> 
		Vaga iha ne'e seidauk iha Shortlist.
	    </div>
	</div>
	
	<div class="row-fluid margin-bottom-25">
	    <div class="span12 text-center">
		<button class="btn green" type="button" onclick="Job.Match.printShortlist( <?php echo $this->id; ?> );">
		    <i class="icon-print m-icon-white"></i>
		    Imprimir Shortlist
		</button>
		<a class="btn red" href="<?php echo $this->baseUrl( '/job/vacancy/close/id/' . $this->id ); ?>">
		    <i class="icon-remove-sign m-icon-white"></i>
		    Taka Vaga
		</a>
	    </div>
	</div>


	<div class="row-fluid">
	    <table class="table table-striped table-bordered table-hover table-full-width" id="shortlist-list">
		<thead>
		    <tr>
			<th style="width: 17%">Numeru</th>
			<th style="width: 40%">Kliente</th>
			<th class="hidden-phone hidden-tablet">Rejistu</th>
			<th class="hidden-phone hidden-tablet">Data Moris</th>
			<th class="hidden-phone hidden-tablet">Idade</th>
			<th>Seksu</th>
			<th class="hidden-phone hidden-tablet">CEOP</th>
			<th>Action</th>
		    </tr>
		</thead>
		<tbody></tbody>
	    </table>
	</div>
    </div>
<?php
    $this->placeholder( 'formShortlist' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'formShortlist' ) );
?>