<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i> Kliente iha Grupu</div>
		<div class="actions">
		    <?php if ( $this->groupSms()->isEnabled() ) : ?>
			<a href="javascript:;" class="btn red" onclick="Sms.Group.addClient();"> 
			    <i class="icon-plus-sign"></i>
			</a>
		    <?php else : ?>
			<a class="btn red" href="javascript:;">
			    <i class="icon-alert icon-lock"></i>                                       
			</a>
		    <?php endif; ?>
		</div>
	    </div>
	    <div class="portlet-body form" style="overflow: auto">
		<table class="table table-striped table-bordered table-hover table-full-width" id="client-group-list">
		    <thead>
			<tr>
			   <th style="width: 18%">Numeru</th>
			    <th style="width: 40%">Kliente</th>
			    <th>Telemóvel</th>
			    <th>Seksu</th>
			    <th class="hidden-phone hidden-tablet">CEOP</th>
			    <th class="no-sort">Action</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>