<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->institution; ?></td>
	<td><?php echo $row->cell_fone; ?></td>
	<td style="width: 15%"><?php echo $row->type_institution; ?></td>
	<td style="width: 10%"><?php echo $row->register ? 'Sim' : 'Lae'; ?></td>
	<td>
	    <?php if ( $this->groupSms()->isEnabled() ) : ?>
		<a class="btn red" data-id="<?php echo $row->id_fefpeduinstitution; ?>" onclick="Sms.Group.removeItem( this, 'fk_id_fefpeduinstitution' );">
		    <i class="icon-remove-sign"></i>            
		</a>
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>                    
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>