<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->enterprise_name; ?></td>
	<td><?php echo $row->cell_fone; ?></td>
	<td><?php echo $row->type_enterprise; ?></td>
	<td><?php echo $row->name_dec; ?></td>
	<td>
	    <?php if ( $this->groupSms()->isEnabled() ) : ?>
		<a class="btn red" data-id="<?php echo $row->id_fefpenterprise; ?>" onclick="Sms.Group.removeItem( this, 'fk_id_fefpenterprise' );">
		    <i class="icon-remove-sign"></i>            
		</a>
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>                    
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>