<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_fefpstudentclass' );
    echo $this->form->getElement( 'step' );
 ?>
<div class="box-content">
    <div class="row-fluid hide" id="info-class-client">
	<div class="alert alert-info">
	    <strong>
		Atensaun!
	    </strong> 
	    Turma iha ne'e seidauk iha Partisipante.
	</div>
    </div>
    <?php if ( $this->competency->count() < 1 ) : ?>
	<div class="row-fluid">
	    <div class="span12 text-center">
		<button class="btn red" <?php echo $this->studentClassActive()->hasAccessEdit() && $this->access( StudentClass_Form_RegisterClient::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ? '' : 'disabled'; ?>>
		    <i class="icon-refresh m-icon-white"></i>
		    Atualiza Aluno
		</button>
	    </div>
	</div>
    <?php endif ;?>
    <div class="row-fluid">
	<table class="table table-striped table-bordered table-hover table-full-width" id="client-list">
	    <thead>
		<tr>
		    <th style="width: 17%">Numeru</th>
		    <th style="width: 35%">Kliente</th>			
		    <th style="width: 15%">Seksu</th>			
		    <th style="width: 15%">Data Retira</th>			
		    <?php if ( $this->competency->count() < 1 ) : ?>

			<th class="no-sort" style="width: 17%">
			    <div class="btn-group" style="margin: 0px !important;">
				<a class="btn green" href="javascript:;" data-toggle="dropdown">
				    <i class="icon-ok-circle"></i> Rezultadu
				    <i class="icon-angle-down"></i>
				</a>
				<ul class="dropdown-menu">
				    <!--
				    <li>
					<a href="javascript:;" 
					onClick="StudentClass.Register.setResult( '<?php echo StudentClass_Model_Mapper_StudentClass::DROPPED_OUT; ?>', this );">
					    <i class="icon-signout"></i> 
					    <?php echo $this->nomenclature()->resultClass( StudentClass_Model_Mapper_StudentClass::DROPPED_OUT ); ?>
					</a>
				    </li>
				    -->
				    <li>
					<a href="javascript:;" 
					onClick="StudentClass.Register.setResult( '<?php echo StudentClass_Model_Mapper_StudentClass::COMPLETED; ?>', this );">
					    <i class="icon-check"></i> 
					    <?php echo $this->nomenclature()->resultClass( StudentClass_Model_Mapper_StudentClass::COMPLETED ); ?>
					</a>
				    </li>
				    <li>
					<a href="javascript:;" 
					onClick="StudentClass.Register.setResult( '<?php echo StudentClass_Model_Mapper_StudentClass::GRADUATED; ?>', this );">
					    <i class="icon-trophy"></i> 
					    <?php echo $this->nomenclature()->resultClass( StudentClass_Model_Mapper_StudentClass::GRADUATED ); ?>
					</a>
				    </li>
				</ul>
			    </div>
			</th>

		    <?php else : ?>
			<th>Kompetensia</th>
			<th>Rezultadu</th>
		    <?php endif ;?>
		</tr>
	    </thead>
	    <tbody></tbody>
	</table>
    </div>
</div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>