<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_fefpstudentclass' );
    echo $this->form->getElement( 'fk_id_perdata' );
    echo $this->form->getElement( 'step' );
 ?>
<div class="box-content">
    <div class="row-fluid">
	<div class="span8">
	    <strong>
		<?php echo Client_Model_Mapper_Client::buildNumRow( $this->client ); ?>
		&nbsp;-&nbsp;
		<?php echo Client_Model_Mapper_Client::buildName( $this->client ); ?>
	    </strong>
	</div>
	<div class="span4">
	    <?php echo $this->form->getElement( 'date_drop_out' ); ?>
	</div>
    </div>
    <div class="row-fluid">
	<table class="table table-striped table-bordered table-hover table-full-width">
	    <thead>
		<tr>
		    <th style="width: 17%">Kodigu</th>
		    <th>Kompetensia</th>
		    <th class="no-sort" style="width: 17%">
			<div class="btn-group" style="margin: 0px !important;">
			    <a class="btn green" href="javascript:;" data-toggle="dropdown">
				<i class="icon-ok-circle"></i> Rezultadu
				<i class="icon-angle-down"></i>
			    </a>
			    <ul class="dropdown-menu">
				    <li>
					<a href="javascript:;" 
					   onClick="StudentClass.Register.setResult( '<?php echo StudentClass_Model_Mapper_StudentClass::DROPPED_OUT; ?>', this );">
					    <i class="icon-signout"></i> 
					    <?php echo $this->nomenclature()->resultClass( StudentClass_Model_Mapper_StudentClass::DROPPED_OUT ); ?>
					</a>
				    </li>
				    <li>
					<a href="javascript:;" 
					   onClick="StudentClass.Register.setResult( '<?php echo StudentClass_Model_Mapper_StudentClass::COMPLETED; ?>', this );">
					    <i class="icon-check"></i> 
					    <?php echo $this->nomenclature()->resultClass( StudentClass_Model_Mapper_StudentClass::COMPLETED ); ?>
					</a>
				    </li>
				    <li>
					<a href="javascript:;" 
					   onClick="StudentClass.Register.setResult( '<?php echo StudentClass_Model_Mapper_StudentClass::GRADUATED; ?>', this );">
					    <i class="icon-trophy"></i> 
					    <?php echo $this->nomenclature()->resultClass( StudentClass_Model_Mapper_StudentClass::GRADUATED ); ?>
					</a>
				    </li>
				</ul>
			</div>
		    </th>
		</tr>
	    </thead>
	    <tbody>
		
		<?php foreach ( $this->competency as $row ) : ?>
		    <tr>
			<td style="width: 17%"><?php echo $row->external_code; ?></td>
			<td><?php echo $row->name; ?></td>
			<td style="width: 17%">
			    <?php 

				$options = array(
				    'class' => 'm-wrap span12'//,
				    //'onchange'  => 'StudentClass.Register.setDropOutCompentency( this, $( this ).closest( "table" ) )'
				);

				if ( !$this->studentClassActive()->hasAccessEdit() )
				    $options['disabled'] = true;

				echo $this->formSelect( 'status_competency[' . $row->id_competency . ']', empty( $row['status'] ) ? null : $row['status'], $options, $this->optionsStatus ); 
			    ?>
			</td>
		    </tr>
		<?php endforeach; ?>
		
	    </tbody>
	</table>
    </div>
</div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>