<div class="box-content">
     <div class="row-fluid">
	<div class="span12 text-center margin-bottom-20">
	    <button type="button" id="button-finish"
		    onClick="StudentClass.Register.finishClass();"
		    class="btn blue <?php echo $this->studentClassActive()->hasAccessEdit() ? '' : 'disabled'; ?>">
		<i class="icon-lock m-icon-white"></i>
		    Taka Klase
	    </button>
	    <?php if ( $this->access( StudentClass_Form_RegisterCancel::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
		<button type="button" onClick="StudentClass.Register.cancelClass();" class="btn red" <?php echo $this->studentClassActive()->hasAccessEdit() ? '' : 'disabled'; ?> >
		    <i class="icon-remove-sign m-icon-white"></i>
		    Kansela Klase
		</button>
	    <?php endif; ?>
	</div>
    </div>
    <div class="row-fluid">
	<table class="table table-striped table-bordered table-hover table-full-width" id="finish-list">
	    <thead>
		<tr>
		    <th style="width: 10%">#</th>
		    <th>Kriterio Sira</th>
		    <th style="width: 10%">Status</th>
		</tr>
	    </thead>
	    <tbody>
		
	    </tbody>
	</table>
    </div>
</div>