<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo ( empty( $row->external_code ) ? '' : $row->external_code . ' - ' ) . $row->scholarity; ?></td>
	<td>
	    <?php if ( $this->studentClassActive()->hasAccessEdit() && $this->access( StudentClass_Form_RegisterCourse::ID, Admin_Model_Mapper_SysUserHasForm::HAMOS ) ) : ?>
		<a class="btn red" data-course='<?php echo $row->id_relationship; ?>' onclick="StudentClass.Register.removeCourse( this );">
		    <i class="icon-remove-sign"></i>        
		</a>
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>  
		    La bele acessu                                            
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>