<div class="form-actions no-print">
    <button type="button" class="btn blue" onClick="self.print();"><i class="icon-print"></i> Print</button>
    <button type="button" class="btn red" onClick="self.close();"><i class="icon-remove-sign"></i> Taka</button>
</div>

<?php echo $this->action( 'header-report', 'index', 'default', array( 'id' => $this->class->fk_id_dec ) ); ?>

<div class="form-view">
    
    <h4 class="form-section bold">
	Klase Formasaun: <?php echo str_pad( $this->class->id_fefpstudentclass, 5, '0', STR_PAD_LEFT ); ?>
    </h4>
    
    <?php 
	
	$this->class->student_payment = (float)$this->class->student_payment;
	$this->class->subsidy = (float)$this->class->subsidy;
    
	$dataClass = array(
	    'Naran Klase'			    => $this->class->class_name,
	    'Instituisaun Ensinu'		    => $this->class->institution,
	    'Kursu'				    => ( empty( $this->class->external_code ) ? '' : $this->class->external_code  . ' - ' ) . $this->class->scholarity,
	    'Tinan Minimu'			    => $this->class->minimal_age,
	    'Tinan Masimu'			    => $this->class->maximal_age,
	    'Eskolaridade Minima'		    => empty( $this->class->minimal_scholarity ) ? null : $this->class->minimal_scholarity_code . ' - ' . $this->class->minimal_scholarity,
	    'Loron Inisiu'			    => $this->class->start_date_formated,
	    'Loron Planu Remata'		    => $this->class->schedule_finish_date_formated,
	    'Loron Real Remata'			    => $this->class->real_finish_date_formated,
	    'Oras Inisiu'			    => $this->class->time_start,
	    'Oras Remata'			    => $this->class->time_finish,
	    'Durasaun Formasaun'		    => $this->class->formation_time,
	    'Oras Formasaun Klase'		    => $this->class->formation_time_class,
	    'Durasaun Formasaun iha Liu'	    => $this->class->formation_time_outclass,
	    'Feto Nain Hira'			    => $this->class->num_women_student,
	    'Mane Nain Hira'			    => $this->class->num_men_student,
	    'Total Partisipante'		    => $this->class->num_total_student,
	    'Pagamentu Estudante'		    => empty( $this->class->student_payment ) ? null : number_format( $this->class->student_payment, 2, '.', '' ),
	    'Subsidiu'				    => empty( $this->class->subsidy ) ? null : number_format( $this->class->subsidy, 2, '.', '' ),
	    'Deskrisaun Pagamentu Partisipante'	    => $this->class->description_payment,
	    'Deskrisaun Subsidiu'		    => $this->class->description_subsity,
	    'Setor da Industria'		    => $this->class->name_classtimor,
	    'Iha Transporte'			    => empty( $this->class->transport ) ? 'SIM' : 'LAE',
	    'Iha Matabisu'			    => empty( $this->class->snack ) ? 'SIM' : 'LAE',
	    'Iha Hahan Meiu-dia'		    => empty( $this->class->lunch ) ? 'SIM' : 'LAE',
	    'Iha Hahan Meiu-dia'		    => empty( $this->class->lunch ) ? 'SIM' : 'LAE',
	    'Iha Hahan Kalan'			    => empty( $this->class->dinner ) ? 'SIM' : 'LAE',
	    'Iha Akomodasaun'			    => empty( $this->class->accommodation ) ? 'SIM' : 'LAE',
	    'Deskrisaun Jeral'                      => $this->class->description
	);
    ?>
    
    <div class="row-fluid">
	<?php 
	    $columns = 0;
	    foreach ( $dataClass as $title => $value ) : 
		
		if ( empty( $value ) )
		    continue;
		
		$columns++;
	?>
	
	    <div class="span4">
		<div class="control-group">
		    <label class="control-label bold"><?php echo $title; ?>:</label>
		    <div class="controls">
			<span class="text">
			    <?php echo $value; ?>
			</span>
		    </div>
		</div>
	    </div>
	
	    <?php if ( $columns % 3 == 0 ) : ?>
		</div>
		<div class="row-fluid">
	    <?php endif; ?>
	
	<?php endforeach; ?>
    </div>
    
    <?php if ( Zend_Auth::getInstance()->hasIdentity() ) : ?>
	<div class="row-fluid">
	    <div class="span4 offset8 text-center">
		<div class="row-fluid">
		    <?php
			$auth = Zend_Auth::getInstance()->getIdentity();
			echo $auth->name_dec . ' - ' . Zend_Date::now()->toString( 'dd/MM/yyyy' );
		    ?>
		</div>
		<div class="row-fluid">Tekniknu Profisional Empregu</div>
		<div class="row-fluid">
		    <br />
		</div>
		<div class="row-fluid">
		    <?php echo $auth->name; ?>
		</div>
	    </div>
	</div>
    <?php endif; ?>
    
</div>