<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td style="width: 8%" class="hidden-phone hidden-tablet"><?php echo str_pad( $row->id_fefpstudentclass, 5, '0', STR_PAD_LEFT ); ?></td>
	<td style="width: 10%" class="hidden-phone hidden-tablet">
	    <?php 
		if ( $row->active == 1 ) {
		    
		    if ( $row->expired ) {
			
			$label = 'warning';
			$status = 'Expirado';
		    
		    } else {
			
			$label = 'success';
			$status = 'Loke';
		    }
		    
		} else {
		    
		    $label = 'important';
		    $status = ( $row->active == 2 ) ? 'Kansela' : 'Taka';	
		}
	    ?>
	    
	    <span class="label label-<?php echo $label; ?>">
		<?php echo $status; ?>
	    </span>
	</td>
	<td><?php echo $row->class_name; ?></td>
	<td><?php echo $row->institution; ?></td>
	<td><?php echo ( empty( $row->external_code ) ? '' : $row->external_code . ' - ' ) . $row->scholarity; ?></td>
	<td style="width: 12%">
	    <?php if ( $this->access( StudentClass_Form_RegisterInformation::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
	    
		<?php if ( empty( $this->listAjax ) ) : ?>
		    <a class="btn green" href="<?php echo $this->baseUrl( 'student-class/register/edit/id/' . $row->id_fefpstudentclass ); ?>">
			<i class="icon-edit"></i>  
			Troka                                            
		    </a>
		<?php else : ?>
	    
		    <a class="btn red-stripe" target="_blank" href="<?php echo $this->baseUrl( 'student-class/register/print/id/' . $row->id_fefpstudentclass ); ?>">
			<i class="icon-eye-open"></i>                                     
		    </a>
		    
		    <?php if ( $row->active == 1 ) : ?>
			<a class="btn red action-ajax" href="javascript:;" data-id="<?php echo $row->id_fefpstudentclass; ?>">
			    <i class="icon-ok"></i>                                     
			</a>
		    <?php endif; ?>
	    
		<?php endif; ?>
	    
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>  
		    La bele acessu                                            
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>