<div class="row-fluid">
    <div class="span12">
	<div class="control-group">
	    <label class="control-label">Grupu:</label>
	    <div class="controls">
		<span class="text bold">
		    <strong><?php echo $this->group->name; ?></strong>
		</span>
	    </div>
	</div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Uzuariu Sira</div>
	    </div>
	    <div class="portlet-body form">
		<div class="row-fluid">
		    <div class="span12">
			<table class="table table-striped table-bordered table-hover table-full-width" id="user-list">
			    <thead>
				<tr>
				    <th style="width: 5%" class="no-sort">
					<input type="checkbox" onClick="General.checkAll( this );" />
				    </th>
				    <th>Uzuariu Hotu-Hotu</th>
				</tr>
			    </thead>
			    <tbody></tbody>
			</table>
		    </div>
		</div>
		<div class="row-fluid">
		    <div class="span12 text-center">
			<hr />
			<button class="btn green" type="button" onclick="Admin.Group.removeUserGroup();">
			    <i class="icon-circle-arrow-up"></i>
			</button>
			<button class="btn green" type="button" onclick="Admin.Group.insertUserGroup();">
			    <i class="icon-circle-arrow-down"></i>
			</button>
			<hr />
		    </div>
		</div>
		<div class="row-fluid">
		    <div class="span12">
			<table class="table table-striped table-bordered table-hover table-full-width" id="user-group-list">
			    <thead>
				<tr>
				    <th style="width: 5%" class="no-sort">
					<input type="checkbox" onClick="General.checkAll( this );" />
				    </th>
				    <th>Uzuariu Husi Grupu</th>
				</tr>
			    </thead>
			    <tbody></tbody>
			</table>
		    </div>
		</div>
		
	    </div>
	</div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Tipu Nota Sira</div>
	    </div>
	    <div class="portlet-body form">
		<div class="row-fluid">
		    <div class="span12">
			<table class="table table-striped table-bordered table-hover table-full-width" id="type-list">
			    <thead>
				<tr>
				    <th style="width: 5%" class="no-sort">
					<input type="checkbox" onClick="General.checkAll( this );" />
				    </th>
				    <th>Tipu Hotu-Hotu</th>
				</tr>
			    </thead>
			    <tbody></tbody>
			</table>
		    </div>
		</div>
		<div class="row-fluid">
		    <hr />
		    <div class="span12 text-center">
			<button class="btn green" type="button" onclick="Admin.Group.removeTypeNoteGroup();">
			    <i class="icon-circle-arrow-up"></i>
			</button>
			<button class="btn green" type="button" onclick="Admin.Group.insertTypeNoteGroup();">
			    <i class="icon-circle-arrow-down"></i>
			</button>
		    </div>
		    <hr />
		</div>
		<div class="row-fluid">
		    <div class="span12">
			<table class="table table-striped table-bordered table-hover table-full-width" id="type-group-list">
			    <thead>
				<tr>
				    <th style="width: 5%" class="no-sort">
					<input type="checkbox" onClick="General.checkAll( this );" />
				    </th>
				    <th>Tipu Husi Grupu</th>
				</tr>
			    </thead>
			    <tbody></tbody>
			</table>
		    </div>
		</div>
		
	    </div>
	</div>
    </div>
</div>