<div class="row-fluid">
    <div class="span3">
	<div class="control-group">
	    <label class="control-label">Numeru Rejistu:</label>
	    <div class="controls">
		<span class="text bold">
		    <strong><?php echo Client_Model_Mapper_Client::buildNumRow( $this->clientRow ); ?></strong>
		</span>
	    </div>
	</div>
    </div>
    <div class="span6">
	<div class="control-group">
	    <label class="control-label">Naran Kliente:</label>
	    <div class="controls">
		<span class="text bold">
		    <?php echo Client_Model_Mapper_Client::buildName( $this->clientRow ); ?>
		</span>
	    </div>
	</div>
    </div>
    <div class="span3">
	<div class="control-group">
	    <label class="control-label">CEOP Kliente:</label>
	    <div class="controls">
		<span class="text bold">
		    <?php echo $this->clientRow->name_dec; ?>
		</span>
	    </div>
	</div>
    </div>
</div>
<hr />
<div class="tabbable tabbable-custom boxless">
    <?php
	echo $this->tab()
		  ->addTab(
			array(
			    'ref'	    => 'updload-file',
			    'label'	    => 'Upload dokumentu',
			    'released'	    => true,
			    'content'	    => $this->render( 'document/upload-file.phtml' )
			)
		    )
		    ->addTab(
			array(
			    'ref'	    => 'list-files',
			    'label'	    => 'Lista Dokumentu Sira',
			    'released'	    => true,
			    'content'	    => $this->render( 'document/list-files.phtml' )
			)
		    );
    ?>
</div>