<?php
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_fe_registration' );
    echo $this->form->getElement( 'fk_id_perdata' );
?>
<?php if ( !empty( $this->has_contract ) ) : ?>
    <div class="alert alert-error">
	Keta edita Fixa Inskrisaun ne'e. Iha kontratu tiha ona.
    </div>
<?php endif; ?>

<div class="box-content">
    <div class="row-fluid">
	<div class="span10">
	    <?php echo $this->form->getElement( 'client_name' ); ?>
	</div>
	<div class="span1">
	    <div class="control-group">
		<label class="control-label">&#160;</label>
		<div class="controls">
		    <button type="button" id="btn-search-client" class="btn green" title="Buka Kliente" onclick="Fefop.FERegistration.searchClient()">
			<i class="icon-search"></i>  
		    </button>
		</div>
	    </div>
	</div>
	<div class="span1">
	    <div class="control-group">
		<label class="control-label">&#160;</label>
		<div class="controls">
		    <button type="button" <?php echo empty( $this->id ) ? 'disabled' : ''; ?> id="btn-print-registration" 
			    class="btn green" title="Print Fixa" onclick="Fefop.FERegistration.printRegistration()">
			<i class="icon-print"></i>  
		    </button>
		</div>
	    </div>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span6">
	    <?php echo $this->form->getElement( 'client_fone' ); ?>
	</div>
	<div class="span6">
	    <?php echo $this->form->getElement( 'email' ); ?>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span6">
	    <?php echo $this->form->getElement( 'evidence' ); ?>
	</div>
	<div class="span6">
	    <?php echo $this->form->getElement( 'electoral' ); ?>
	</div>
    </div>
    <h4>Formasaun Profisionál</h4>
    <div class="row-fluid">
	<div class="span12">
	    <table class="table table-striped table-bordered table-hover table-full-width" id="scholarity-list">
		<thead>
		    <tr>
			<th>Kategoria</th>
			<th>Kursu</th>
			<th>Instituisaun</th>
			<th style="width: 12%" class="hidden-tablet hidden-phone">Data Inisiu</th>
			<th style="width: 12%" class="hidden-tablet hidden-phone">Data Fim</th>
		    </tr>
		</thead>
		<tbody>
		    <?php
			if ( !empty( $this->client ) ) :
			    echo $this->action( 'list-scholarity', 'fe-registration', 'fefop', array( 'id' => $this->client, 'type' => Register_Model_Mapper_PerTypeScholarity::NON_FORMAL ) );
			endif;
		    ?>
		</tbody>
	    </table>
	</div>
    </div>
     <h4>Formasaun Akadémika</h4>
    <div class="row-fluid">
	<div class="span12">
	    <table class="table table-striped table-bordered table-hover table-full-width" id="formal-scholarity-list">
		<thead>
		    <tr>
			<th>Kategoria</th>
			<th>Kursu</th>
			<th>Instituisaun</th>
			<th style="width: 12%" class="hidden-tablet hidden-phone">Data Inisiu</th>
			<th style="width: 12%" class="hidden-tablet hidden-phone">Data Fim</th>
		    </tr>
		</thead>
		<tbody>
		    <?php
			if ( !empty( $this->client ) ) :
			    echo $this->action( 'list-scholarity', 'fe-registration', 'fefop', array( 'id' => $this->client, 'type' => Register_Model_Mapper_PerTypeScholarity::FORMAL ) );
			endif;
		    ?>
		</tbody>
	    </table>
	</div>
    </div>
    <!--
    <div class="row-fluid">
	<div class="span6">
	    <div class="row-fluid">
		<h4>Formação Profissional</h4>
		<div class="row-fluid">
		    <div class="span12">
			<?php echo $this->form->getSubForm('professional')->getElement( 'area' ); ?>
		    </div>
		</div>
		<div class="row-fluid">
		    <div class="span12">
			<?php echo $this->form->getSubForm('professional')->getElement( 'occupation' ); ?>
		    </div>
		</div>
		<div class="row-fluid">
		    <div class="span12">
			<?php echo $this->form->getSubForm('professional')->getElement( 'level' ); ?>
		    </div>
		</div>
	    </div>
	</div>
	<div class="span6">
	    <div class="row-fluid">
		<h4>Formação Academica</h4>
		<div class="row-fluid">
		    <div class="span12">
			<?php echo $this->form->getSubForm('formation')->getElement( 'area' ); ?>
		    </div>
		</div>
		<div class="row-fluid">
		    <div class="span12">
			<?php echo $this->form->getSubForm('formation')->getElement( 'occupation' ); ?>
		    </div>
		</div>
		<div class="row-fluid">
		    <div class="span12">
			<?php echo $this->form->getSubForm('formation')->getElement( 'level' ); ?>
		    </div>
		</div>
	    </div>
	</div>
    </div>
    -->
    <hr>
    <h4>Formasaun iha servisu fatin ne'ebe hakarak</h4>
    <div class="row-fluid">
	<div class="span6">
	    <?php echo $this->form->getSubForm('selected')->getElement( 'area' ); ?>
	</div>
	<div class="span6">
	    <?php echo $this->form->getSubForm('selected')->getElement( 'occupation' ); ?>
	</div>
    </div>

    <div class="row-fluid">
	<div class="span12">
	    <div class="portlet box blue">
		<div class="portlet-title">
		    <div class="caption"><i class="icon-building"></i>Preferénsia ba entidade promotora balun</div>
		    <div class="actions">
			<?php if ( empty( $this->has_contract ) ) : ?>
			    <a href="javascript:;" class="btn red" onclick="Fefop.FERegistration.searchEnterprise();"> 
				 <i class="icon-plus-sign"></i>
				 Empreza
			    </a>
			    <a href="javascript:;" class="btn yellow" onclick="Fefop.FERegistration.searchInstitute();"> 
				 <i class="icon-plus-sign"></i>
				 Inst. Ensinu
			    </a>
			<?php endif; ?>
		    </div>
		</div>
		<div class="portlet-body form">
		    <table class="table table-striped table-bordered table-hover table-full-width" id="entity-list">
			<thead>
			    <tr>
				<th>Entidade</th>			
				<th>Tipu</th>			
				<th style="width: 15%"></th>
			    </tr>
			</thead>
			<tbody>
			    <?php 
				if ( !empty( $this->entities ) ) :
				    foreach ( $this->entities as $entity ) :
					echo $this->action( 'add-entity', 'fe-registration', 'fefop', array( 'row' => $entity, 'has_contract' => $this->has_contract ) );
				    endforeach;
				endif; 
			    ?>
			</tbody>
		    </table>
		</div>
	    </div>
	</div>
    </div>

    <?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
</div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>