<?php $this->headScript()->appendFile( $this->baseUrl( 'public/scripts/controller/fefop/contract.js' ) );  ?>
<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-search"></i>Buka Kontratu Formasaun iha Servisu Fatin</div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<?php 
		    $this->placeholder( 'form' )->captureStart(); 
		?>

		    <div class="box-content">
			<div class="row-fluid">
			    <div class="span12">
				<?php echo $this->form->getElement( 'fk_id_perdata' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_fefpenterprise' ); ?>
			    </div>
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_fefpeduinstitution' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span3">
				<?php echo $this->form->getElement( 'identifier' ); ?>
			    </div>
			    <div class="span3">
				<?php echo $this->form->getElement( 'fk_id_scholarity_area' ); ?>
			    </div>
			    <div class="span3">
				<?php echo $this->form->getElement( 'fk_id_profocupationtimor' ); ?>
			    </div>
			    <div class="span3">
				<?php echo $this->form->getElement( 'fk_id_perlevelscholarity' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="form-actions">
				<button class="btn blue">Buka <i class="icon-search m-icon-white"></i></button>
				<button class="btn green" type="reset" id="clear">Hamoos <i class="icon-trash m-icon-white"></i></button>
				<button onclick="Fefop.Contract.printGrid( '#fe-registration-list' );" class="btn purple" type="button">Print <i class="icon-print m-icon-white"></i></button>
			    </div>
			</div>
		    </div>
		
		<?php
		    $this->placeholder( 'form' )->captureEnd();
		    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
		?>
	    </div>
	</div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Buka Fixa Inskrisaun Formasaun iha Servisu Fatin</div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="fe-registration-list">
		    <thead>
			<tr>
			    <th>Benefisiariu</th>
			    <th>Loron Rejistu</th>
			    <th class="no-sort">Action</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>