<div class="form-actions no-print">
    <button type="button" class="btn blue" onClick="self.print();"><i class="icon-print"></i> Print</button>
    <button type="button" class="btn red" onClick="self.close();"><i class="icon-remove-sign"></i> Taka</button>
</div>

<?php echo $this->action( 'header-report', 'index', 'default', array('id' => $this->user->fk_id_dec) ); ?>

<h3 class="text-center">
    Fixa Inskrisaun Formasaun iha Servisu Fatin
</h3>

<div class="form-view">
    <div class="row-fluid">

	<h4 class="form-section bold">
	    DADUS JERAIS
	</h4>

	<div class="row-fluid">
	    <div class="span12">
		<div class="control-group">
		    <label class="control-label bold">Naran Kompletu:</label>
		    <div class="controls">
			<span class="text">
			    <?php echo Client_Model_Mapper_Client::buildName( $this->registration ); ?>
			</span>
		    </div>
		</div>
	    </div>
	</div>
	
	<div class="row-fluid">
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label bold">Kontatu:</label>
		    <div class="controls">
			<span class="text">
			    <?php echo $this->registration->client_fone; ?>
			</span>
		    </div>
		</div>
	    </div>
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label bold">Naran Kompletu:</label>
		    <div class="controls">
			<span class="text">
			    <?php echo $this->registration->email; ?>
			</span>
		    </div>
		</div>
	    </div>
	</div>
	
	<div class="row-fluid">
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label bold">Kartaun Evidensia:</label>
		    <div class="controls">
			<span class="text">
			    <?php echo $this->registration->evidence; ?>
			</span>
		    </div>
		</div>
	    </div>
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label bold">Kartaun Eleitoral:</label>
		    <div class="controls">
			<span class="text">
			    <?php echo $this->registration->electoral; ?>
			</span>
		    </div>
		</div>
	    </div>
	</div>

	<div class="row-fluid">

	    <h4 class="form-section bold">
		Formasaun Profisionál
	    </h4>

	    <div class="row-fluid">
		<table class="table table-striped table-hover table-bordered">
		    <thead>
			<tr>
			    <th>Kategoria</th>
			    <th>Kursu</th>
			    <th>Instituisaun</th>
			    <th style="width: 12%" class="hidden-tablet hidden-phone">Data Inisiu</th>
			    <th style="width: 12%" class="hidden-tablet hidden-phone">Data Fim</th>
			</tr>
		    </thead>
		    <tbody>
			<?php foreach ( $this->non_formal_scholarity as $row ) : ?>
			    <tr>
				<td><?php echo $this->nomenclature()->scholarityCategory( $row->category );?></td>
				<td><?php echo ( empty( $row->external_code ) ? '' : $row->external_code . ' - ' ) . $row->scholarity; ?></td>
				<td><?php echo $row->institution; ?></td>
				<td style="width: 12%" class="hidden-tablet hidden-phone"><?php echo $row->start_date_formated; ?></td>
				<td style="width: 12%" class="hidden-tablet hidden-phone"><?php echo $row->finish_date_formated; ?></td>
			    </tr>
			<?php endforeach; ?>
		    </tbody>
		</table>
	    </div>

	</div>
	
	<div class="row-fluid">

	    <h4 class="form-section bold">
		Formasaun Akadémika
	    </h4>

	    <div class="row-fluid">
		<table class="table table-striped table-hover table-bordered">
		    <thead>
			<tr>
			    <th>Kategoria</th>
			    <th>Kursu</th>
			    <th>Instituisaun</th>
			    <th style="width: 12%" class="hidden-tablet hidden-phone">Data Inisiu</th>
			    <th style="width: 12%" class="hidden-tablet hidden-phone">Data Fim</th>
			</tr>
		    </thead>
		    <tbody>
			<?php foreach ( $this->formal_scholarity as $row ) : ?>
			    <tr>
				<td><?php echo $this->nomenclature()->scholarityCategory( $row->category );?></td>
				<td><?php echo ( empty( $row->external_code ) ? '' : $row->external_code . ' - ' ) . $row->scholarity; ?></td>
				<td><?php echo $row->institution; ?></td>
				<td style="width: 12%" class="hidden-tablet hidden-phone"><?php echo $row->start_date_formated; ?></td>
				<td style="width: 12%" class="hidden-tablet hidden-phone"><?php echo $row->finish_date_formated; ?></td>
			    </tr>
			<?php endforeach; ?>
		    </tbody>
		</table>
	    </div>

	</div>
	
	<h4 class="form-section bold">
	   Formasaun iha servisu fatin ne'ebe hakarak
	</h4>
	
	<div class="row-fluid">
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label bold">Area Kursu:</label>
		    <div class="controls">
			<span class="text">
			    <?php echo $this->groups['selected']['area_name']; ?>
			</span>
		    </div>
		</div>
	    </div>
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label bold">Dezignasaun:</label>
		    <div class="controls">
			<span class="text">
			    <?php echo $this->groups['selected']['occupation_name']; ?>
			</span>
		    </div>
		</div>
	    </div>
	</div>
	
	<div class="row-fluid">

	    <h4 class="form-section bold">
		Preferénsia ba entidade promotora balun
	    </h4>

	    <div class="row-fluid">
		<table class="table table-striped table-hover table-bordered">
		    <thead>
			<tr>
			    <th>Entidade</th>			
			    <th>Tipu</th>
			</tr>
		    </thead>
		    <tbody>
			<?php foreach ( $this->entities as $row ) : ?>
			    <tr>
				<td><?php echo $row['name']; ?></td>
				<td><?php echo ucfirst( $row['type'] ); ?></td>
			    </tr>
			<?php endforeach; ?>
		    </tbody>
		</table>
	    </div>

	</div>

    </div>
</div>

<div class="row-fluid margin-bottom-25">
</div>
<div class="row-fluid">
    <div class="span12 text-right">
	<small><em>SECRETARIA DE ESTADO PARA POLÍTICA DA FORMAÇÃO PROFISSIONAL E EMPREGO</em></small>
    </div>
</div>