<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo Client_Model_Mapper_Client::buildNumRow($row) . ' - ' . Client_Model_Mapper_Client::buildName( $row ); ?></td>
	<td><?php echo $this->date( $row->date_inserted ); ?></td>
	<td>
	    <?php if ( empty( $this->listAjax ) ) : ?>
		<?php if ( $this->access( Fefop_Form_FERegistration::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
		    <a class="btn green" href="<?php echo $this->baseUrl( 'fefop/fe-registration/edit/id/' . $row->id_fe_registration ); ?>">
			<i class="icon-edit"></i>  
			Troka                                            
		    </a>
		<?php else : ?>
		    <a class="btn red" href="javascript:;">
			<i class="icon-alert icon-lock"></i>  
			La bele acessu                                            
		    </a>
		<?php endif; ?>
	    <?php else : ?>
		<a class="btn red action-ajax" href="javascript:;" data-id="<?php echo $row->id_fe_registration; ?>">
		    <i class="icon-ok"></i>                                     
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>