<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->section_acronym; ?></td>
	<td><?php echo $row->name_disivion; ?></td>
	<td>
	    <?php echo $row->acronym; ?>
	</td>
	<td>
	    <?php if ( $this->access( Register_Form_IsicDivision::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
		<a class="btn green" href="<?php echo $this->baseUrl( 'register/isic-division/edit/id/' . $row->id_isicdivision ); ?>">
		    <i class="icon-edit"></i>  
		    Troka                                            
		</a>
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>  
		    La bele acessu                                            
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>