<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_job_list' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'list_name' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_dec' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_user' ); ?>
		</div>
		<div class="span6">
		    <div class="control-group">
			<label class="control-label optional">Status List</label>
			<div class="controls">
			    <?php if ( !empty( $this->data['printed'] ) ) : ?>
				<a class="btn disabled green" href="javascript:;">
				    <i class="icon-ok-sign"></i> 
				    Print tiha ona
				</a>
			    <?php else : ?>
				<a class="btn disabled yellow" href="javascript:;">
				    <i class="icon-warning-sign"></i> 
				    Seidauk print
				</a>
			    <?php endif; ?>
			</div>
		    </div>
		</div>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
	
	<div class="row-fluid">
	    <div class="span12">
		<div class="portlet box blue">
		    <div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i> Kliente iha Lista</div>
			<div class="actions">
			    <a href="javascript:;" class="btn red" onclick="Client.ListEvidence.addClient();"> 
				<i class="icon-plus-sign"></i>
			    </a>
			</div>
		    </div>
		    <div class="portlet-body form" style="overflow: auto">
			<table class="table table-striped table-bordered table-hover table-full-width" id="client-list-evidence">
			    <thead>
				<tr>
				    <th style="width: 5%" class="no-sort">
					<input type="checkbox" onClick="General.checkAll( this );" />
				    </th>
				    <th style="width: 18%">Numeru</th>
				    <th style="width: 40%">Kliente</th>
				    <th class="hidden-phone hidden-tablet">CEOP</th>
				    <th>Print</th>
				    <th class="no-sort">Action</th>
				</tr>
			    </thead>
			    <tbody></tbody>
			</table>
		    </div>
		</div>
	    </div>
	</div>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>