<?php 
    $this->placeholder( 'form' )->captureStart();
 ?>
    <div class="box-content">
	
	<div class="row-fluid">
	    <div class="span12">
		<div class="portlet box blue">
		    <div class="portlet-title">
			<div class="caption"><i class="icon-search"></i> Buka Lista Kartaun Evidensia</div>
			<div class="tools"><a class="collapse" href="javascript:;"></a></div>
		    </div>
		    <div class="portlet-body form">
	
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'list_name' ); ?>
			    </div>
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_dec' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_user' ); ?>
			    </div>
			    <div class="span6">
				<?php echo $this->form->getElement( 'printed' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'date_registration_ini' ); ?>
			    </div>
			    <div class="span6">
				<?php echo $this->form->getElement( 'date_registration_fim' ); ?>
			    </div>
			</div>

			<div class="row-fluid">
			    <div class="form-actions">
				<button class="btn blue">Buka <i class="icon-search m-icon-white"></i></button>
				<button class="btn green" type="reset" id="clear">Hamoos <i class="icon-trash m-icon-white"></i></button>
			    </div>
			</div>
		    </div>
		</div>
	    </div>
	</div>
	
	<div class="row-fluid">
	    <div class="span12">
		<div class="portlet box blue">
		    <div class="portlet-title">
			<div class="caption"><i class="icon-list"></i> Resultado Buka</div>
			<div class="tools"><a class="collapse" href="javascript:;"></a></div>
		    </div>
		    <div class="portlet-body form">
			<table class="table table-striped table-bordered table-hover table-full-width" id="list-evidence-list">
			    <thead>
				<tr>
				    <th>Naran Lista</th>
				    <th>Uzuariu</th>
				    <th>CEOP</th>
				    <th>Print</th>
				    <th>Data</th>
				    <th style="width: 21%" class="no-sort">Action</th>
				</tr>
			    </thead>
			    <tbody></tbody>
			</table>
		    </div>
		</div>
	    </div>
	</div>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>