<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td>
	    <input type="checkbox" checked class="clients" value="<?php echo $row->id_perdata; ?>" />
	</td>
	<td><?php echo Client_Model_Mapper_Client::buildNumRow( $row ); ?></td>
	<td><?php echo Client_Model_Mapper_Client::buildName( $row ); ?></td>
	<td class="hidden-phone hidden-tablet"><?php echo $row->name_dec; ?></td>
	<td>
	    <span class="label label-<?php echo !empty( $row->printed ) ? 'success' : 'warning'; ?>">
		<?php echo !empty( $row->printed ) ? 'Sim' : 'Lae'; ?>
	    </span>
	</td>
	<td style="width: 21%">
	    <a class="btn red" data-id="<?php echo $row->id_perdata; ?>" onclick="Client.ListEvidence.removeClient( <?php echo $row->id_perdata; ?> );">
		<i class="icon-remove-sign"></i>            
	    </a>
	</td>
    </tr>
<?php endforeach; ?>