<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->list_name; ?></td>
	<td><?php echo $row->user; ?></td>
	<td><?php echo $row->name_dec; ?></td>
	<td>
	    <span class="label label-<?php echo !empty( $row->printed ) ? 'success' : 'warning'; ?>">
		<?php echo !empty( $row->printed ) ? 'Sim' : 'Lae'; ?>
	    </span>
	<td><?php echo $this->date( $row->create_date ); ?></td>
	<td>
	    <a class="btn green" href="<?php echo $this->baseUrl( 'client/list-evidence/edit/id/' . $row->id_job_list ); ?>">
		<i class="icon-edit"></i>  
		Troka                                            
	    </a>
	</td>
    </tr>
<?php endforeach; ?>