<?php foreach ( $this->rows as $row ) : ?>

    <?php if ( empty( $row->log ) ) : ?>
	<tr>
	<?php else : ?>
	<tr class="popovers"
	    data-trigger="hover"
	    data-container="body" 
	    data-toggle="popover" 
	    data-placement="top" 
	    data-content='<p class="text-error"><?php echo $row->log; ?></p>'>	
	    <?php endif; ?>
        <td><?php echo $row->campaign_title; ?></td>
        <td><?php echo $row->contact; ?></td>
        <td><?php echo App_General_String::cleanFone( $row->target ); ?></td>
        <td><?php echo $row->type; ?></td>
        <td><?php echo $row->date_sent; ?></td>
        <td>
    	<span class="label label-<?php echo $row->status == 'S' ? 'success' : 'important'; ?>">
		<?php echo $row->status == 'S' ? 'Loos' : 'Sala'; ?>
    	</span>
        </td>
        <td><?php echo $row->attempts; ?></td>
        <td><?php echo App_General_String::cleanFone( $row->source ); ?></td>
    </tr>
<?php endforeach; ?>