<div class="box-content">

    <?php $this->placeholder( 'form' )->captureStart(); ?>

	<?php 
	    echo $this->form->getElement( 'path' ); 
	    echo $this->form->getElement( 'title' ); 
	    echo $this->form->getElement( 'orientation' ); 
	?>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>

    <?php
	$this->placeholder( 'form' )->captureEnd();
	echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
    ?>

</div>

<div class="row-fluid" id="report-iframe">
</div>