<div class="box-content">

    <?php $this->placeholder( 'form' )->captureStart(); ?>

	<?php 
	    echo $this->form->getElement( 'path' ); 
	    echo $this->form->getElement( 'title' ); 
	    echo $this->form->getElement( 'orientation' ); 
	?>

	<div class="row-fluid">
	    <div class="span6">
		<?php echo $this->form->getElement( 'campaign_title' ); ?>
	    </div>
	    <div class="span6">
		<?php echo $this->form->getElement( 'fk_id_department' ); ?>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="span6">
		<?php echo $this->form->getElement( 'fk_id_campaign_type' ); ?>
	    </div>
	    <div class="span6">
		<?php echo $this->form->getElement( 'status_campaign' ); ?>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="control-group span12">
		<label class="control-label">Grupu</label>
		<div class="container-checkbox"><?php echo $this->form->getElement( 'group' ); ?></div>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>

    <?php
	$this->placeholder( 'form' )->captureEnd();
	echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
    ?>

</div>

<div class="row-fluid" id="report-iframe">
</div>