<div class="filters">
    <p><?php echo $this->filterReport( $this->data['filters'] ); ?></p>
</div>

<table class="relatorio">
    <thead>
	<tr>
	    <th>Departamentu</th>
	    <th>Uzuariu</th>
	    <th>Data</th>
	    <th>Total</th>
	    <th>Folin Hira</th>
	</tr>
    </thead>
    <tbody>
	<?php foreach ( $this->data['rows'] as $row ) : ?>
	    <tr class="<?php echo $this->cycle( array( 'one', 'two') )->next(); ?>">
		<td><?php echo $row->department; ?></td>
		<td><?php echo $row->user; ?></td>
		<td><?php echo $this->date( $row->date_insert, 'dd/MM/yyyy HH:mm'); ?></td>
		<td><?php echo $row->amount; ?></td>
		<td><?php echo $this->currency( $row->value , 'en_US' ); ?></td>
	    </tr>
	<?php endforeach; ?>
    </tbody>
    <tfoot>
	<tr>
	    <th colspan="3">Total</th>
	    <th><?php echo $this->data['amount']; ?></th>
	    <th><?php echo $this->currency( $this->data['total'] , 'en_US' ); ?></th>
	</tr>
    </tfoot>
</table>