<div class="filters">
    <p><?php echo $this->filterReport( $this->data['filters'] ); ?></p>
</div>

<table class="relatorio">
    <thead>
	<tr>
	    <th>Kampanha</th>
	    <th>Departamentu</th>
	    <th>Kontatu</th>
	    <th>Telemóvel</th>
	    <th>Tipu</th>
	    <th>Data</th>
	    <th>Status</th>
	    <th>Koko Dala hira</th>
	    <th>Husi</th>
	    <th>Kustu</th>
	</tr>
    </thead>
    <tbody>
	<?php foreach ( $this->data['rows'] as $row ) : ?>
	    <tr class="<?php echo $this->cycle( array( 'one', 'two') )->next(); ?>">
		<td><?php echo $row->campaign_title; ?></td>
		<td><?php echo $row->department; ?></td>
		<td><?php echo $row->contact; ?></td>
		<td><?php echo App_General_String::cleanFone( $row->target ); ?></td>
		<td><?php echo $row->type; ?></td>
		<td><?php echo $row->date_sent; ?></td>
		<td><?php echo $row->status == 'S' ? 'Loos' : 'Sala'; ?></td>
		<td><?php echo $row->attempts; ?></td>
		<td><?php echo App_General_String::cleanFone( $row->source ); ?></td>
		<td><?php echo $this->currency( $row->cost , 'en_US' ); ?></td>
	    </tr>
	<?php endforeach; ?>
    </tbody>
    <tfoot>
	<tr>
	    <th colspan="8">Total</th>
	    <th><?php echo count( $this->data['rows'] ); ?></th>
	    <th><?php echo $this->currency( $this->data['total'] , 'en_US' ); ?></th>
	</tr>
    </tfoot>
</table>