<div class="row-fluid well">
    <div class="row-fluid">
	<div class="span6">
	    <div class="control-group">
		<label class="control-label">Setor de indústria:</label>
		<div class="controls">
		    <span class="text bold">
			<strong><?php echo $this->enterprise->name_classtimor; ?></strong>
		    </span>
		</div>
	    </div>
	</div>
	<div class="span6">
	    <?php if ( !empty( $this->address ) ) : ?>
		<h4>Localização</h4>
		<div class="control-group">
		    <label class="control-label">Distrito:</label>
		    <div class="controls">
			<span class="text bold">
			    <strong><?php echo $this->address->District; ?></strong>
			</span>
		    </div>
		</div>
		<div class="control-group">
		    <label class="control-label">SubDistrito:</label>
		    <div class="controls">
			<span class="text bold">
			    <strong><?php echo $this->address->sub_district; ?></strong>
			</span>
		    </div>
		</div>
		<div class="control-group">
		    <label class="control-label">Suco:</label>
		    <div class="controls">
			<span class="text bold">
			    <strong><?php echo $this->address->sucu; ?></strong>
			</span>
		    </div>
		</div>
	    <?php endif; ?>
	</div>
    </div>
    <div class="row-fluid">
	<?php if ( !empty( $this->address ) ) : ?>
	    <div class="span9">
		<div class="control-group">
		    <label class="control-label">Responsável da Instituição:</label>
		    <div class="controls">
			<span class="text bold">
			    <strong><?php echo $this->staff->staff_name; ?></strong>
			</span>
		    </div>
		</div>
	    </div>
	    <div class="span3">
		<div class="control-group">
		    <label class="control-label">Kargo:</label>
		    <div class="controls">
			<span class="text bold">
			    <strong><?php echo $this->staff->post; ?></strong>
			</span>
		    </div>
		</div>
	    </div>
	<?php endif; ?>
    </div>
</div>