<table class="table table-striped table-bordered table-hover table-full-width">
    <thead>
	<tr>
	    <th>Item</th>
	    <th style="width: 10%">Qtd.</th>
	    <th style="width: 12%">Folin Ketak</th>			
	    <th style="width: 10%">Folin Total</th>			
	    <th>Komentariu</th>
	    <th style="width: 5%"></th>
	</tr>
    </thead>
    <tbody>
	<?php 
	    if ( !empty( $this->items ) ) {
		foreach ( $this->items as $itemExpense )
		    echo $this->action( 'add-detailed-expense', 'etc-contract', 'fefop', array( 'row' => $itemExpense ) );
	    }
	?>
    </tbody>
</table>