<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_per_contract' );
    echo $this->form->getElement( 'fk_id_fefop_contract' );
    echo $this->form->getElement( 'fk_id_fefop_modules' );
    echo $this->form->getElement( 'fk_id_fefpenterprise' );
 ?>

    <?php echo $this->fefopContract()->getMessages(); ?>

    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span4">
		    <?php echo $this->form->getElement( 'fk_id_adddistrict' ); ?>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'fk_id_addsubdistrict' ); ?>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'fk_id_addsucu' ); ?>
		</div>
	    </div>
	    
	    <div class="row-fluid">
		<div class="span4">
		    <?php echo $this->form->getElement( 'fk_id_per_area' ); ?>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'date_start' ); ?>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'date_finish' ); ?>
		</div>
	    </div>
	    
	     <div class="row-fluid">
		<div class="span12">
		    <?php echo $this->form->getElement( 'description' ); ?>
		</div>
	    </div>
	    
	    <div class="row-fluid">
		<div class="span10">
		    <?php echo $this->form->getElement( 'enterprise' ); ?>
		</div>
		<div class="span1">
		    <div class="control-group">
			<label class="control-label">&#160;</label>
			<div class="controls">
			    <button type="button" id="btn-search-enterprise" class="btn green" title="Buka Empreza" onclick="Fefop.ETCContract.searchEnterprise()">
				 <i class="icon-search"></i>  
			     </button>
			</div>
		    </div>
		</div>
		<div class="span1">
		    <div class="control-group">
			<label class="control-label">&#160;</label>
			<div class="controls">
			    <button type="button" id="btn-export-contract" disabled="disabled" 
				    class="btn green" title="Exporta Kontratu" onclick="Fefop.ETCContract.exportContract()">
				 <i class="icon-print"></i>  
			     </button>
			</div>
		    </div>
		</div>
	    </div>
	    
	    <div class="row-fluid" id="detail-enterprise">
		
	    </div>
	    
	    <div class="row-fluid">
		<div class="span12">
		    <div class="portlet box blue ">
			<div class="portlet-title">
			    <div class="caption"><i class="icon-dollar"></i>Rúbrika ba despeza - Totál</div>
			</div>
			<div class="portlet-body form">
			    <table class="table table-striped table-bordered table-hover table-full-width" id="expense-list">
				<thead>
				    <tr>
					<th style="width: 7%">#</th>
					<th>Komponente</th>			
					<th>Tipu</th>			
					<th style="width: 15%">Folin Hira</th>
				    </tr>
				</thead>
				<tbody>
				    <?php 
					$count = 'A';
					$optionsStatus = array(
					    ''	=> 'Hili ida',
					    'I' => 'Item',
					    'E' => 'Empregu lokal',
					    'F' => 'Formasaun Profissional'
					);
					$optionsSelect = array( 'class' => 'm-wrap span12 expense-type' );
					
					$attribsText = array(
					    'class'	=> 'm-wrap span12 focused cost-expense submit-field money-mask',
					    'readonly'  => true
					);
					
					foreach ( $this->expenses as $expense ) : 
				    ?>
					<tr>
					    <td><?php echo $count++; ?>.</td>
					    <td><?php echo str_replace( '&', ' ', $expense->description ); ?></td>
					    <td>
						<?php
						    $type = null;
						    if ( !empty( $this->expense_detailed[$expense->id_budget_category] ) ) {
							
							switch ( $this->expense_detailed[$expense->id_budget_category]['type'] ) {
							    case 'item':
								$type = 'I';
								break;
							    case 'employment':
								$type = 'E';
								break;
							    case 'formation':
								$type = 'F';
								break;
							}
							
							$optionsSelect['readonly'] = true;
						    } else
							unset( $optionsSelect['readonly'] );
						    
						    $optionsSelect['data-expense'] = $expense->id_budget_category;

						    echo $this->formSelect( 'expense[' . $expense->id_budget_category . '][type]', $type, $optionsSelect, $optionsStatus ); 
						?>
					    </td>
					    <td>
						<?php
						    $amount = 0;
						    if ( !empty( $expense->amount ) )
							$amount = $expense->amount;

						    $amount = number_format( $amount, 2, '.', '.' );
						    
						    $attribsTotal = $attribsText;
						    $attribsTotal['id'] = 'total_expense_' . $expense->id_budget_category;
						    
						    echo $this->formText( 'expense[' . $expense->id_budget_category . '][total]', $amount, $attribsTotal );  
						 ?>
					    </td>
					</tr>
				    <?php endforeach; ?>
				</tbody>
				<tfoot>
				    <tr>
					<td colspan="3">TOTAL</td>
					<td>
					    <?php echo $this->form->getElement( 'amount' ); ?>
					</td>
				    </tr>
				</tfoot>
			    </table>
			</div>
		    </div>
		</div>
	    </div>
	    
	    <div class="row-fluid">
		<div class="span12">
		    <div class="portlet box grey ">
			<div class="portlet-title">
			    <div class="caption"><i class="icon-dollar"></i>Rúbrika Detalladu</div>
			</div>
			<div class="portlet-body form">
			    <?php 
				$count = 'A';
				foreach ( $this->expenses as $expense ) : 
			    ?>
				<div class="row-fluid">
				    <div class="span12">
					<div class="portlet box light-grey expense-portlet" id="expense-portlet-<?php echo $expense->id_budget_category; ?>" >
					    <input type="hidden" name="expense-detailed" class="expense-id" value="<?php echo $expense->id_budget_category; ?>" />
					    <div class="portlet-title">
						<div class="caption" style="font-size: 11px">
						    <strong><?php echo ( $count++ ) . ' - ' . str_replace( '&', ' ', $expense->description ); ?></strong>
						</div>
						<div class="tools">
						    <?php if  ( empty( $this->expense_detailed[$expense->id_budget_category] ) ) : ?>
							<a href="javascript:;" class="expand"></a>
						    <?php else : ?>
							<a href="javascript:;" class="collapse"></a>
						    <?php endif; ?>
						</div>
						<div class="actions">
						    <button type="button" <?php echo empty( $this->expense_detailed[$expense->id_budget_category] ) ? 'disabled="disabled"' : ''; ?>
							    id="btn-add-expense-detailed" class="btn mini green" onclick="Fefop.ETCContract.addDetailedExpense( event, this );"> 
							 <i class="icon-plus-sign"></i>
							 Aumenta
						    </button>
						</div>
					    </div>
					    <div class="portlet-body form <?php echo empty( $this->expense_detailed[$expense->id_budget_category] ) ? 'hide' : ''; ?>">
						<?php 
						    if  ( !empty( $this->expense_detailed[$expense->id_budget_category] ) ) {
							switch ( $this->expense_detailed[$expense->id_budget_category]['type'] ) {
							    case 'item':
								echo $this->action( 'header-item', 'etc-contract', 'fefop', array( 'items' => $this->expense_detailed[$expense->id_budget_category]['items'] ) );
								break;
							    case 'employment':
								echo $this->action( 'header-employment', 'etc-contract', 'fefop', array( 'items' => $this->expense_detailed[$expense->id_budget_category]['items'] ) );
								break;
							    case 'formation':
								echo $this->action( 'header-formation', 'etc-contract', 'fefop', array( 'items' => $this->expense_detailed[$expense->id_budget_category]['items'] ) );
								break;
							}
						    }
						?>
					    </div>
					</div>
				    </div>
				</div>
			    <?php endforeach; ?>
			</div>
		    </div>
		</div>
	    </div>
	    
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>