<?php $this->headScript()->appendFile( $this->baseUrl( 'public/scripts/controller/fefop/contract.js' ) );  ?>
<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-search"></i>Buka Kontratu Empregu no Turismu Komunitariu</div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<?php 
		    $this->placeholder( 'form' )->captureStart(); 
		    echo $this->form->getElement( 'minimum_amount' );
		    echo $this->form->getElement( 'maximum_amount' );
		    echo $this->form->getElement( 'fk_id_fefop_modules' );
		?>

		    <div class="box-content">
			<div class="row-fluid">
			    <div class="span12">
				<?php echo $this->form->getElement( 'fk_id_fefpenterprise' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span4">
				<?php echo $this->form->getElement( 'fk_id_adddistrict' ); ?>
			    </div>
			    <div class="span4">
				<?php echo $this->form->getElement( 'fk_id_addsubdistrict' ); ?>
			    </div>
			    <div class="span4">
				<?php echo $this->form->getElement( 'fk_id_addsucu' ); ?>
			    </div>
			</div>
                        <div class="row-fluid">
                            <div class="span4">
                                <?php echo $this->form->getElement( 'fk_id_per_area' ); ?>
                            </div>
                            <div class="span4">
                                <?php echo $this->form->getElement( 'date_start' ); ?>
                            </div>
                            <div class="span4">
                                <?php echo $this->form->getElement( 'date_finish' ); ?>
                            </div>
                        </div>
			<div class="row-fluid">
			     <div class="span12">
				<div class="control-group">
				    <label class="control-label optional margin-bottom-10-">Kustu total</label>
				    <div class="controls">
					<div id="slider-amount" class="slider bg-blue"></div>
					<div class="slider-value">
					    Kustu:
					    <span id="slider-age-amount">
						<?php echo $this->currency( 0 ) . ' - ' . $this->currency( 100000 ); ?>
					    </span>
					</div>
				    </div>
				</div>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="form-actions">
				<button class="btn blue">Buka <i class="icon-search m-icon-white"></i></button>
				<button class="btn green" type="reset" id="clear">Hamoos <i class="icon-trash m-icon-white"></i></button>
				<button onclick="Fefop.Contract.printGrid( '#etc-contract-list' );" class="btn purple" type="button">Print <i class="icon-print m-icon-white"></i></button>
			    </div>
			</div>
		    </div>
		
		<?php
		    $this->placeholder( 'form' )->captureEnd();
		    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
		?>
	    </div>
	</div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Buka Kontratu Empregu no Turismu Komunitariu</div>
		<div class="tools"><a href="javascript:;" class="collapse"></a></div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="etc-contract-list">
		    <thead>
			<tr>
			    <th>Kontratu</th>
			    <th>Empreza</th>
			    <th>Distritu</th>
			    <th>Area</th>
			    <th class="date-column">Loron Inisiu</th>
			    <th class="date-column">Loron Remata</th>
			    <th>Total</th>
			    <th>Status</th>
			    <th class="no-sort">Action</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>