<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_fefpeduinstitution' );
    echo $this->form->getElement( 'id_relationship' );
    echo $this->form->getElement( 'scholarity_classification' );
    echo $this->form->getElement( 'step' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span4">
		    <?php echo $this->form->getElement( 'fk_id_pertypescholarity' ); ?>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'category' ); ?>
		</div>
		<div class="span4">
		    <?php echo $this->form->getElement( 'fk_id_scholarity' ); ?>
		</div>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Kursu Sira</div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="course-list">
		    <thead>
			<tr>
			    <th>Tipu Kursu</th>
			    <th style="width: 40%">Kursu</th>
			    <th>Kategoria</th>
			    <!--<th>Klasifikasaun</th>-->
			    <th>Action</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>