<div class="form-view">

    <div class="row-fluid">
	<div class="span8">
	    <div class="control-group">
		<label class="control-label bold">Naran Instituisaun Ensinu:</label>
		<div class="controls">
		    <span class="text">
			<?php echo $this->row->institution; ?>
		    </span>
		</div>
	    </div>
	</div>
	<div class="span2">
	    <div class="control-group">
		<label class="control-label bold">Data Visita:</label>
		<div class="controls">
		    <span class="text">
			<?php echo $this->date( $this->row->date_visit ); ?>
		    </span>
		</div>
	    </div>
	</div>
	<div class="span2">
	    <div class="control-group">
		<label class="control-label bold">Data Rejistu:</label>
		<div class="controls">
		    <span class="text">
			<?php echo $this->date( $this->row->date_registration ); ?>
		    </span>
		</div>
	    </div>
	</div>
    </div>

    <div class="row-fluid">
	<div class="span7">
	    <div class="control-group">
		<label class="control-label bold">CEOP:</label>
		<div class="controls">
		    <span class="text">
			<?php echo $this->row->name_dec; ?>
		    </span>
		</div>
	    </div>
	</div>
	<div class="span3">
	    <div class="control-group">
		<label class="control-label bold">Tipu Instituisaun:</label>
		<div class="controls">
		    <span class="text">
			<?php echo $this->row->type_institution; ?>
		    </span>
		</div>
	    </div>
	</div>
	<div class="span2">
	    <div class="control-group">
		<label class="control-label bold">Rejistu?</label>
		<div class="controls">
		    <span class="text">
			<?php echo $this->row->register ? 'Sim' : 'Lae'; ?>
		    </span>
		</div>
	    </div>
	</div>
    </div>
    
    <?php if ( $this->contact->count() > 0 ) : ?>
    
	<h4 class="form-section bold">
	    Contatu
	</h4>
    
	<div class="row-fluid">
	    <div class="span7">
		<strong>Naran</strong>
	    </div>
	    <div class="span2">
		<strong>Telemóvel</strong>
	    </div>
	    <div class="span3">
		<strong>E-mail</strong>
	    </div>
	</div>

	<?php foreach ( $this->contact as $contact ) : ?>
	    <div class="row-fluid">
		<div class="span7"><?php echo $contact->contact_name; ?></div>
		<div class="span2"><?php echo $contact->cell_fone; ?></div>
		<div class="span3"><?php echo $contact->email; ?></div>
	    </div>
	<?php endforeach; ?>
    
    <?php endif; ?>
</div>

<h4 class="form-section bold">
    Kursu
</h4>

<div class="row-fluid">
    <div class="span12">
	<table class="table table-striped table-bordered table-hover table-full-width">
	    <thead>
		<tr>
		    <th>Tipu Kursu</th>
		    <th style="width: 40%">Kursu</th>
		    <th>Kategoria</th>
		</tr>
	    </thead>
	    <tbody>
		<?php foreach ( $this->courses as $row ) : ?>
		    <tr>
			<td><?php echo $row->type_scholarity; ?></td>
			<td style="width: 40%"><?php echo ( empty( $row->external_code ) ? '' : $row->external_code . ' - ' ) . $row->scholarity; ?></td>
			<td><?php echo $this->nomenclature()->scholarityCategory( $row->category ); ?></td>
		    </tr>
		<?php endforeach; ?>
	    </tbody>
	</table>
    </div>
</div>