<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_fefpeduinstitution' );
    echo $this->form->getElement( 'step' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'institution' ); ?>
		</div>
		<div class="span3">
		    <?php echo $this->form->getElement( 'date_visit' ); ?>
		</div>
		<div class="span3">
		    <?php echo $this->form->getElement( 'date_registration' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'num_register' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'year_start' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_typeinstitution' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_sysuser' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_dec' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'register' ); ?>
		</div>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>