<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->staff_name; ?></td>
	<td><?php echo $row->gender == 'M' ? 'MANE' : 'FETO'; ?></td>
	<td><?php echo $row->post; ?></td>
	<td>
	    <?php if ( $this->access( Register_Form_EducationInstitutionStaff::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
		<a class="btn green" data-staff='<?php echo $row->id_staff; ?>' onclick="Register.EducationInstitute.editStaff( this );">
		    <i class="icon-edit"></i>                                          
		</a>
		<a class="btn red" data-staff='<?php echo $row->id_staff; ?>' onclick="Register.EducationInstitute.removeStaff( this );">
		    <i class="icon-remove-sign"></i>                                         
		</a>
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>  
		    La bele acessu                                            
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>