<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->type_scholarity; ?></td>
	<td style="width: 40%"><?php echo ( empty( $row->external_code ) ? '' : $row->external_code . ' - ' ) . $row->scholarity; ?></td>
	<td><?php echo $this->nomenclature()->scholarityCategory( $row->category ); ?></td>
	<!--<td><?php //echo $this->nomenclature()->scholarityClassification( $row->scholarity_classification ); ?></td>-->
	<td>
	    <?php if ( $this->access( Register_Form_EducationInstitutionCourse::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
		<!--<a class="btn green" data-course='<?php echo $row->fk_id_scholarity; ?>' onclick="Register.EducationInstitute.editCourse( this );">
		    <i class="icon-edit"></i>                      
		</a>
		-->
		<a class="btn red" data-course='<?php echo $row->fk_id_scholarity; ?>' onclick="Register.EducationInstitute.removeCourse( this );">
		    <i class="icon-remove-sign"></i>         
		</a>
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>  
		    La bele acessu                                            
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>