<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->staff_name; ?></td>
	<td><?php echo ( empty( $row->external_code ) ? '' : $row->external_code . ' - ' ) . $row->scholarity; ?></td>
	<td>
	    <?php if ( $this->access( Register_Form_EducationInstitutionQualification::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
		<a class="btn red" data-qualification='<?php echo $row->id_relationship; ?>' onclick="Register.EducationInstitute.removeQualification( this );">
		    <i class="icon-remove-sign"></i>                                         
		</a>
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>  
		    La bele acessu                                            
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>