<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_fefpeduinstitution' );
    echo $this->form->getElement( 'step' );
?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="span12">
		<?php echo $this->form->getElement( 'fk_id_staff' ); ?>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="span6">
		<?php echo $this->form->getElement( 'category_qualification' ); ?>
	    </div>
	    <div class="span6">
		<?php echo $this->form->getElement( 'fk_id_perscholarity_staff' ); ?>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Kualifikasaun Sira</div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="qualification-list">
		    <thead>
			<tr>
			    <th>Naran Funcionariu</th>
			    <th>Kualifikasaun</th>
			    <th>Action</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>