<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_fefpeduinstitution' );
    echo $this->form->getElement( 'id_staff' );
    echo $this->form->getElement( 'step' );
    echo $this->form->getElement( 'fk_id_perdata' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span6">
		    <div class="span10">
			<?php echo $this->form->getElement( 'staff_name' ); ?>
		    </div>
		    <div class="span2">
			<div class="control-group">
			    <label class="control-label">&nbsp;</label>
			    <div class="controls">
				<button id="btn-search-client" class="btn red" onclick="Register.EducationInstitute.searchClient()" type="button"><i class="icon-search m-icon-white"></i></button>
			    </div>
			</div>
		    </div>
		</div>
		<div class="span6">
		    <div class="span6">
			<?php echo $this->form->getElement( 'birth_date' ); ?>
		    </div>
		    <div class="span6">
			 <?php echo $this->form->getElement( 'gender' ); ?>
		    </div>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'post' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'position' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span12">
		    <?php echo $this->form->getElement( 'description' ); ?>
		</div>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>

<div class="row-fluid">
    <div class="span12">
	<div class="portlet box blue ">
	    <div class="portlet-title">
		<div class="caption"><i class="icon-reorder"></i>Resultadu Funcionariu Sira</div>
	    </div>
	    <div class="portlet-body form">
		<table class="table table-striped table-bordered table-hover table-full-width" id="staff-list">
		    <thead>
			<tr>
			    <th>Naran Funcionariu</th>
			    <th>Seksu</th>
			    <th>Kargo</th>
			    <th>Action</th>
			</tr>
		    </thead>
		    <tbody></tbody>
		</table>
	    </div>
	</div>
    </div>
</div>