<div class="row-fluid">
    <div class="span12">
	<form id="fileupload" action="<?php echo $this->baseUrl( 'fefop/document/save' ); ?>" method="POST" enctype="multipart/form-data">
	    <input type="hidden" name="contract" id="contract" value="<?php echo $this->id; ?>" />
	    <div class="row-fluid fileupload-buttonbar">
		<div class="span7">
		    <!-- The fileinput-button span is used to style the file input field as button -->
		    <span class="btn green fileinput-button">
			<i class="icon-plus icon-white"></i>
			<span>Add Dokumentu</span>
			<input type="file" name="files[]" multiple="multiple" />
		    </span>
		    <button type="submit" class="btn blue start">
			<i class="icon-upload icon-white"></i>
			<span>Hahu upload</span>
		    </button>
		    <button type="reset" class="btn yellow cancel">
			<i class="icon-ban-circle icon-white"></i>
			<span>Kansela upload</span>
		    </button>
		    <button type="button" class="btn red delete">
			<i class="icon-trash icon-white"></i>
			<span>Hamoos</span>
		    </button>
		    <input type="checkbox" class="toggle fileupload-toggle-checkbox" />
		</div>
		<!-- The global progress information -->
		<div class="span5 fileupload-progress fade">
		    <!-- The global progress bar -->
		    <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
			<div class="bar" style="width:0%;"></div>
		    </div>
		    <!-- The extended global progress information -->
		    <div class="progress-extended"></div>
		</div>
	    </div>
	    <!-- The loading indicator is shown during file processing -->
	    <div class="fileupload-loading"></div>
	    <!-- The table listing the files available for upload/download -->
	    <table role="presentation" class="table table-striped">
		<tbody class="files"></tbody>
	    </table>
	</form>
    </div>
</div>