<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_perscholarity' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_pertypescholarity' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_scholarity_area' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'scholarity' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'Title' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'category' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'external_code' ); ?>
		</div>
	    </div>
	    <div class="row-fluid <?php echo $this->showlevel ? '' : 'hide' ; ?>">
		<div class="span6">
		    <?php echo $this->form->getElement( 'fk_id_perlevelscholarity' ); ?>
		</div>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>

<?php if ( !empty( $this->competencies ) && $this->competencies->count() > 0 ) : ?>
    <div class="row-fluid">
	<div class="span12">
	    <div class="portlet box blue ">
		<div class="portlet-title">
		    <div class="caption"><i class="icon-user"></i>Lista Kompetensia sira</div>
		    <div class="tools"><a href="javascript:;" class="collapse"></a></div>
		</div>
		<div class="portlet-body form">
		    <table class="table table-striped table-bordered table-hover table-full-width" id="competency-list">
			<thead>
			    <tr>
				<th>Kodigu</th>
				<th>Kompetensia</th>			
			    </tr>
			</thead>
			<tbody>
			    <?php foreach ( $this->competencies as $competency ) : ?>
				<tr>
				    <td><?php echo $competency->external_code; ?></td>
				    <td><?php echo $competency->name; ?></td>
				</tr>
			    <?php endforeach; ?>
			</tbody>
		    </table>
		</div>
	    </div>
	</div>
    </div>
<?php endif; ?>