<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->id_perscholarity; ?></td>
	<td><?php echo $row->type_scholarity; ?></td>
	<td><?php echo ( empty( $row->external_code ) ? '' : $row->external_code . ' - ' ) . $row->scholarity; ?></td>
	<td><?php echo $row->scholarity_area; ?></td>
	<td><?php echo $this->nomenclature()->scholarityCategory( $row->category ); ?></td>
	<td><?php echo empty( $row->level_scholarity ) ? '-' : $row->level_scholarity; ?></td>
	<td>
	    <?php if ( $this->access( Register_Form_Scholarity::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
		<a class="btn green" href="<?php echo $this->baseUrl( 'register/scholarity/edit/id/' . $row->id_perscholarity ); ?>">
		    <i class="icon-edit"></i>  
		    Troka                                            
		</a>
	    <?php else : ?>
		<a class="btn red" href="javascript:;">
		    <i class="icon-alert icon-lock"></i>  
		    La bele acessu                                            
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>