<?php
    $this->headLink()->appendStylesheet( $this->baseUrl( 'public/template/plugins/fullcalendar/fullcalendar/fullcalendar.css' ), '' );
    $this->headScript()->appendFile( $this->baseUrl( 'public/template/plugins/fullcalendar/fullcalendar/fullcalendar.min.js' ) );
?>
<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_annual_planning' );
    echo $this->form->getElement( 'fk_id_fefpeduinstitution' );
 ?>
    <div class="row-fluid">
	<div class="span11">
	    <?php echo $this->form->getElement( 'institution' ); ?>
	</div>
	<div class="span1">
	    <div class="control-group">
		<label class="control-label">&#160;</label>
		<div class="controls">
		    <a class="btn green" title="Buka Instituisaun" href="javascript:;" 
			onclick="Fefop.FPAnnualPlanning.searchInstitute()">
			 <i class="icon-search"></i>  
		     </a>
		</div>
	    </div>
	</div>
	
    </div>
    <div class="row-fluid">
	<div class="span4">
	    <?php echo $this->form->getElement( 'year_planning' ); ?>
	</div>
	<div class="span4">
	    <?php echo $this->form->getElement( 'total_students' ); ?>
	</div>
	<div class="span4">
	    <?php echo $this->form->getElement( 'total_cost' ); ?>
	</div>
    </div>

    <div class="row-fluid">
	<div class="span12">
	    <div class="portlet box yellow">
		<div class="portlet-title">
		    <div class="caption"><i class="icon-reorder"></i>Calendariu</div>
		    <div class="actions">
			<button type="button" id="btn-print" class="btn mini blue" disabled onclick="Fefop.FPAnnualPlanning.printContract();"> 
			     <i class="icon-print"></i>
			     Print
			</button>
			<button type="button" id="btn-add-planning" class="btn mini green" disabled onclick="Fefop.FPAnnualPlanning.addNewEvent();"> 
			     <i class="icon-plus-sign"></i>
			     Aumenta Formasaun
			</button>
		    </div>
		</div>
                <div class="portlet-body form">
		    <div id="calendar-planning"></div>
		</div>
	    </div>
	</div>
    </div>

<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>