<div class="form-actions no-print">
    <button type="button" class="btn blue" onClick="self.print();"><i class="icon-print"></i> Print</button>
    <button type="button" class="btn red" onClick="self.close();"><i class="icon-remove-sign"></i> Taka</button>
</div>

<?php echo $this->action( 'header-report', 'index', 'default', array( 'id' => $this->user->fk_id_dec ) ); ?>

<h3 class="text-center">
    PLANO DE FORMAÇÃO ANUAL
</h3>

<div class="form-view">
    <div class="row-fluid">
	    
	<h4 class="form-section bold">
	    DADUS JERAIS
	</h4>

	<div class="row-fluid">
	    <div class="span12">
		<div class="control-group">
		    <label class="control-label bold">Centro de formação acreditado:</label>
		    <div class="controls">
			<span class="text">
			    <?php echo $this->planning->institution; ?>
			</span>
		    </div>
		</div>
	    </div>
	</div>
	<div class="row-fluid">
	    <div class="span4">
		<div class="control-group">
		    <label class="control-label bold">Tinan:</label>
		    <div class="controls">
			<span class="text">
			    <?php echo $this->planning->year_planning; ?>
			</span>
		    </div>
		</div>
	    </div>
	    <div class="span4">
		<div class="control-group">
		    <label class="control-label bold">Alunu Nain Hira</label>
		    <div class="controls">
			<span class="text">
			    <?php echo $this->planning->total_students; ?>
			</span>
		    </div>
		</div>
	    </div>
	    <div class="span4">
		<div class="control-group">
		    <label class="control-label bold">Kustu total estimado</label>
		    <div class="controls">
			<span class="text">
			    <?php echo $this->currency( $this->planning->total_cost ); ?>
			</span>
		    </div>
		</div>
	    </div>
	</div>
    </div>
    
     <div class="row-fluid">
	    
	<h4 class="form-section bold">
	    KURSU SIRA PLANEADU
	</h4>
	 
	 <div class="row-fluid">
	    <table class="table table-striped table-hover table-bordered">
		    <thead>
			    <tr>
				<th>Kursu</th>
				<th>Loron Inisiu</th>
				<th>Loron Remata</th>
				<th>Mane Nain Hira</th>
				<th>Feto Nain Hira</th>
				<th>Total Nain Hira</th>
				<th>Kustu Unitariu</th>
				<th>Kustu Total Estimado</th>
			    </tr>
		    </thead>
		    <tbody>
			<?php foreach ( $this->events as $key => $event ) : ?>
			    <tr>
				<td><?php echo ( empty( $event->external_code ) ? '' : $event->external_code . ' - ' ) . $event->scholarity; ?></td>
				<td><?php echo $this->date( $event->date_start ); ?></td>
				<td><?php echo $this->date( $event->date_finish ); ?></td>
				<td><?php echo $event->total_man; ?></td>
				<td><?php echo $event->total_woman; ?></td>
				<td><?php echo $event->students_course; ?></td>
				<td><?php echo $this->currency( $event->unit_cost ); ?></td>
				<td><?php echo $this->currency( $event->cost_course ); ?></td>
			    </tr>

			<?php endforeach; ?>
		    </tbody>
	    </table>
	</div>
	 
     </div>
    
    <div class="row-fluid margin-bottom-25">
	    
	<div class="row-fluid">
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label bold">Representante do Centro de Formação</label>
		</div>
	    </div>
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label bold">O Presidente do Conselho de Administração ou entidade a quem este delegue</label>
		</div>
	    </div>
	</div>
	
	<div class="row-fluid">
	    <div class="span6">
		<div class="span8">
		    <div class="control-group">
			<label class="control-label bold">Assinatura</label>
		    </div>
		</div>
		<div class="span4">
		    <div class="control-group">
			<label class="control-label bold">Data</label>
			<div class="controls">
			    <span class="text">
				&nbsp;
			    </span>
			</div>
		    </div>
		</div>
	    </div>
	    <div class="span6">
		<div class="span8">
		    <div class="control-group">
			<label class="control-label bold">Assinatura</label>
		    </div>
		</div>
		<div class="span4">
		    <div class="control-group">
			<label class="control-label bold">Data</label>
			<div class="controls">
			    <span class="text">
				&nbsp;
			    </span>
			</div>
		    </div>
		</div>
	    </div>
	</div>
	
	<div class="row-fluid">
	    <div class="span6">
		<div class="control-group">
		    <div class="controls">
			<span class="text">
			    <?php echo str_repeat( '_', 60 ); ?>
			</span>
		    </div>
		</div>
	    </div>
	    <div class="span6">
		<div class="control-group">
		    <div class="controls">
			<span class="text">
			    <?php echo str_repeat( '_', 60 ); ?>
			</span>
		    </div>
		</div>
	    </div>
	</div>
    </div>
    
</div>

<div class="row-fluid margin-bottom-25">
</div>
<div class="row-fluid">
    <div class="span12 text-right">
	<small><em>SECRETARIA DE ESTADO PARA POLÍTICA DA FORMAÇÃO PROFISSIONAL E EMPREGO</em></small>
    </div>
</div>