<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_dec' );
 ?>
    <div class="box-content">
	<div class="row-fluid">
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'name_dec' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'coordenator_name' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'email' ); ?>
		</div>
		<div class="span6">
		    <?php echo $this->form->getElement( 'phone1' ); ?>
		</div>
	    </div>
	    <div class="row-fluid">
		<div class="span6">
		    <?php echo $this->form->getElement( 'phone2' ); ?>
		</div>
	    </div>
	</div>

	<?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>