<!DOCTYPE html>
<html lang="en">
    <head>
	<?php
	    $this->headMeta()
		    ->appendHttpEquiv( 'Content-Language', 'en-US' )
		    ->appendHttpEquiv( 'expires', 'Wed, 26 Feb 2012 08:21:57 GMT' )
		    ->appendHttpEquiv( 'pragma', 'no-cache' )
		    ->appendHttpEquiv( 'Cache-Control', 'no-cache' )
		    ->appendHttpEquiv( 'imagetoolbar', 'no' )
		    ->appendHttpEquiv( 'Content-Encoding', 'gzip' )
		    ->appendName( 'viewport', 'width=device-width, initial-scale=1.0' );
	    
	    $this->headLink()->appendStylesheet( $this->baseUrl( 'public/styles/external.css' ), '' );

	    echo $this->headTitle();
	    echo $this->headMeta() . "\n";
	    echo $this->headLink() . "\n";
	    echo $this->headScript() . "\n";
	?>

        <script type="text/javascript">
            var BASE_URL = '<?php echo $this->baseUrl(); ?>';
        </script>
    </head>

    <body class="page-header-fixed page-full-width">
	<!-- BEGIN HEADER -->
	<div class="header navbar navbar-inverse navbar-fixed-top">
	    <!-- BEGIN TOP NAVIGATION BAR -->
	    <div class="navbar-inner">
		<div class="container-fluid">

		    <a class="brand" href="<?php echo $this->baseUrl( '/external'); ?>">
			<h1>SIMU<span>WEB</span></h1>
		    </a>

		    <!-- BEGIN HORIZANTAL MENU -->
		    <div class="navbar hor-menu hidden-phone hidden-tablet">
			<div class="navbar-inner">
			    <?php echo $this->menuExternal(); ?>
			</div>
		    </div>
		    <!-- END HORIZANTAL MENU -->

		    <ul class="nav pull-right">
			<li class="dropdown">
			    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
				<i class="icon-user pico icon-white"></i>
				<span class="username">
				    <?php echo Client_Model_Mapper_Client::buildNumRow( $this->session->client ); ?>
				    -
				    <?php echo Client_Model_Mapper_Client::buildName( $this->session->client ); ?>
				</span>
				<i class="icon-angle-down"></i>
			    </a>
			    <ul class="dropdown-menu">
				<li>
				    <a href="<?php echo $this->baseUrl( 'auth/logout-external' ); ?>">
					<i class="icon-key"></i> Sai Sistema
				    </a>
				</li>
			    </ul>
			</li>
		    </ul>
		</div>
	    </div>
	</div>
	<div class="page-container row-fluid">


	    <div class="page-content">
		<div class="container-fluid">
		    <div class="row-fluid">
			<div class="span12">
			    <?php
				echo $this->title();
				echo $this->breadcrumb()->setBase( '/external' );
			    ?>
			</div>
		    </div>

		    <?php echo $this->layout()->content; ?>
		</div>
	    </div>
	</div>

	<div class="footer">
	    <div class="footer-inner">
		2013 &copy; Secretaria de Estado para Política da Formação Profissional e Emprego - SEPFOPE. <br />
		Departamento da Informação sobre o Mercado de Trabalho - DMIT.
	    </div>
	    <div class="footer-tools">
		<span class="go-top">
		    <i class="icon-angle-up"></i>
		</span>
	    </div>
	</div>

	<div id="modal-root" class="modal hide fade active" style="width: 75%; margin-left: -35%">
	    <div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
		<h3 class="">
		    <i></i>
		</h3>
	    </div>
	    <div class="modal-body">
	    </div>
	    <div class="modal-footer">
		<button type="button" data-dismiss="modal" class="btn">Taka</button>
	    </div>
	</div>
    </body>

    <script type="text/javascript">
	
	$( document ).ready(
	function() 
	{    
	    App.init();
	}
    );
	    
    </script>

</html>