<div class="form-view">
    <div class="row-fluid">
	<div class="span8">
	    <div class="control-group">
		<label class="control-label bold">Uzuariu:</label>
		<div class="controls">
		    <span class="text"><?php echo $this->note->name; ?></span>
		</div>
	    </div>
	</div>
	<div class="span4">
	    <div class="control-group">
		<label class="control-label bold">Data:</label>
		<div class="controls">
		    <span class="text"><?php echo $this->note->date_insert_formated; ?></span>
		</div>
	    </div>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span8">
	    <div class="control-group">
		<label class="control-label bold">Atividade:</label>
		<div class="controls">
		    <span class="text"><?php echo $this->note->activity; ?></span>
		</div>
	    </div>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span8">
	    <div class="control-group">
		<label class="control-label bold">Rezultadu:</label>
		<div class="controls">
		    <span class="text"><?php echo $this->note->result; ?></span>
		</div>
	    </div>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span8">
	    <div class="control-group">
		<label class="control-label bold">Asaun:</label>
		<div class="controls">
		    <span class="text"><?php echo $this->note->action; ?></span>
		</div>
	    </div>
	</div>
    </div>
</div>