<div class="form-view">
  <div class="row-fluid">
    <div class="span6">
      <div class="control-group">
        <label class="control-label bold">Loron Inisiu:</label>
        <div class="controls">
          <span class="text">
            <?php echo $this->date($this->timeline->date_start); ?></span>
        </div>
      </div>
    </div>

    <?php if (!empty($this->timeline->date_end)) : ?>
    <div class="span6">
      <div class="control-group">
        <label class="control-label bold">Loron Planu Remata:</label>
        <div class="controls">
          <span class="text">
            <?php echo $this->date($this->timeline->date_end); ?></span>
        </div>
      </div>
    </div>
    <?php endif; ?>

  </div>

  <div class="row-fluid">
    <div class="span6">
      <div class="control-group">
        <label class="control-label bold">Atribui ba:</label>
        <div class="controls">
          <span class="text">
            <?php echo $this->timeline->user; ?></span>
        </div>
      </div>
    </div>
    <div class="span6">
      <div class="control-group">
        <label class="control-label bold">Instituisaun:</label>
        <div class="controls">
          <span class="text">
            <?php echo $this->timeline->institution; ?></span>
        </div>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span8">
      <div class="control-group">
        <label class="control-label bold">Deskrisaun:</label>
        <div class="controls">
          <span class="text">
            <?php echo $this->timeline->description; ?></span>
        </div>
      </div>
    </div>
  </div>
</div>