<div class="row-fluid top-news button-dashboard">
     <div class="span6">
	<a href="<?php echo $this->baseUrl( '/client/client/evidence/id/' . $this->case->fk_id_perdata ); ?>" target="_blank" class="btn yellow">
	    <span>Kartaun Evidensia</span>
	    <i class="icon-credit-card top-news-icon"></i>                             
	</a>
    </div>
    <div class="span6">
	<a href="javascript:;" class="btn red" onclick="Client.Case.caseNote( <?php echo $this->id; ?>);">
	    <span>Nota Kazu</span>
	    <i class="icon-edit top-news-icon"></i>
	</a>
    </div>
</div>
<div class="row-fluid top-news button-dashboard">
    <div class="span6">
	<a href="javascript:;" class="btn blue" onclick="Client.Case.appointment( <?php echo $this->id; ?>);">
	    <span>Audiensia</span>
	    <i class="icon-group top-news-icon"></i>                              
	</a>
    </div>
    <div class="span6">
	<a href="javascript:;" class="btn green" onclick="Client.Case.documentsCase();">
	    <span>Dokumentu</span>
	    <i class="icon-folder-open top-news-icon"></i>                              
	</a>
    </div>
</div>
<div class="row-fluid top-news button-dashboard">
    <?php if ( $this->access( Client_Form_ClientInformation::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
	<div class="span6">
	    <a href="<?php echo $this->baseUrl( '/client/client/edit/id/' . $this->case->fk_id_perdata ); ?>" class="btn green">
		<span>Edita dados</span>
		<i class="icon-edit top-news-icon"></i>                             
	    </a>
	</div>
    <?php endif; ?>
    <div class="span6">
	<a class="btn blue" target="_blank" href="<?php echo $this->baseUrl( '/client/client/print/id/' . $this->case->fk_id_perdata ); ?>">
	    <span>Curriculum Vitae</span>
	    <i class="icon-list top-news-icon"></i>
	</a>
    </div>
</div>

<hr />

<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'fk_id_action_plan' );
    echo $this->form->getElement( 'step' );
 ?>
   
    <div class="row-fluid">
	<div class="span12">
	    <table class="table table-striped table-bordered table-hover table-full-width" id="barrier-action-list">
		<thead>
		    <tr>
			<th>Barreira</th>
			<th>Intervensaun</th>
			<th>Se mak halo</th>
			<th>Hahu</th>
			<th style="width: 12%">Taka</th>
			<th class="no-sort">
			    <?php if ( $this->caseActive()->hasAccessEdit() ) : ?>
				<div class="btn-group" style="margin: 0px !important;">
				    <a class="btn green" href="javascript:;" data-toggle="dropdown">
					<i class="icon-ok-circle"></i> Status
					<i class="icon-angle-down"></i>
				    </a>
				    <ul class="dropdown-menu">
					<li>
					    <a href="javascript:;" 
					    onClick="Client.Case.setStatus( '<?php echo Client_Model_Mapper_Case::BARRIER_PENDING; ?>', this );">
						<i class="icon-time"></i> 
						<?php echo $this->nomenclature()->statusCase( Client_Model_Mapper_Case::BARRIER_PENDING ); ?>
					    </a>
					</li>
					<li>
					    <a href="javascript:;" 
					    onClick="Client.Case.setStatus( '<?php echo Client_Model_Mapper_Case::BARRIER_NOT_COMPLETED; ?>', this );">
						<i class="icon-thumbs-down"></i> 
						<?php echo $this->nomenclature()->statusCase( Client_Model_Mapper_Case::BARRIER_NOT_COMPLETED ); ?>
					    </a>
					</li>
					<li>
					    <a href="javascript:;" 
					    onClick="Client.Case.setStatus( '<?php echo Client_Model_Mapper_Case::BARRIER_COMPLETED; ?>', this );">
						<i class="icon-check"></i> 
						<?php echo $this->nomenclature()->statusCase( Client_Model_Mapper_Case::BARRIER_COMPLETED ); ?>
					    </a>
					</li>
				    </ul>
				</div>
			    <?php else : ?>
				Status
			    <?php endif; ?>
			</th>
			<th class="no-sort">Action</th>
		    </tr>
		</thead>
		<tbody></tbody>
	    </table>
	</div>
    </div>

    <?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>

<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>