<div class="box-content">
     <div class="row-fluid">
	<div class="span12 text-center margin-bottom-20">
	    <button type="button" id="button-finish"
		    onClick="Client.Case.finishCase();"
		    class="btn green <?php echo $this->caseActive()->hasAccessEdit() ? '' : 'disabled'; ?>">
		<i class="icon-lock m-icon-white"></i>
		    Taka Kazu
	    </button>
	    <?php if ( $this->access( Client_Form_CaseCancel::ID, Admin_Model_Mapper_SysUserHasForm::SAVE ) ) : ?>
		<button type="button" onClick="Client.Case.cancelCase();" class="btn red" <?php echo $this->caseActive()->hasAccessEdit() ? '' : 'disabled'; ?> >
		    <i class="icon-remove-sign m-icon-white"></i>
		    Kansela Kazu
		</button>
	    <?php endif; ?>
	    <a id="print-certificate hide" class="btn blue" href="<?php echo $this->baseUrl( '/client/case/certificate/id/' . $this->id ); ?>" target="_blank">
		<i class="icon-certificate m-icon-white"></i>
		Print Sertifikadu
	    </a>
	</div>
    </div>
    <div class="row-fluid">
	<table class="table table-striped table-bordered table-hover table-full-width" id="finish-list">
	    <thead>
		<tr>
		    <th style="width: 10%">#</th>
		    <th>Kriterio Sira</th>
		    <th style="width: 10%">Status</th>
		</tr>
	    </thead>
	    <tbody>
		
	    </tbody>
	</table>
    </div>
</div>