<div class="row-fluid">
    <div class="span12">
	<div class="alert alert-info">
	    <i class="icon-info icon-white"></i>
	    <strong>Ba halo rejistu Kazu tenki hili:</strong>
	</div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12 text-center">
	<a class="btn green" href="javascript:;">
	    Kazu ho Ema Barak
	</a>
	<a class="btn red" href="<?php echo $this->path( 'form' ); ?>">
	    Kazu ho Ema ida
	</a>
    </div>
</div>