<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_action_plan' );
    echo $this->form->getElement( 'step' );
    echo $this->form->getElement( 'fk_id_perdata' );
 ?>
    <div class="row-fluid">
	<div class="span6">
	    <?php echo $this->form->getElement( 'fk_id_counselor' ); ?>
	</div>
	<div class="span6">
	    <?php echo $this->form->getElement( 'fk_id_profocupationtimor' ); ?>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span12">
	    <?php echo $this->form->getElement( 'observation' ); ?>
	</div>
    </div>

    <div class="row-fluid">
	<div class="span12">
	    <div class="portlet box light-grey">
		<div class="portlet-title">
		    <div class="caption"><i class="icon-reorder"></i>Planu Asaun</div>
		    <div class="actions">
			<?php if ( $this->caseActive()->hasAccessEdit() ) : ?>
			   <a href="javascript:;" class="btn red" onclick="Client.Case.addBarrier();"> 
				<i class="icon-plus-sign"></i>
				Aumenta
			    </a>
			<?php else : ?>
			    <a class="btn red" href="javascript:;">
				<i class="icon-alert icon-lock"></i>                                   
			    </a>
			<?php endif; ?>
		    </div>
		</div>
                <div class="portlet-body form" style="overflow: auto">
		    <table class="table table-striped table-bordered table-hover table-full-width" id="barrier-list">
			<thead>
			    <tr>
				<th>Tipu Barreira</th>
				<th>Barreira</th>
				<th>Intervensaun</th>
				<th>Se mak halo</th>
				<th></th>
			    </tr>
			</thead>
			<tbody></tbody>
		    </table>
		</div>
	    </div>
	</div>
    </div>

    <?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>

<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>