<?php foreach ($this->rows as $row): ?>
    <tr>
	<td><?php echo $row->user; ?></td>
	<td><?php echo $this->truncate($row->description, 100); ?></td>
	<td><?php echo $this->date($row->date_start); ?></td>
	<td><?php echo $row->date_end ? $this->date($row->date_end) : ''; ?></td>
	<td>
	    <a class="btn green-stripe" href="javascript:;" onclick="Client.Case.detailTimeline( <?php echo $row->id_action_plan_timeline; ?> )">
			<i class="icon-eye-open"></i>
	    </a>
		<?php 
			$userIds = [$row->fk_id_sysuser, $row->fk_id_sysuser_created];
			if (in_array($this->logged_user, $userIds) && $this->caseActive()->hasAccessEdit()): 
		?>
			<a class="btn green" onclick="Client.Case.editTimeline( <?php echo $row->id_action_plan_timeline; ?> );">
				<i class="icon-edit"></i>
			</a>
			<a class="btn red" onclick="Client.Case.deleteTimeline( <?php echo $row->id_action_plan_timeline; ?> );">
				<i class="icon-remove-sign"></i>
			</a>
	    <?php endif;?>
	</td>
    </tr>
<?php endforeach;?>