<div class="row-fluid">
    <table class="table table-striped table-bordered table-hover table-full-width" id="job-barrier-list">
	<thead>
	    <tr>
		<th class="hidden-tablet hidden-phone" style="width: 7%">Kodigu</th>
		<th style="width: 22%">Titulu</th>
		<th>Empreza</th>
		<th style="width: 25%">Okupasaun</th>
		<th style="width: 7%">Status</th>
		<th style="width: 13%">Hetan Serbisu</th>
		<th style="width: 9%">Action</th>
	    </tr>
	</thead>
	<tbody></tbody>
    </table>
</div>