<?php $this->placeholder( 'form' )->captureStart(); ?>
    <div class="box-content">
	
	<div class="row-fluid">
	    <div class="span12">
		<div class="portlet box blue">
		    <div class="portlet-title">
			<div class="caption"><i class="icon-search"></i> Buka Kazu</div>
			<div class="tools"><a class="collapse" href="javascript:;"></a></div>
		    </div>
		    <div class="portlet-body form">
	
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_counselor' ); ?>
			    </div>
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_profocupationtimor' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_fefpeduinstitution' ); ?>
			    </div>
			    <div class="span6">
				<?php echo $this->form->getElement( 'fk_id_addcountry' ); ?>
			    </div>
			</div>
			<div class="row-fluid">
			    <div class="span6">
				<?php echo $this->form->getElement( 'status' ); ?>
			    </div>
			    <div class="span6">
				<?php echo $this->form->getElement( 'type' ); ?>
			    </div>
			</div>

			<div class="row-fluid">
			    <div class="form-actions">
				<button class="btn blue">Buka <i class="icon-search m-icon-white"></i></button>
				<button class="btn green" type="reset" id="clear">Hamoos <i class="icon-trash m-icon-white"></i></button>
			    </div>
			</div>
		    </div>
		</div>
	    </div>
	</div>
	
	<div class="row-fluid">
	    <div class="span12">
		<div class="portlet box blue">
		    <div class="portlet-title">
			<div class="caption"><i class="icon-list"></i> Resultado Buka</div>
			<div class="tools"><a class="collapse" href="javascript:;"></a></div>
		    </div>
		    <div class="portlet-body form">
			<table class="table table-striped table-bordered table-hover table-full-width" id="case-list">
			    <thead>
				<tr>
				    <th style="width: 40%">Naran/Titulu</th>
				    <th style="width: 18%">Konselleiro</th>
				    <th class="date-column">Data Hahu</th>
				    <th>Tipu</th>
				    <th>Status</th>
				    <th style="width: 15%" class="no-sort">Action</th>
				</tr>
			    </thead>
			    <tbody></tbody>
			</table>
		    </div>
		</div>
	    </div>
	</div>
    </div>
<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>