<?php foreach ( $this->rows as $row ) : ?>
    <tr>
	<td><?php echo $row->name; ?></td>
	<td><?php echo $this->truncate( $row->activity ); ?></td>
	<td><?php echo $this->truncate( $row->result ); ?></td>
	<td><?php echo $this->truncate( $row->action ); ?></td>
	<td><?php echo $row->date_insert_formated; ?></td>
	<td>
	    <a class="btn green-stripe" href="javascript:;" onclick="Client.Case.detailNote( <?php echo $row->id_case_note; ?> )">
		<i class="icon-eye-open"></i>                                       
	    </a>
	    <?php if ( $row->fk_id_sysuser == $this->logged_user && $this->caseActive()->hasAccessEdit() ) : ?>
		<a class="btn green" onclick="Client.Case.editNote( <?php echo $row->id_case_note; ?> );">
		    <i class="icon-edit"></i>                       
		</a>
		<a class="btn red" onclick="Client.Case.deleteNote( <?php echo $row->id_case_note; ?> );">
		    <i class="icon-remove-sign"></i>        
		</a>
	    <?php endif; ?>
	</td>
    </tr>
<?php endforeach; ?>