<div class="row-fluid">
    <table class="table table-striped table-bordered table-hover table-full-width" id="job-training-barrier-list">
	<thead>
	    <tr>
		<td style="width: 10%">ID</td>
		<th>Titulu</th>
		<th>Empreza</th>
		<th>Area</th>
		<th style="width: 10%">Posisaun Hira</th>
		<th style="width: 10%" class="hidden-phone hidden-tablet">Status</th>
		<th style="width: 10%" class="hidden-phone hidden-tablet">Hahu ?</th>
		<th style="width: 15%">Action</th>
	    </tr>
	</thead>
	<tbody></tbody>
    </table>
</div>