<?php 
    
    $optionsSelect = array(
	'class'	    => 'm-wrap span12 chosen',
	'multiple'  => false
    );
    
    $attribsValue = array( 
	'class'		=> 'text-right span12 pull-right date-mask date-finish'
    );
    
    if ( !$this->caseActive()->hasAccessEdit() )
	$optionsSelect['disabled'] = true;

    foreach ( $this->rows as $row ) : 
?>
    <tr>
		<td>
			<input type="hidden" name="id_action_barrier[]" value="<?php echo $row->id_action_barrier; ?>" />
			<input type="hidden" name="fk_id_barrier_type[]" value="<?php echo $row->fk_id_barrier_type; ?>" />
			<input type="hidden" name="fk_id_barrier_name[]" value="<?php echo $row->fk_id_barrier_name; ?>" />
			<input type="hidden" name="fk_id_barrier_intervention[]" value="<?php echo $row->fk_id_barrier_intervention; ?>" />
			<?php echo $row->barrier_name; ?>
		</td>
		<td><?php echo $row->barrier_Intervention_name; ?></td>
		<td><?php echo $row->user; ?></td>
		<td><?php echo $row->date_registration_format; ?></td>
		<td>
			<?php
			$dateFinish = null;
			if ( !empty( $row->date_finish_format ) )
				$dateFinish = $row->date_finish_format;
			
			$attribsDate = $attribsValue;
			if ( $row->status == Client_Model_Mapper_Case::BARRIER_COMPLETED )
				$attribsDate['disabled'] = true;
			
			$attribsDate['data-id'] = $row->fk_id_barrier_intervention;
			
			?>
			<div class="control-group">
			<div class="controls">
				<?php echo $this->formText( 'finish[]', $dateFinish, $attribsDate ); ?>
			</div>
			</div>
		</td>
		<td><?php echo $this->nomenclature()->responsible($row->responsible); ?></td>
		<td>
			<?php 
			$optionsCurrentCombo = $optionsSelect;	
			
			if ( $row->status == Client_Model_Mapper_Case::BARRIER_COMPLETED )
				$optionsCurrentCombo['disabled'] = true;
			
			$optionsCurrentCombo['id'] = $row->fk_id_barrier_intervention;
			
			echo $this->formSelect( 'status_combo[]', $row->status, $optionsCurrentCombo, $this->optStatus );  
			?>
		</td>
		<td>
			<div class="btn-group" style="margin: 0px !important;">
			<a class="btn yellow" href="javascript:;" data-toggle="dropdown">
				<i class="icon-bolt"></i> Asaun
				<i class="icon-angle-down"></i>
			</a>
			<ul class="dropdown-menu">
				<li>
					<a href="javascript:;" onClick="Client.Case.timeline( <?php echo $row->id_action_barrier; ?> );">
						<i class="icon-calendar"></i> 
						Liña Tempu
					</a>
				</li>
				<li>
					<a href="javascript:;" onClick="Client.Case.searchJob( <?php echo $row->id_action_barrier; ?> );">
						<i class="icon-briefcase"></i> 
						Buka Empregu
					</a>
				</li>
				<li>
					<a href="javascript:;" onClick="Client.Case.searchClass( <?php echo $row->id_action_barrier; ?> );">
						<i class="icon-book"></i> 
						Buka Turma
					</a>
				</li>
				<li>
					<a href="javascript:;" onClick="Client.Case.searchJobTraining( <?php echo $row->id_action_barrier; ?> );">
						<i class="icon-user-md"></i> 
						Buka OJT
					</a>
				</li>
			</ul>
			</div>
		</td>
    </tr>
<?php endforeach; ?>