<div class="row-fluid">
    <table class="table table-striped table-bordered table-hover table-full-width" id="class-barrier-list">
	<thead>
	    <tr>
		<th style="width: 8%" class="hidden-phone hidden-tablet">Klase</th>
		<th style="width: 10%" class="hidden-phone hidden-tablet">Status</th>
		<th>Naran</th>
		<th>Parceiru</th>
		<th>Kursu</th>
		<th style="width: 13%">Partisipante ?</th>
		<th style="width: 12%">Action</th>
	    </tr>
	</thead>
	<tbody></tbody>
    </table>
</div>