<div class="form-actions no-print">
    <button type="button" class="btn blue" onClick="self.print();"><i class="icon-print"></i> Print</button>
    <button type="button" class="btn red" onClick="self.close();"><i class="icon-remove-sign"></i> Taka</button>
</div>

<?php echo $this->action( 'header-report', 'index', 'default', array( 'id' => $this->fk_id_dec ) ); ?>

<h3 class="text-center">
    JESTAUN KAZU
</h3>

<div class="form-view">
	<h4 class="form-section bold">
	    DADUS KAZU
	</h4>

	<div class="row-fluid">
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label bold">Naran Kliente:</label>
		    <div class="controls">
			<span class="text">
			    <?php echo Client_Model_Mapper_Client::buildName( $this->client ); ?>
			</span>
		    </div>
		</div>
	    </div>
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label bold">Kartaun Evidensia:</label>
		    <div class="controls">
			<span class="text">
			    <?php echo Client_Model_Mapper_Client::buildNumRow( $this->client ); ?>
			</span>
		    </div>
		</div>
	    </div>
	</div>
    
	<div class="row-fluid">
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label bold">Meta Empregu:</label>
		    <div class="controls">
			<span class="text">
			    <?php echo $this->case->ocupation_name_timor; ?>
			</span>
		    </div>
		</div>
	    </div>
	    <div class="span6">
		<div class="control-group">
		    <label class="control-label bold">Konselleru:</label>
		    <div class="controls">
			<span class="text">
			    <?php echo $this->case->name; ?>
			</span>
		    </div>
		</div>
	    </div>
	</div>
    
	<?php if ( !empty( $this->case->observation ) ) : ?>
	    <div class="row-fluid">
		<div class="span12">
		    <div class="control-group">
			<label class="control-label bold">Observasaun:</label>
			<div class="controls">
			    <span class="text">
				<?php echo $this->case->observation; ?>
			    </span>
			</div>
		    </div>
		</div>
	    </div>
	<?php endif; ?>
    
	<div class="row-fluid margin-bottom-25"></div>	
    
	<h4 class="form-section bold margin-bottom-15">
	    PLANU ASAUN
	</h4>
    
	<div class="row-fluid">
	    <div class="span12">
		<table class="table table-striped table-bordered table-hover table-full-width">
		    <thead>
			<tr>
			    <th>Barreira</th>
			    <th>Intervensaun</th>
			    <th>Se mak halo</th>
			    <th>Status</th>
			    <th>Data Hahu</th>
			    <th>Data Remata</th>
			</tr>
		    </thead>
		    <tbody>
			<?php foreach ( $this->barriers as $barrier ) : ?>
			    <tr>
				<td><?php echo $barrier->barrier_name; ?></td>
				<td><?php echo $barrier->barrier_Intervention_name; ?></td>
				<td><?php echo $barrier->user; ?></td>
				<td><?php echo $this->nomenclature()->statusCase( $barrier->status ); ?></td>
				<td><?php echo $barrier->date_registration_format; ?></td>
				<td><?php echo empty( $barrier->date_finish_format ) ? '-' : $barrier->date_finish_format; ?></td>
			    </tr>
			<?php endforeach; ?>
		    </tbody>
		</table>
	    </div>
	</div>
</div>
<div class="row-fluid margin-bottom-25"></div>
 <div class="row-fluid">
    <div class="span4 text-center">
	<div class="row-fluid">Kliente assina iha ne'e</div>
	<div class="row-fluid">&nbsp;</div>
	<div class="row-fluid">
	    ______________________________________________<br/>
            <?php echo Client_Model_Mapper_Client::buildName( $this->client ); ?>
	</div>
    </div>
    <div class="span4 pull-right text-center">
        <div class="row-fluid">
	     <?php
                $auth = Zend_Auth::getInstance()->getIdentity();
                echo $auth->name_dec . ' - ' . Zend_Date::now()->toString( 'dd/MM/yyyy' );
            ?>
	     - Konselleru Profisional Empregu
	</div>
        <div class="row-fluid">
            <br />
        </div>
        <div class="row-fluid">
	    ______________________________________________<br/>
            <?php echo $auth->name; ?>
        </div>
    </div>
</div>
<div class="row-fluid margin-bottom-25"></div>
<div class="row-fluid">
    <div class="span12 text-right">
	<small><em>SECRETARIA DE ESTADO PARA POLÍTICA DA FORMAÇÃO PROFISSIONAL E EMPREGO</em></small>
    </div>
</div>
