<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_action_plan_timeline' );
    echo $this->form->getElement( 'fk_id_action_plan' );
 ?>
    <div class="row-fluid">
        <div class="span4">
            <?php echo $this->form->getElement( 'date_start' ); ?>
        </div>
        <div class="span4">
            <?php echo $this->form->getElement( 'date_end' ); ?>
        </div>
        <div class="span4">
            <?php echo $this->form->getElement( 'institution' ); ?>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <?php echo $this->form->getElement( 'description' ); ?>
        </div>
    </div>

    <?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>

<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>