<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_case_note' );
    echo $this->form->getElement( 'fk_id_action_plan' );
 ?>
    <div class="row-fluid">
	<div class="span12">
	    <?php echo $this->form->getElement( 'activity' ); ?>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span12">
	    <?php echo $this->form->getElement( 'result' ); ?>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span12">
	    <?php echo $this->form->getElement( 'action' ); ?>
	</div>
    </div>

    <?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>

<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>