<?php 
    $this->placeholder( 'form' )->captureStart();
    echo $this->form->getElement( 'id_appointment' );
    echo $this->form->getElement( 'fk_id_action_plan' );
 ?>
    <div class="row-fluid">
	<div class="span6">
	    <div class="span6">
		<?php echo $this->form->getElement( 'date_appointment' ); ?>
	    </div>
	    <div class="span6">
		<?php echo $this->form->getElement( 'time_appointment' ); ?>
	    </div>
	</div>
	<div class="span6">
	    <div class="span8">
		<?php echo $this->form->getElement( 'fk_id_dec' ); ?>
	    </div>
	    <div class="span4">
		<?php echo $this->form->getElement( 'appointment_filled' ); ?>
	    </div>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span6">
	    <?php echo $this->form->getElement( 'fk_id_counselor' ); ?>
	</div>
	<div class="span6">
	    <?php echo $this->form->getElement( 'fk_id_sysuser' ); ?>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span12">
	    <?php echo $this->form->getElement( 'appointment_desc' ); ?>
	</div>
    </div>

    <div class="row-fluid">
	<div class="span12">
	    <div class="portlet box green">
		<div class="portlet-title">
		    <div class="caption"><i class="icon-reorder"></i>Intensaun ba Audiensia</div>
		    <div class="actions">
			<?php if ( $this->caseActive()->hasAccessEdit() ) : ?>
			    <a href="javascript:;" class="btn red" onclick="Client.Case.addAppointmentObjective();"> 
				<i class="icon-plus-sign"></i>
				Aumenta
			    </a>
			<?php else : ?>
			    <a class="btn red" href="javascript:;">
				<i class="icon-alert icon-lock"></i>                                   
			    </a>
			<?php endif; ?>
		    </div>
		</div>
		<div class="portlet-body form">
		    <table class="table table-striped table-bordered table-hover table-full-width" id="appointment-objective-list">
			<thead>
			    <tr>
				<th>Objetivu</th>
				<th></th>
			    </tr>
			</thead>
			<tbody></tbody>
		    </table>
		</div>
	    </div>
	</div>
    </div>

    <?php echo $this->form->getDisplayGroup( 'toolbar' ); ?>

<?php
    $this->placeholder( 'form' )->captureEnd();
    echo $this->form( $this->form->getId(), $this->form->getAttribs(), $this->placeholder( 'form' ) );
?>