<div class="row-fluid">
    <div class="span3">
	<div class="control-group">
	    <label class="control-label">Numeru Rejistu:</label>
	    <div class="controls">
		<span class="text bold">
		    <strong><?php echo Client_Model_Mapper_Client::buildNumRow($this->client); ?></strong>
		</span>
	    </div>
	</div>
    </div>
    <div class="span6">
	<div class="control-group">
	    <label class="control-label">Naran Kliente:</label>
	    <div class="controls">
		<span class="text bold">
		    <?php echo Client_Model_Mapper_Client::buildName($this->client); ?>
		</span>
	    </div>
	</div>
    </div>
    <div class="span3">
	<div class="control-group">
	    <label class="control-label">CEOP Kliente:</label>
	    <div class="controls">
		<span class="text bold">
		    <?php echo $this->client->name_dec; ?>
		</span>
	    </div>
	</div>
    </div>
</div>
<hr />
<div class="tabbable tabbable-custom boxless">
    <?php
		echo $this->tab()
			->addTab(
				array(
					'ref' => 'list-timeline',
					'label' => 'Lista Linã Tempu',
					'released' => true,
					'content' => $this->render('case/list-timeline.phtml'),
				)
			)
			->addTab(
				array(
					'ref' => 'timeline-stream',
					'label' => 'Linã Tempu',
					'released' => true,
					'content' => $this->render('case/timeline-stream.phtml'),
				)
			)
			->addTab(
				array(
					'ref' => 'register-timeline',
					'label' => 'Rejistu Foun',
					'released' => true,
					'content' => $this->render('case/register-timeline.phtml'),
				)
			);
	?>
</div>