<tr>
    <td>
	<?php $atribbsItem = array( 'class' => 'm-wrap span12 focused required' ); ?>
	<div class="control-group">
	    <div class="controls">
		<?php echo $this->formText( 'item_expense[' . $this->expense . '][]', $this->defaultValues['description'], $atribbsItem ); ?>
	    </div>
	</div>
    </td>
    <td>
	<?php $attribsQuantity = array( 'class' => 'm-wrap span12 required expense-quantity' ); ?>
	<div class="control-group">
	    <div class="controls">
		<?php echo $this->formText( 'quantity[' . $this->expense . '][]', $this->defaultValues['quantity'], $attribsQuantity ); ?>
	    </div>
	</div>
    </td>
    <td>
	<?php $attribsPriceUnity = array( 'class' => 'm-wrap span12 expense-amount required money-mask' ); ?>
	<div class="control-group">
	    <div class="controls">
		<?php echo $this->formText( 'amount_unit[' . $this->expense . '][]', $this->defaultValues['amount_unit'], $attribsPriceUnity ); ?>
	    </div>
	</div>
    </td>
    <td>
	<?php $attribsPriceTotal = array( 'class' => 'm-wrap span12 required expense-total money-mask', 'readOnly' => true ); ?>
	<div class="control-group">
	    <div class="controls">
		<?php echo $this->formText( 'amount_total[' . $this->expense . '][]', $this->defaultValues['amount_total'], $attribsPriceTotal ); ?>
	    </div>
	</div>
    </td>
    <td>
	<?php $attribsComments = array( 'class' => 'm-wrap span12 ' ); ?>
	<div class="control-group">
	    <div class="controls">
		<?php echo $this->formText( 'comments[' . $this->expense . '][]', $this->defaultValues['comments'], $attribsComments ); ?>
	    </div>
	</div>
    </td>
    <td>
	<a class="btn red" onclick="Fefop.RIContract.removeItem( this );">
	    <i class="icon-remove-sign"></i>            
	</a>
    </td>
</tr>